src/compiler/generate-xspec-tests.xsl, src/schemas/xspec.rnc
- change schema to allow context in named scenario
- add $impl to context (now $impl:context)
References in original XSpec project:
PR 76: https://github.com/expath/xspec/pull/76
issue 66: https://github.com/expath/xspec/issues/66
=> PR-76 issue #66 allow context in named templates

.travis.yml, src/compiler/generate-query-utils.xql, src/compiler/generate-tests-utils.xsl, test/generate-tests-utils.xspec
This pull request fixes #23 submitted by @AirQuick
The error occurred because of the order of the conditions in [generate-tests-utils.xsl](https://github.com/xspec/xspec/blob/master/src/compiler/generate-tests-utils.xsl):
```xml
<xsl:sequence select="node-name($node1) eq node-name($node2) and
($node1 = '...' or string($node1) eq string($node2))" />
``` 
The condition ```$node1 = '...'``` is raising a compilation error when the value of the node has data type boolean as in the example submitted in #23. In this case the condition is comparing a boolean with a string, hence the compilation error. Because XPath [supports lazy evaluation](https://www.w3.org/TR/xpath/#booleans), it is sufficient to swap the order of the conditions so that the first condition tested is ```string($node1) eq …
```
=> use lazy evaluation to fix data type error

.travis.yml, src/compiler/generate-query-utils.xql, src/compiler/generate-tests-utils.xsl
@AirQuick posted an [additional scenario](https://github.com/xspec/xspec/issues/23#issuecomment-266236525) that causes a compilation error in XSpec. This is an example of a test that it is meant to fail but XSpec generates the same error as in #24 at compilation time:
```bash
Type error on line 453 of generate-tests-utils.xsl:
XPTY0004: Cannot compare xs:boolean to xs:string
Cannot compare xs:boolean to xs:string
```
The error occurs because the node is a boolean in the scenario posted and XSpec is comparing it to a string in [generate-tests-utils.xsl](https://github.com/xspec/xspec/blob/master/src/compiler/generate-tests-utils.xsl):
```bash
$node1 = '...'
```
Forcing the node the return its string value fixes the issue:
```bash
string($node1) = '...'
```
For sake of consistency, I …
=> force to return the string value of node to support other data types #23

bin/xspec.bat
* Made xspec.bat in sync with [xspec.sh](https://github.com/xspec/xspec/blob/8a412363f6435fb4d7d09a624437974332bb3085/bin/xspec.sh) (except for EXPath Packaging System which I haven't used)
* Fixed https://github.com/xspec/xspec/issues/25
* Windows 7  x86 + Java 6 u45      + Saxon-B  8.9.0.4
* Windows 7  x86 + Java 6 u45      + Saxon-HE 9.7.0.7
* Windows 10 x64 + Java 8 u111 x64 + Saxon-EE 9.6.0.10
* Windows 10 x64 + Java 8 u111 x64 + Saxon-EE 9.7.0.14
Running with Saxon 8, the batch file dies with `Error compiling the test suite`, because of the command line syntax difference between 8 and 9. I presume xspec.sh and xspec.bat no longer support 8.
I tested `-q -c` (XQuery + coverage) with [xspec-focus-1.xspec](https://github.com/xspec/xspec/blob/df4959b87cf8054ca4ad8b6d17b627c233dff659/test …
=> Revamp xspec.bat

src/reporter/junit-report.xsl
With Saxon 9.6.0.10, `test\xspec-junit.xspec` fails.
```
P:\xspec-master>bin\xspec.bat test\xspec-junit.xspec
Creating Test Stylesheet...
Running Tests...
Testing with SAXON HE 9.6.0.10
When processing a successful test
convert it to test case with status passed
When processing a failing test
convert it to test case with status failed
FAILED
When processing successful and failing tests
convert it to test cases with status passed and failing
FAILED
Formatting Report...
passed: 1 / pending: 0 / failed: 2 / total: 3
Report available at P:\xspec-master\test\xspec\xspec-junit-result.html
Done.
```
That happens because `fn:serialize()` in `junit-report.xsl` does not omit the XML declaration on Saxon 9.6.
Per the latest [specification](http://www.w3.org/TR/xpath-functions-31/#func-serialize), …
=> test/xspec-junit.xspec fails with Saxon 9.6.0.10

appveyor.yml
* Saxonica usually maintains two versions. (Currently 9.7.x and 9.6.x)
* oXygen, who bundles XSpec, does not always bundle the latest version of Saxon. (The latest oXygen has 9.6.0.7.)
* We've actually seen some differences between the versions.
I think those things justify some extra time of testing with the latest Saxon version minus 0.1.
What do you think?
With this change, AppVeyor tests XSpec with Saxon 9.7 and 9.6, and should work like [this](https://ci.appveyor.com/project/AirQuick/xspec/build/13-master) when it detects https://github.com/xspec/xspec/pull/40.
Although the latest 9.6 is 9.6.0.10, I chose 9.6.0.7 just because it's the one bundled currently in oXygen.
=> Test with Saxon n and n-0.1

test/xspec-bat.cmd, test/xspec.bats
This pull request addresses #39. 
It amends two bats tests which should be testing that XSpec is generating the XML and HTML reports when it is executed without any option. The ```-j``` option was erroneous so I removed it.
=> remove -j option in tests #39

.travis.yml, README.md
This pull request addresses #44.
Tests are run in parallel by Travis using different values for the environment variable ```SAXON_CP```:
**Summary of commits**
- 0f3317c replaces the hard-coded branch with the default environment variable ```TRAVIS_BRANCH``` which:
- for builds not triggered by a pull request it is the name of the branch currently being built; 
- for builds triggered by a pull request it is the name of the branch targeted by the pull request (usually ```master```).
- 6691792 download the two versions of Saxon and executes a matrix build similar to what @AirQuick implemented with AppVeyor in #43 
-  7258643 add a link to Travis build page
**Reviewer**
@AirQuick, could you please review this pull request?
=> Run tests in Travis for both Saxon HE 9.7.0-14 and 9.6.0-7

src/compiler/generate-xspec-tests.xsl
Fixes #46 
If `$impl:test-result` happens to be determined statically as a non `xs:boolean`, a warning is raised for `$impl:successful`.
The spec allows raising type errors at XSLT compile time if there is code that would always deliver a value of the wrong type, even if that code is never executed.
So it is `generate-xspec-tests.xsl`'s responsibility to keep the expression valid.
=> Always provide xs:boolean in $impl:successful expression

.travis.yml, src/compiler/generate-xspec-tests.xsl, test/xspec-46.xsl, test/xspec-46.xspec, test/xspec.bats
I implemented a bats test for the shell script that covers issue #46 and pr #48. This test uses the examples in #46 and checks that a warning is not raised. The bats test is using the `=~` operator for testing a partial match in line 3 of the shell output. This operator is bash specific (as opposed to POSIX shell) but works fine when run via Travis.
=> add bats test issue #46 / pr #48

test/run-xspec-tests.cmd, test/xspec-bat.cmd
This change makes the tests on AppVeyor parity with Travis
* Mimic `=~` operator of Bats
* Copy [the test case](https://github.com/xspec/xspec/blob/ba5f97c903d0022d322d7af7e379b6fbcaf35ee6/test/xspec.bats#L172-L177)
=>  Add a test case for issue #46 / pr #48  for Windows

LICENSE, README.md
This PR addresses #52. Main changes include:
- add release badge (displayed when the release is available)
- remove references to maven plugins as XSpec plugins are in the process to be consolidated under the XSpec organisation
- remove reference to jxsl (this project doesn't seem to be active anymore)
- add section Contribute
- update License section and years in copyright
=> Prepare XSpec for release v0.5.0

.travis.yml, appveyor.yml
Saxon 9.6 series got an update in December 2016
=> Use latest Saxon 9.6.0-10 for ci tests

src/compiler/generate-tests-utils.xsl, test/generate-tests-utils.xspec, test/xspec-50.xspec, test/xspec-55.xspec
Fixes #50 
* `test:atom-type()` now covers all the built-in types supported by every XSLT 2.0 processor.
Fixes #55 
* `test:report-atomic-value()` now returns valid expressions for decimal, double and integer.
Also added are
* Unit tests for `test:atom-type()` and `test:report-atomic-value`
* Regression tests for #50 and #55. Actually they test `test:report-value()`. I'm not sure if this is the best way.
=> Report all the basic types and valid numeric expressions

src/compiler/generate-xspec-tests.xsl
Fixes #47
This change keeps the type annotations in `$impl:test-items` by creating an [implicit document node](http://www.w3.org/TR/xslt20/#temporary-trees).
Another option would be creating the document node explicitly with `validation="preserve"`. But the `validation` attribute is not available on Saxon-HE. Not a viable option.
No regression test at the moment. Reproducing the bug requires Saxon-EE.
=> Keep type annotations in $impl:test-items

.travis.yml, appveyor.yml
* 9a75af7ef08fa322e139b89ce38c082723642e4c increments the Saxon 9.7 maintenance version
* b756310088dcb95be771f007eabc45adbbaa2ca9 and 47b1d168d8060c210460e9cd2f8e919b4db58525 are not directly related to the Saxon version. They are only to align some details of `appveyor.yml` with those of `.travis.yml`.
=> Run tests with Saxon 9.7.0-15

src/reporter/test-report.css
A trivial change to show a ruddy vertical bar.
To see the effect, run `bin/xspec.sh tutorial/escape-for-regex.xspec` or whatever to generate a report HTML. Open the report HTML file (such as `tutorial/xspec/escape-for-regex.html`) in a web browser and click any in-page link.
=> Highlight the link target in report HTML

appveyor.yml, test/xspec-bat.cmd, test/xspec.bats
Following #76, this pull request adds XProc test to the test set on AppVeyor.
* For the simulated failure, see the AppVeyor/Travis test result of 2173614 in [the commit log](https://github.com/AirQuick/xspec/commits/win_xproc). (It expects 'UTF-7' and thus failed.)
* `xspec.bats` is also modified a bit. (in order to be more platform independent)
* `'&#x0A;'` is added to XQuery. (in order to avoid conflict with the "Picked up JAVA_TOOL_OPTIONS..." stderr line which is emitted when the `JAVA_TOOL_OPTIONS` environment variable is defined)
=>   Run XProc test on AppVeyor

.travis.yml, test/xspec.bats
This pull request aligns the Travis configuration with the AppVeyor configuration implemented in #86.
#76 introduced a test for checking that the XProc harness is working. Running XProc requires XMLCalabash which is installed in the ```.travis.yml``` file. However, XMLCalabash currently comes bundled with Saxon 9.7.0.11 as highlighted by @AirQuick in https://github.com/xspec/xspec/pull/86#discussion_r104289634. It is therefore useless to install it and run the test for XProc when a lower version of Saxon is used. This also makes the test suite slower.    
In ```.travis.yml``` I added the ```XMLCALABASH_VERSION``` in the matrix as suggested by @AirQuick in https://github.com/xspec/xspec/pull/86#discussion_r104293014. This is in line with the configuration in ```appveyor.yml``` and also …
=> Align Travis configuration with AppVeyor in #86

src/harnesses/harness-lib.xpl, src/harnesses/saxon/saxon-xquery-harness.xproc, src/harnesses/saxon/saxon-xslt-harness.xproc, test/xspec-bat.cmd, test/xspec.bats
This pull request is part of the code review for #103 and addresses the XProc harness for Saxon. See https://github.com/xspec/xspec/pull/103#issuecomment-286272902 for details. This pull request has been approved in https://github.com/xspec/xspec/pull/103#issuecomment-286288272.
The XProc harness was reverted to v0.3.0 in https://github.com/xspec/xspec/commit/ad6b0412afdf9f95feeb5b6c0e99804fa34d7bfc because it didn't seem to work. @fgeorges fixed this as part of #103 and provided information on how to run it so that the XProc harness implemented in v0.4.0-RC can be now used.
The library ```harness-lib.xpl``` is used for this XProc harness and can be re-used for other harnesses. One of the major changes from v0.3.0 is the use of the ```-p``` option in front of the parameter …
=> add XProc harness for Saxon from v0.4.0

test/generate-xspec-tests.xspec, test/run-xspec-tests.cmd, test/run-xspec-tests.sh
Fixes #109.
Just printing `result.log` would be the simplest way for now. So here it is.
What happens with this change on a test failure:
* [Travis](https://travis-ci.org/AirQuick/xspec/jobs/211437161#L218-L241)
* [AppVeyor](https://ci.appveyor.com/project/AirQuick/xspec/build/134-fix_issue-109/job/03fkwbp6dtew71hs#L140)
=> run-xspec-tests.*: Print result.log on failure

test/generate-tests-utils.xspec, test/generate-x-utils.xspec
Currently `test/generate-tests-utils.xspec`, despite its filename, has scenarios both for XSLT (`src/compiler/generate-tests-utils.xsl`) and XQuery (`src/compiler/generate-query-utils.xql`). So three kinds of scenarios coexist in `test/generate-tests-utils.xspec`:
* (a) Scenarios which should be Success both on XSLT and XQuery
* (b) Scenarios which should be Success on XSLT and Failure on XQuery (Some features/fixes not implemented yet in `src/compiler/generate-query-utils.xql`)
* (c) Scenarios which do work on XSLT but somehow do not work on XQuery (#82)
This pull request does two things:
* Moves (a) to a new file `test/generate-x-utils.xspec`
* Adds TODO comments to `test/generate-tests-utils.xspec`
In consequence,
* #82 is resolved tentatively. (We can run `test/generate-x-utils.xspec` …
=> Separate common tests (for XSLT and XQuery) from generate-tests-utils.xspec (only for XSLT) 

test/xspec-result-naming-collision.xslt, test/xspec-result-naming-collision.xspec
Fixes #95.
* For the namespace URI, I simply took the original pull request's URL. Any other suggestion is welcomed.
* I searched the `test` directory for the string `functx` and confirmed that no other `functx` string existed there.
* Before and after making this change, I ran `xspec-result-naming-collision.xspec` and confirmed that the generated report HTML did not change (except for the timestamp).
=> Stop using functx namespace in unrelated func

src/reporter/format-utils.xsl
Fixes #90.
Before and after committing this change, I created `*.html` files using the following commands.
```winbatch
set TEST_DIR=
bin\xspec.bat tutorial\escape-for-regex.xspec
test\run-xspec-tests.cmd
set TEST_DIR=tutorial\xspec-c
bin\xspec.bat -c tutorial\escape-for-regex.xspec
set TEST_DIR=tutorial\xspec-j
bin\xspec.bat -j tutorial\escape-for-regex.xspec
set TEST_DIR=test\xspeq-q
for %I in ( focus-1 focus-2 function import pending variable ) do bin\xspec.bat -q test\xspec-%I.xspec
set TEST_DIR=
```
By comparing the `*.html` files, I verified that the commit did the followings:
* Fixed #90
* Did not change the HTML structure unrelated to #90
=> Do not copy unused namespaces from format utils to output

src/compiler/generate-xspec-tests.xsl, test/xspec-bat.cmd, test/xspec.bats
This pull request addresses #119 and allows to run an XSpec test stored in a folder which has an apostrophe in its name.
In ```generate-xspec-tests.xsl``` I replaced the apostrophe with the encoded character ```%27``` as suggested by @raducoravu in https://github.com/xspec/xspec/issues/119#issue-221183560. A similar solution was also suggested by Michael Kay (see [XSLT 2.0 book](http://p2p.wrox.com/xslt/50152-how-do-you-translate-apostrophe.html#post182183) and [Stackoverflow](http://stackoverflow.com/a/12406443)). I used ```replace()``` instead of ```translate()``` as in the original post from @raducoravu although I think both functions can achieve the same result. 
I added a test in ```bats.xspec``` that creates a folder ```some'path```, copy the tutorial example in this folder, and …
=> Run XSpec test in folder with an apostrophe in its name (#119)

bin/xspec.sh, test/xspec.bats
Following discussions with @hanshuebner, @fgeorges, and @AirQuick in #121 and #122, I submit this pull request which hopefully sums up and includes your previous pull requests and comments on the saxon script being properly checked. I also added a test for the shell script that simulates the use of the saxon script. 
I [previously wrote](https://github.com/xspec/xspec/pull/122#discussion_r111888470) that the ```which``` command was not necessary in the condition. I was actually wrong as without it the shell script returns an error message ```command not found``` instead of evaluating to ```false```. The other conditions can be piped together without side effects as the passing test shows.
If you agree with these changes, just add a thumb up or approve it and I will merge into ```master``` …
=> Add checks for saxon script + test

.travis.yml, src/harnesses/basex/basex-standalone-xquery-harness.xproc, test/xspec.bats, tutorial/xquery-tutorial.xq, tutorial/xquery-tutorial.xspec
This pull request integrates the XProc test harness for BaseX standalone developed by @fgeorges in #103. 
I took the [XProc test harness for BaseX standalone](https://github.com/xspec/xspec/blob/fix/revert-revert-reverting/src/harnesses/basex/basex-standalone-xquery-harness.xproc) from #103 as developed it by @fgeorges. I added the following files:
- Documentation on how to run the XProc harness for BaseX standalone in the [wiki](https://github.com/xspec/xspec/wiki/Running-with-BaseX)
- [Bats test](https://github.com/xspec/xspec/blob/review/103-basex/test/xspec.bats#L275-L285) for Linux/MacOS that runs the XProc harness for BaseX standalone
- XQuery tutorial files: [xquery-tutorial.xq](https://github.com/xspec/xspec/blob/review/103-basex/tutorial/xquery-tutorial.xq) and …
=> add XProc harness for BaseX standalone (review #103)

bin/xspec.bat, bin/xspec.sh, test/xspec-bat.cmd, test/xspec.bats
As discussed in pull request #129: suppress warning message "Running an XSLT 10 stylesheet with an XSLT 20 processor" during Schematron compilation and clean up temporary files.
=> From pull request #129 discussion: suppress warning message and clean up temporary files

bin/xspec.bat, bin/xspec.sh, test/schematron/schematron-xslt-compile.xsl, test/schematron/schematron-xslt-expand.xsl, test/schematron/schematron-xslt-include.xsl, test/xspec-bat.cmd, test/xspec.bats
This change adds the ability for Schematron XSLTs to be provided externally. This will help with using XSpec to test the Schematron XSLTs (see [Schematron Issue 49](https://github.com/Schematron/schematron/issues/49)) and may help with testing customizations of the Schematron XSLTs (see http://schematron.com/front-page/the-schematron-skeleton-implementation/). To use external Schematron XSLTs set/export the following environment variables with the path to the XSLTs for XSpec to use when compiling a Schematron schema.
* SCHEMATRON_XSLT_INCLUDE - the default is iso_dsdl_include.xsl
* SCHEMATRON_XSLT_EXPAND - the default is iso_abstract_expand.xsl
* SCHEMATRON_XSLT_COMPILE - the default is iso_svrl_for_xslt2.xsl
=> Allow Schematron XSLTs to be provided externally

test/xspec-focus-1.xspec, test/xspec-function.xspec, test/xspec-imported.xspec, test/xspec-pending.xspec, test/xspec-rule.xspec
Related to #4.
df4959b87cf8054ca4ad8b6d17b627c233dff659 added/removed `focus`/`pending` as workaround.
I understand the workaround was necessary. However, the workaround makes it hard to distinguish the genuine `focus`/`pending` from the workaround ones.
This change gives explicit TODO comments to the workaround ones.
@cirulls,
Can you please verify I have put the correct TODOs at the right places?
If ok, please consider merging this.
=> TODO comments for #4

.travis.yml, appveyor.yml
Just move on to the latest maintenance release of Saxon 9.7.
9.7.0.20 released on 28 July 2017
=> Test with Saxon 9.7.0.20

.travis.yml
This pull request unset the `_JAVA_OPTIONS` environment variable from Travis builds so that the message `Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m` is not displayed in bats tests.
[Build #404](https://travis-ci.org/xspec/xspec/jobs/281928612) failed in Travis because some bats tests added the message `Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m` in their output thus messing up the line to be checked and making the test fail. 
This seems to be due to a recent change in Travis that explicitly sets this option in Java (see https://github.com/travis-ci/travis-ci/issues/8408 and [Travis release 2017-09-06](https://docs.travis-ci.com/user/build-environment-updates/2017-09-06/)). Unsetting `_JAVA_OPTIONS` as suggested [here](https://github.com/rspec/rspec-dev/pull/185/commits/f4cca9294777cf6dca …
=> Remove JAVA_OPTIONS message from output in Travis

.travis.yml, bin/xspec.bat, bin/xspec.sh, src/schemas/xspec.rnc, src/schematron/schut-to-xspec.xsl, test/schematron-012.xspec, test/schematron-016.sch, test/schematron-016.xspec, test/schematron-017.xspec, test/schematron-018.xspec, test/schematron-019.xspec, test/schematron-020.xspec, test/schematron-021.xspec, test/schematron-022.xspec, test/schematron/data/standards.xml, test/schematron/schematron-017.sch, test/schematron/schematron-018.sch, test/schematron/schematron-019.sch, test/schematron/schematron-020-01.sch, test/schematron/schematron-020.sch, test/schematron/schematron-021.sch, test/schematron/schematron-022.sch, test/schematron/schut-to-xspec-012-out.xspec, test/schut-to-xspec-012.sch
Pull request for issue #140. 
Improvements to Schematron support:
* Added new element `<x:expect-rule>` to test that a rule is fired/thrown.
* Added new attribute `@count` to test that an assert, report, or rule is thrown a specific number of times.
* Changed the RelaxNG grammar to allow `<x:expect>` in scenarios that have Schematron-specific expect elements.
* Changed the location of the compiled Schematron XSLT to the same folder as the Schematron so that relative file paths that are used within the Schematron will work. 
* Extended the `@id` attribute matching to include the `@id` attribute on the Schematron pattern element.
=> Balisage improvements to Schematron support

.travis.yml, appveyor.yml
Reflects the new 9.8 and the latest 9.7 maintenance releases.
This PR effectively removes 9.6 from testing. Since 9.6 is not actively maintained, I think it's ok.
=> Test on Saxon 9.8.0.7, 9.7.0.21 and 9.7.0.19

test/xspec-bat.cmd, test/xspec.bats
This pull request adds a test to check that the HTML report contains an inline CSS. This feature was introduced in #135 and this test checks that the inline CSS is always generated. 
The test does a simple search (grep) in the generated HTML report and checks that there is a line with the opening style element (`<style type="text/css">`) and with a CSS property (I chose randomly `margin-right`).
@AirQuick : would you be able to add a similar test for the batch script? Feel free to check out and commit directly to this branch so that we can merge the pull request with both tests. But it's also fine if you prefer to work on a separate branch and merge with two separate commits. Let me know the test makes sense to you and if you would like to add more checks for #135.
=> Add tests for CSS inline in #135

bin/xspec.bat, bin/xspec.sh, src/reporter/coverage-report.xsl
As proposed by #AirQuick, added a parameter to allow to create inlined CSS, and another one to specify CSS location.
Based on current master.
=> Proposal issue 192 (Enhance coverage-report.xsl to be able to specify css location)

bin/xspec.bat, bin/xspec.sh, src/reporter/coverage-report.xsl
`coverage-report.xsl` has two half-baked parameters `tests` and `pwd`. They put a burden upon its caller: https://github.com/xspec/xspec/blob/0e21fca458505ad9b2048e3b42a06a99952a7e3e/bin/xspec.bat#L535-L586
This pull request removes `pwd` and resolves `tests` within `coverage-report.xsl`.
The change depends on [`file:path-to-uri()`](http://www.saxonica.com/documentation/index.html#!functions/expath-file/path-to-uri) which requires Saxon-PE or EE. That shouldn't be a problem, because `coverage-report.xsl` requires Saxon-PE+ in the first place.
Verified that the pull request generated the same coverage reports as the current master, using the files from #197 and these command lines:
Windows
```winbatch
bin\xspec.bat -c tutorial\coverage\demo.xspec
bin\xspec.bat -c …
```
=> Resolve native file path to URI in coverage-report.xsl

.travis.yml, appveyor.yml, bin/xspec.bat, bin/xspec.sh, test/catalog/catalog-01-catalog.xml, test/catalog/catalog-01-doc.xml, test/catalog/catalog-01-xquery.xspec, test/catalog/catalog-01-xslt.xspec, test/catalog/catalog-01.dtd, test/catalog/catalog-01.xquery, test/catalog/catalog-01.xslt, test/xspec-bat.cmd, test/xspec.bats
This pull request is to add support for OASIS XML Catalogs to `xspec.bat` and `xspec.sh` as requested in issue #167. 
Here are suggestions for changes to the wiki documentation to describe this feature:
* Create a new page about XML Catalog support using the information in [this comment](https://github.com/xspec/xspec/issues/167#issuecomment-367173274).
* Add a link to the XML Catalog page from the pages for [Installation on Windows](https://github.com/xspec/xspec/wiki/Installation-on-Windows) and [Installation on Max and Linux](https://github.com/xspec/xspec/wiki/Installation-on-Mac-and-Linux) for optional additional installation steps to enable catalog support.
* Update the [Environment Variables](https://github.com/xspec/xspec/wiki/Environment-Variables) page to add the new environment …
=> Support for XML Catalogs in xspec.bat/sh

build.xml, src/ant/get-schematron-phase.xsl, test/xspec-bat.cmd, test/xspec.bats
Fixes #168
If the user sets no `xspec.phase` property and the .xspec file defines no phase in Schematron testing, `build.xml` sets a bogus phase parameter at STEP 3.
So the user has to set `xspec.phase` explicitly, when testing `demo-03.xspec`. Though that's how the original PR #160 was designed, the design is not aligned with `xspec.bat/sh` which works more friendly.
With this PR, the user no longer has to set `xspec.phase` when testing `demo-03.xspec` and the like.
=> Schematron Ant: Do not set bogus phase parameter when phase is undefined

test/end-to-end/cases/expected/xspec-xslt2-result-norm.html, test/end-to-end/cases/xspec-xslt2.xspec, test/xspec-xslt1.xsl, test/xspec-xslt1.xspec
This PR just adds some tests for `/x:description/@xslt-version`.
No code change involved.
---
FWIW, `test/xspec-xslt3.xspec` has `xslt-version="3.0"` but it no longer influences the test result.
The test is successful even when there is no `xslt-version` or when there is `xslt-version="1.0"`.
I guess it's because of [this](http://www.saxonica.com/documentation/index.html#!conformance/xslt30):
> Saxon (from release 9.8) acts as an XSLT 3.0 processor whether this is explicitly requested or not. Specifying version="1.0" or version="2.0" does not prevent the use of 3.0 features
=> Add xslt-version tests

src/reporter/format-xspec-report.xsl, test/xspec-bat.cmd, test/xspec.bats
This pull request just adds some tests which verify the output from Ant.
This change ensures that the future code changes to Ant won't declare BUILD SUCCESSFUL without actually running XSpec tests.
No code change in XSpec core.
=> Test Ant more closely

src/reporter/coverage-report.xsl
Put xsl:analyze-string inside a variable, tagging the unprocessed residue of the string separately as test:residue. Then, output the part of the string you processed (xsl:copy-of) and, lastly, call this template recursively if there is anything left to process.
Credit goes to Saxonica. This change works with XSLT 2.0. (The diff is noisy due to indentation.)
Beware: This change works with Saxon-EE 9.7.0.21J but not 9.8.0.12. I have reported the v9.8.0.12 problem to Saxonica.
=> Tail recursion in test:output-lines template (version-dependent)

bin/xspec.bat
This pull request fixes typo in `xspec.bat` just as #223 did in `xspec.sh`.
=> Fix typo in xspec.bat (formating)

src/ant/locate-schematron.xsl
This pull request just adds some comments to `src/ant/locate-schematron.xsl` to clarify why those lines are necessary.
=> Add comment to locate-schematron.xsl

.travis.yml, appveyor.yml
This pull request just updates the version of XML Calabash, used on Travis and AppVeyor, to 1.1.21-97: https://github.com/ndw/xmlcalabash1/releases/latest
=> Test with XML Calabash 1.1.21-97

appveyor.yml
Following the recent [incident](https://appveyor.statuspage.io/incidents/kqwjgg14m71g), this pull request just adds `appveyor-retry` before `choco install` in `appveyor.yml`
=> Add appveyor-retry before choco install

pom.xml
This pull request addresses the discussion in [#395](https://github.com/xspec/xspec/issues/395#issuecomment-429645051) and updates the version number to the latest XSpec release. Other minor changes include updates in the year for the copyright and the use of 'XSLT' instead of 'Xsl' in the description.
@cmarchand: could you review this pull request and check that it is fine? I have not included the second patch that uses the version `1.1.1-SNAPSHOT`, I guess this will be applied at the next release (please correct me if I'm wrong).
=> Update for XSpec release v1.1.0

bin/xspec.bat
XSpec failed with message:
```
find: ÔÇÿdÔÇÖ: No such file or directory
ERROR: XSPEC_HOME is not a directory
```
It seems the "find"-command is supposed to look for a letter "d" in file properties.
correct command for this task seems to be "findstr".
Line 281 changed this way things work
=> Fix "find"-command in `xspec.bat`

tutorial/under-the-hood/Compilation.md, tutorial/under-the-hood/README.md
This pull request copies `Compilation.md` from the latest Wiki.
* Why this PR is necessary is demonstrated in #475:
* We need to propose changes to documentation and example files at once
* And then we need to collaborate on the proposed changes
* I don't think this PR will affect user-friendliness of documentation. `Compilation.md` talks about the internal details. The other docs in the current Wiki focus more on the ordinary usage.
* I chose `tutorial/under-the-food/` just because I couldn't find a better place among the existing directories.
* `Compilation.md` in this pull request is an exact copy of the latest Wiki.
* We'll make further changes on it or add its companion files via other pull requests including #475.
* Remove `Compilation.md` from Wiki repository and its sidebar.
* …
=> Move Compilation.md from Wiki

pom.xml
Looking back the operations happened when releasing v1.1.0 and following https://github.com/xspec/xspec/pull/415#issuecomment-455510906, I guess this is the last required change for v1.2.0 and to be merged immediately before tagging it.
Ccing @cmarchand just in case.
=> Remove -SNAPSHOT from version in pom.xml for v1.2.0

pom.xml
According to https://github.com/xspec/xspec/wiki/pom.xml-version which is based on https://github.com/xspec/xspec/pull/415#issuecomment-455510906, I guess this should be the very first change when we start v1.3.0 after completing v1.2.0 release.
Feel free to resolve conflict if any.
=> Increment version in pom.xml to 1.3.0-SNAPSHOT

tutorial/under-the-hood/Compilation.md
This pull request fixes up namespaces in `Compilation.md` (and attempts to simplify #475 in part).
* 680e12b775e8c6533bf6cbc2b2e4bece9bed2916 replaces `t:` with `x:`, because `t:` seems to be an old minor convention and mixing `x:` and `t:` just complicates the overall description. What do you think, @galtm ?
* 31dd8a47987c35763b74764033f05b562609a7ab prefixes XSpec element names with `x:`.
* The other commits fix namespaces to reflect the actual behavior.
=> Fix up namespaces in Compilation.md

test/end-to-end/processor/junit/_normalizer.xsl
A trivial change to harden a template in an end-to-end test normalizer for JUnit.
=> JUnit end-to-end test: More specific template result type

test/end-to-end/README.md
This wiki change is to answer a question I had the first time I reviewed some files in the test/end-to-end area.
=> Noting CSS difference between actual and expected

src/harnesses/basex/basex-standalone-xquery-harness.xproc
a6bb23507e11277d07b06914fc9a5590401e22f7 changed the format of `src/harnesses/basex/basex-standalone-xquery-harness.xproc`, which made it difficult to see the actual changes.
This pull request restores the original format. No code change.
As a result, the file is reverted to 86af4b57e599b02d22a1fe79011ea040db86eb77.
=> Restore format of basex-standalone-xquery-harness.xproc

.travis.yml
Looks like Travis CI is gradually deploying Ubuntu Xenial 16.04 as the default Travis CI build environment
https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
Unfortunately, [on Travis with Ubuntu Xenial](https://travis-ci.org/AirQuick/xspec/jobs/562906822#L9), `jdk: oraclejdk8` [fails](https://travis-ci.org/AirQuick/xspec/jobs/562906822#L160-L167).
(See also https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766)
We could switch to `openjdk8` or something. But if we do so, we would need to recompile [`XSLTCoverageTraceListener.class`](https://github.com/xspec/xspec/blob/master/java/com/jenitennison/xslt/tests/XSLTCoverageTraceListener.class) otherwise [a test](https://github.com/xspec/xspec/pull/296) …
=> Set dist trusty in .travis.yml

test/schematron-012.xspec, test/schematron/schut-to-xspec-012-out.xspec
This pull request just fixes a typo in `test/schematron-012.xspec`.
=> Fix typo 'inherrit' in schematron-012.xspec

src/reporter/format-utils.xsl
This pull request just simplifies how `test:disable-escaping` (introduced by #369) manages intermediate characters.
I manually verified that this pull requests generates the same HTML files as the ones generated by the current master.
=> Simplify test:disable-escaping characters

test/schut-to-xspec-012.sch
Saxon warns about `div` (element name vs math division) in `test/schut-to-xspec-012.sch`:
```console
C:\xspec>bin\xspec.bat -s test\schematron-012.xspec
...
Running Tests...
Testing with SAXON EE 9.9.1.2
expect-valid
Warning in xsl:if/@test on line 311 column 29 of schut-to-xspec-012.sch-compiled.xsl:
SXWN9000: in {div[}:
The keyword 'div' in this context means 'child::div'. If this was intended, use
'child::div' or './div' to avoid this warning.
```
This pull request addresses it.
=> Address SXWN9000 (child::div) in schut-to-xspec-012.sch

src/compiler/generate-common-tests.xsl, src/compiler/generate-query-tests.xsl, test/xspec-no-prefix.xspec, test/xspec-no-prefix_schematron.xspec, test/xspec-no-prefix_stylesheet.xspec
Closes #572 
This pull request 
* sets a fallback prefix (`XsPeC:`) when the test author does not provide a prefix to the XSpec namespace (`http://www.jenitennison.com/xslt/xspec`) in `x:description`.
* also modifies a namespace declaration on XQuery so that it works without a prefix.
As far as I know, most test authors provide a prefix (`x:` in most cases) to the XSpec namespace. [SchXslt](https://github.com/schxslt/schxslt/tree/master/src/test/resources/spec) is the only use case I've ever found. So I didn't write the test for this pull request extensively.
* `xspec-no-prefix.xspec` tests both XQuery and XSLT.
* For Schematron (`xspec-no-prefix_schematron.xspec`) and XSLT-only (`xspec-no-prefix_stylesheet.xspec`), I just copied some of the existing test files and removed the `x:` …
=> Accept x:description without XSpec namespace prefix

pom.xml
Following our [release workflow](https://github.com/xspec/xspec/wiki/Release-Workflow), this PR increases the version of the `pom.xml` file in order to prepare for the next XSpec release (probably v1.5.0) and allow developers to publish Maven artifacts before an official release is made.
=> release: maven snapshot version for development

src/compiler/generate-query-tests.xsl, src/compiler/generate-xspec-tests.xsl, src/reporter/format-xspec-report-folding.xsl, test/end-to-end/ant/base/worker/generate.xsl
This pull request just removes `static-base-uri()` calls which are not necessary.
There is no automated test for `format-xspec-report-folding.xsl`. So I manually tested this pull request and verified this:
* `ant -lib "saxon9ee.jar" -Dxspec.xml=tutorial\escape-for-regex.xspec -Dxspec.html.reporter.xsl=src\reporter\format-xspec-report-folding.xsl` generates the same `escape-for-regex-result.html` as the current master (except for timestamp).
=> Remove unnecessary static-base-uri()

src/compiler/generate-xspec-tests.xsl, test/end-to-end/cases/expected/stylesheet/mode-all-junit.xml, test/end-to-end/cases/expected/stylesheet/mode-all-result.html, test/end-to-end/cases/expected/stylesheet/mode-all-result.xml, test/end-to-end/cases/mode-all.xsl, test/end-to-end/cases/mode-all.xspec
Closes #592
This pull request provides some tests with `mode="#all"` template in the stylesheet being tested.
* 5624863a50901b132cf267b6a2b75681d2ca0837
Primary commit.
The test has to be in `test/end-to-end/`, because the conflict between `#all` template and XSpec happens when XSpec constructs the test failure report.
* c58ffe630d9f003a25c7d7f24c436f5ff43c0be2
Temporary commit for demonstrating a test failure ([Travis](https://travis-ci.org/AirQuick/xspec/jobs/577743778#L1966-L2079), [AppVeyor](https://ci.appveyor.com/project/AirQuick/xspec/builds/27012822/job/5omdch9r2q9go08k#L865))
* abbc2953369262bc202adf07d4a476439722fd9f reverts the temporary commit
=> Test with mode="#all"

test/xspec-utils_stylesheet.xspec
This pull request just adds some test cases for [`x:is-user-content()`](https://github.com/xspec/xspec/blob/877ed425593ee7ec613669c5df8ce8723013ab7e/src/common/xspec-utils.xsl#L156-L174) with `x:variable`.
The function was created in acd72e031466be8dafb9c5945d452d53e50212cc but it didn't have tests with `x:variable` which wasn't available at that time.
=> Test x:is-user-content() with x:variable

appveyor.yml, test/win-bats/collection.xml, test/win-bats/stub.cmd
This pull request just applies the same change as #464 to the test scripts.
=> Use full path for Windows find command in test

.travis.yml, appveyor.yml, test/end-to-end/ant/base/worker/build-worker.xml
This pull request updates Ant version used for testing. As a result, this reverts #608.
* b8167de65225b0fd959facd5c01e4ddf8dd2782a updates Ant version from 1.9 to 1.10.
* 1.9 is kept in the test matrix for oXygen.
* The latest Ant release is 1.10.7 as of now, but 1.10.5 is the latest available on Chocolatey.
* This change reveals an Ant 1.10 regression [bug](https://bz.apache.org/bugzilla/show_bug.cgi?id=62330) which is triggered by #608. ([AppVeyor](https://ci.appveyor.com/project/AirQuick/xspec/builds/27433506/job/jlstgdhnkwjnlt7t#L894))
* 4b1656496106928ebc2001408066250e212ff915 reverts #608.
* ff7a3c62207d990dc902acadcacb395b4f4e5985 adds a comment about the Ant bug.
=> Test with Ant 1.10 and revert #608

test/ant/worker/generate.xsl, test/xspec-638.xsl, test/xspec-638.xspec
Whatever the root cause of #638 is, there should be a test case for `xsl:output` collision:
https://github.com/xspec/xspec/blob/47f1d47506a801dea2dfe8e836346c172fa35b09/src/compiler/generate-xspec-tests.xsl#L84-L86
This pull request adds a simple test which reproduces #638 on Saxon 9.9.
* 43a414cef740bed01d9dbd94f93492c9eb368a56 is the test. It fails on Saxon 9.9: [Azure](https://xspec.visualstudio.com/xspec/_build/results?buildId=152), [AppVeyor](https://ci.appveyor.com/project/xspec/xspec/builds/27583003), [Travis](https://travis-ci.org/xspec/xspec/builds/588162867)
* 38f74fb1402b66dbc5f2ed95e7675cc3bc2fdcea skips the test on Saxon 9.9 assuming its next maintenance release will fix the problem.
=> Test for issue 638 (xsl:output in the stylesheet being tested)

test/win-bats/collection.xml, test/win-bats/stub.cmd, test/xspec.bats
This pull request adds a test for #633.
31a4f2029ce7358064d693f89f64ad7422e1e09b is the test.
cde7e67eec92d49099c768af0d47c16b7aecfd17 is a temporary commit for demonstrating test failures by not skipping the tests on Saxon 9.7: [Azure](https://xspec.visualstudio.com/xspec/_build/results?buildId=156), [Travis](https://travis-ci.org/xspec/xspec/builds/588359811)
2c0fb3b387c544e6bf55471ce37e8faca151861a is for readability. 09227ea6f2a04d416d5bb888fa9e271bb2857fa2 just improves precision of a test. They aren't related directly to #633 but they are so trivial that I included them here.
=> Test for issue 633 (warning on Ant)

appveyor.yml, test/ci/install-deps.cmd
This pull request just removes dependency on 7-zip when installing dependencies on Azure Pipelines and AppVeyor.
To realize it, AppVeyor `image` is moved forward to `Visual Studio 2019` (9fa4280a431c5d6c94c3c44ec7ae0178970f5cf1) which is Windows Server 2019 which aligns with our current configuration of [Azure Pipelines](https://github.com/xspec/xspec/blob/e19539062a32ce7424e4a24416498d6dd38a9c0f/test/ci/azure-pipelines_template.yml#L9).
I visually inspected [AppVeyor log](https://ci.appveyor.com/project/xspec/xspec/builds/27628152) and [Azure Pipelines log](https://xspec.visualstudio.com/xspec/_build/results?buildId=171) and verified that XML Calabash and BaseX tests were executed.
=> ci: remove dependency on 7-zip

.travis.yml, test/ci/install-deps.sh
This pull request just pulls `before_script` from `.travis.yml` and puts it into an external shell script. This is supposed to help migrating to another CI or local testing.
This change aligns with what we [did](https://github.com/xspec/xspec/blob/master/test/ci/install-deps.cmd) for Azure Pipelines.
I visually inspected [Travis CI logs](https://travis-ci.org/xspec/xspec/builds/589087112) and verified these:
* `ant -version` output and `# skip` lines conform to the test matrix
* [`script`](https://github.com/xspec/xspec/blob/b38a0c7e61e99fe84ad235d4b80f97c542f4adc9/.travis.yml#L68-L81) is performed to the end
=> ci: externalize test dependency installation in .travis.yml

.travis.yml, test/ci/print-env.cmd, test/ci/print-env.sh
This pull request extends `test/ci/print-env.cmd` to align with the command line in [Wiki](https://github.com/xspec/xspec/wiki/How-to-Run-the-Test-Suite-Locally#windows).
For Linux/MacOS, an equivalent script is created. (`test/ci/print-env.sh`)
Update [Wiki](https://github.com/xspec/xspec/wiki/How-to-Run-the-Test-Suite-Locally) to direct readers to `test/ci/print-env.cmd` (Windows) and `test/ci/print-env.sh` (Linux/MacOS) instead of the current command line snippet.
=> ci: print environment

test/ci/install-deps.cmd, test/end-to-end/ant/base/worker/build-worker.xml
Following #645, this pull request just removes dependency on Chocolatey when installing Ant on Azure Pipelines and AppVeyor.
50beffa86caa9fde00108f8645062ac768336920 is a temporary commit for verifying that the specified version of Ant is installed and takes effect. As expected, the tests failed on Ant 1.10 jobs and succeeded on Ant 1.9 jobs: [Azure](https://xspec.visualstudio.com/xspec/_build/results?buildId=173), [AppVeyor](https://ci.appveyor.com/project/xspec/xspec/builds/27631938)
---
Although `test/ci/choco-install.cmd` is no longer necessary, I didn't remove it, for the sake of any future use.
=> ci: remove dependency on Chocolatey

.travis.yml, appveyor.yml, test/ci/azure-pipelines_template.yml, test/ci/install-deps.cmd, test/ci/install-deps.sh
Just for historical reasons, `SAXON_JAR` and `XML_RESOLVER_JAR` are defined in each CI's YAML.
This pull request moves them to `test/ci/install-deps.*`. This change is supposed to help migrating to another CI or local testing.
Update [Wiki](https://github.com/xspec/xspec/wiki/How-to-Run-the-Test-Suite-Locally) to direct readers to `test/ci/install-deps.*` for instant installation.
=> ci: set Saxon and XML Resolver path in test/ci/install-deps.*

.travis.yml, appveyor.yml, test/ci/azure-pipelines_template.yml
Now that we don't depend on Chocolatey (#646), we can select Ant version more freely. This pull request advances Ant version to the latest.
=> ci: test with Ant 1.10.7

.travis.yml, appveyor.yml, test/ci/azure-pipelines_template.yml
XML Calabash maintains two lines of [releases](https://github.com/ndw/xmlcalabash1/releases). `*-99` for Saxon 9.9. `*-98` for Saxon 9.8. Our CI has been testing only one line.
This pull request adds the 9.8 line to the text matrix.
=> ci: test with XML Calabash 1.1.*-98

src/compiler/generate-query-tests.xsl
This pull request just uses `$this` in the `mode="x:generate-tests"` template in `generate-query-tests.xsl` in order to align with the other lines in the same template.
Virtually no code change.
=> Use $this in x:generate-tests mode template in generate-query-tests.xsl

src/common/xspec-utils.xsl, src/compiler/generate-common-tests.xsl, src/compiler/generate-query-helper.xsl, src/compiler/generate-query-tests.xsl, src/compiler/generate-tests-utils.xsl, src/compiler/generate-xspec-tests.xsl, src/reporter/coverage-report.xsl, src/reporter/format-utils.xsl, src/reporter/format-xspec-report-folding.xsl, src/reporter/format-xspec-report.xsl, src/schematron/schut-to-xspec.xsl, test/ant/worker/generate.xsl, test/end-to-end/ant/base/worker/generate.xsl, test/end-to-end/ant/generate-expected/worker/generate.xsl, test/end-to-end/ant/run-e2e-tests/worker/generate.xsl, test/end-to-end/processor/base/_normalizer.xsl, test/end-to-end/processor/html/_normalizer.xsl, test/win-bats/generate.xsl
This pull request just adds `xsl:context-item` to `xsl:template[@name]` to clarify what context each template expects.
`@use-when` is for compatibility with XSLT 2.0.
There is no automated test for `format-xspec-report-folding.xsl`. So I manually tested this pull request and verified this:
* `ant -lib "saxon9ee.jar" -Dxspec.xml=tutorial\escape-for-regex.xspec -Dxspec.html.reporter.xsl=src\reporter\format-xspec-report-folding.xsl` generates the same `escape-for-regex-result.html` as the current master.
=> Add xsl:context-item to named templates

.travis.yml, appveyor.yml, pom.xml, test/ci/azure-pipelines_windows.yml, test/ci/maven-package.cmd, test/ci/maven-package.sh
This pull request adds `mvn package -P release` to Azure Pipelines (Windows) and Travis CI for making sure `pom.xml` is not broken.
Up until now, only `mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V` was performed (automatically) only on Travis CI.
The added test is skipped
* on AppVeyor where the image does not have Maven
* and on Azure Pipelines (macOS) where its current configuration focuses only on the core tests.
The test fails on JDK 11. ([Azure](https://xspec.visualstudio.com/xspec/_build/results?buildId=241), [Travis](https://travis-ci.org/xspec/xspec/builds/592419298))
281967e78cd35583d746721fb1e84fb6692fee34 fixes it by following https://bugs.openjdk.java.net/browse/JDK-8212233. The source version `1.7` was taken from [the compiler source version]( …
=> ci: test Maven package and fix javadoc compatibility with JDK 11

test/end-to-end/cases/expected/query/xspec-shared-like-junit.xml, test/end-to-end/cases/expected/query/xspec-shared-like-result.html, test/end-to-end/cases/expected/query/xspec-shared-like-result.xml, test/end-to-end/cases/expected/stylesheet/xspec-shared-like-junit.xml, test/end-to-end/cases/expected/stylesheet/xspec-shared-like-result.html, test/end-to-end/cases/expected/stylesheet/xspec-shared-like-result.xml, test/end-to-end/cases/xspec-shared-like.xspec
`test/end-to-end/cases/xspec-shared-like.xspec` has an error where two `x:like` are collocated:
https://github.com/xspec/xspec/blob/7ca0c444d089a1b9190440cf5f8cec9379f78114/test/end-to-end/cases/xspec-shared-like.xspec#L41-L44
After unshared, this `x:scenario` looks like this:
```xml
<x:scenario xslt-version="2"
label="Scenario for testing x:like which references unshared scenarios">
<x:call function="false"/>
<x:expect label="This referenced and explicitly unshared x:expect should fire both at its original x:scenario and x:like"
test="true()"/>
<x:call function="false"/>
<x:expect label="This referenced and implicitly unshared x:expect should fire both at its original x:scenario and x:like"
test="true()"/>
</x:scenario>
```
So one `x:scenario` has two `x:call`, which is not allowed.
This …
=> Fix test/end-to-end/cases/xspec-shared-like.xspec

test/xspec-utils_stylesheet.xspec
While reviewing #640, I thought that incorporating a part of the proposed tests beforehand would help narrowing down the scope of #640.
=> Test inheritance in x:copy-namespaces()

build.xml, test/win-bats/collection.xml, test/xspec.bats
Alternative to #666.  Because of automatic prefixing with `include`, the `<antcall>` caused problem when `include`ing the XSpec build file in another build file:
````
C:\xspec-1.4.0\build.xml:486: The following error occurred while executing this line:
Target "fail" does not exist in the project "...". 
````
=> 'fail' and 'cleanup' in 'depends', not as <antcall>

.travis.yml
Every Travis CI build executes [`mvn install`](https://travis-ci.org/xspec/xspec/jobs/595375401#L451-L1273) which is useless because
* XSpec doesn't actually depend on Maven
* Maven package is tested separately (#664)
This pull request replaces `before_script` with [`install`](https://docs.travis-ci.com/user/job-lifecycle/#customizing-the-installation-phase) so that
* Useless `mvn install` is no longer executed.
* `install-deps.sh` is executed in a more suitable phase.
=> ci: replace .travis.yml before_script with install

.travis.yml, test/run-bats.sh
`.travis.yml` unsets `_JAVA_OPTIONS` in order to make Bats output line numbers predictable. `_JAVA_OPTIONS` affects not only Travis CI but also any other environment. So this pull request unsets the environment variables in `run-bats.sh`.
Windows is not affected in the first place, because it filters out the noise line:
https://github.com/xspec/xspec/blob/4197e367ae7487adac9ab5d952d7e258242706e0/test/win-bats/stub.cmd#L240-L243
=> ci: unset JVM environment variables in run-bats.sh

src/reporter/coverage-report.xsl
Fixes #682 
* I visually inspected the coverage report HTML on Windows and Linux with Saxon-EE 9.9.1.5 and verified the fix
* I manually ran the tests with Saxon-EE 9.9.1.5 on Windows and Linux
=> Fix issue 682 (Module URIs in coverage report HTML are not formatted)

test/ci/install-deps.cmd, test/ci/install-deps.sh
Travis CI fails to download Ant occasionally. When it happens, the preinstalled Ant still works and confuses the test result.
This pull request invalidates the preinstalled Ant when the download fails.
* 85e0c596e884d18077e60507fb44866ea8d6925b demonstrates a download failure. [Travis CI](https://travis-ci.org/xspec/xspec/jobs/599537102#L470-L471) picks up the preinstalled Ant 1.9.3. Only a few tests failed (possibly because of [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=552032)?)
* b842167e5dc633eccc48302c0b5392677f4f7c88 invalidates the preinstalled Ant. [This time](https://travis-ci.org/xspec/xspec/jobs/599544015#L470-L471), the preinstalled Ant is not used and many tests failed to launch Ant.
* 9dec0a86790e400613f7a7079009072ad0561f1f reverts the deliberate failure.
=> ci: invalidate preinstalled Ant

src/common/xspec-utils.xsl, src/reporter/coverage-report.xsl, src/reporter/format-utils.xsl, src/reporter/format-xspec-report.xsl, test/xspec-utils_stylesheet.xspec
Fixes #681 
* fb480a766e3f432d5c772c16afbdc21dc747d566 pulls `test:format-URI()` out from `format-utils.xsl` and puts it into `xspec-utils.xsl` in order to make the function testable.
* 927aa856d5e0cfa9d5806e781e2f41d79d0f6e66 renames the function to `x:format-uri` to align with the other names
* 7eea9c0b083bc532b0bded148d3155c4cb16c6c8 tests the function
* 3476374b73fcfea9520ed15777faa1a7a096c395 fixes the bug
* I visually inspected the test result report HTML and the coverage report HTML on Windows and Linux with Saxon-EE 9.9.1.5 and verified the fix
* I manually ran the tests with Saxon-EE 9.9.1.5 on Windows and Linux
=> Fix issue 681 (Leading slash missing from formatted URI in HTML report on *nix)

test/end-to-end/cases/expected/schematron/xspec-693-junit.xml, test/end-to-end/cases/expected/schematron/xspec-693-result.html, test/end-to-end/cases/expected/schematron/xspec-693-result.xml, test/end-to-end/cases/xspec-693.sch, test/end-to-end/cases/xspec-693.xspec, test/end-to-end/processor/xml/_normalizer.xsl
Fixs #693
* 50fe689658683c65a4ad5a7baf282ce73f6b2c0c adds an end-to-end test which produces `svrl:active-pattern/@document[. = '']`. This test terminates the entire end-to-end test. ([Travis](https://travis-ci.org/xspec/xspec/jobs/604067884#L1554))
* db4aee76bd0c028d6555ab75fbb93d23d1c170fe fixes the report XML normalizer to ignore the zero-length attribute.
=> Fix issue 693 (end-to-end test cannot handle svrl:active-pattern/attribute(document) if it's zero-length)

src/compiler/generate-common-tests.xsl, test/like/loop.xspec, test/like/multiple.xspec, test/like/none.xspec, test/win-bats/collection.xml, test/xspec.bats
This pull request generates explicit errors when one of the errors happens in resolving `x:like`:
* `x:like` cannot find a scenario: [`none.xspec`](https://github.com/AirQuick/xspec/blob/19aba7d23213d789609d70fab2a42a8685471b29/test/like/none.xspec)
* `x:like` pulls multiple scenarios: [`multiple.xspec`](https://github.com/AirQuick/xspec/blob/19aba7d23213d789609d70fab2a42a8685471b29/test/like/multiple.xspec)
* `x:like` falls into an infinite loop: [`loop.xspc`](https://github.com/AirQuick/xspec/blob/19aba7d23213d789609d70fab2a42a8685471b29/test/like/loop.xspec)
71f591faf42206e7fec9568ef993cab5c971b6c2 tests the implementation on XSLT.
Since the errors are detected in `generate-common-tests.xsl` and common to XSLT/XQuery/Schematron, I didn't write tests specifically for XQuery and …
=> Detect x:like errors

src/reporter/format-utils.xsl, test/end-to-end/cases/expected/query/xspec-467-result.html, test/end-to-end/cases/expected/query/xspec-serialize-junit.xml, test/end-to-end/cases/expected/query/xspec-serialize-result.html, test/end-to-end/cases/expected/query/xspec-serialize-result.xml, test/end-to-end/cases/expected/schematron/xspec-693-result.html, test/end-to-end/cases/expected/stylesheet/xspec-23_2-result.html, test/end-to-end/cases/expected/stylesheet/xspec-467-result.html, test/end-to-end/cases/expected/stylesheet/xspec-serialize-junit.xml, test/end-to-end/cases/expected/stylesheet/xspec-serialize-result.html, test/end-to-end/cases/expected/stylesheet/xspec-serialize-result.xml, test/end-to-end/cases/xspec-serialize.xspec
Fixes #689 
* e64d351408fd56f602b73c4c1241e3f5b1e953cc reproduces the problem. ([XSLT report HTML](https://htmlpreview.github.io/?https://github.com/xspec/xspec/blob/e64d351408fd56f602b73c4c1241e3f5b1e953cc/test/end-to-end/cases/expected/stylesheet/xspec-serialize-result.html#ELEM-471))
* f67437fa99fc6c6b36bc3dfeec750a114858db33 fixes it.  ([XSLT report HTML](https://htmlpreview.github.io/?https://github.com/xspec/xspec/blob/f67437fa99fc6c6b36bc3dfeec750a114858db33/test/end-to-end/cases/expected/stylesheet/xspec-serialize-result.html#ELEM-471))
=> Fix issue 689 (Namespace and attribute nodes are serialized with misaligned indentation)

bin/xspec.bat, bin/xspec.sh, build.xml, test/win-bats/collection.xml, test/xspec-catch.xspec, test/xspec.bats
It usually happens that you have files like these
* `myStylesheet.xsl`
* `myStylesheet.xspec`
and run XSpec over `myStylesheet.xspec`.
Then XSpec creates a compiled stylesheet (`xspec/myStylesheet.xsl`) which happens to have the same name as the tested stylesheet.
Having two files of the same name is confusing, particularly when you're diagnosing an error message or debugging XSpec.
This pull request appends `-compiled` to the compiled query/stylesheet file name. In the above example, `xspec/myStylesheet-compiled.xsl`.
=> Append -compiled to compiled query/stylesheet file name

src/compiler/generate-query-utils.xql, src/compiler/generate-tests-utils.xsl, src/reporter/format-xspec-report.xsl, test/end-to-end/cases/expected/query/xspec-report-junit.xml, test/end-to-end/cases/expected/query/xspec-report-result.html, test/end-to-end/cases/expected/query/xspec-report-result.xml, test/end-to-end/cases/expected/query/xspec-three-dots-result.html, test/end-to-end/cases/expected/stylesheet/xspec-report-junit.xml, test/end-to-end/cases/expected/stylesheet/xspec-report-result.html, test/end-to-end/cases/expected/stylesheet/xspec-report-result.xml, test/end-to-end/cases/expected/stylesheet/xspec-three-dots-result.html, test/end-to-end/cases/xspec-report.xspec
Fixes #697
* 313705945a4da1e3816b3d9eab8701f943c588f4 reproduces the problem ([HTML report](https://htmlpreview.github.io/?https://github.com/xspec/xspec/blob/313705945a4da1e3816b3d9eab8701f943c588f4/test/end-to-end/cases/expected/stylesheet/xspec-report-result.html#ELEM-254))
* af2fe06445896cf92e7de851f036cb49b75b860c fixes it ([HTML report](https://htmlpreview.github.io/?https://github.com/xspec/xspec/blob/af2fe06445896cf92e7de851f036cb49b75b860c/test/end-to-end/cases/expected/stylesheet/xspec-report-result.html#ELEM-254))
=> Fix issue 697 (Empty document node is reported without XPath notation)

test/ant/build.xml, test/ant/worker/generate.xsl
`test/ant/worker/generate.xsl` uses `fn:collection()` to collect XSpec files. URI query parameter is hardcoded:
https://github.com/xspec/xspec/blob/66103d760ab9336a92396b6f1872355d3619f997/test/ant/worker/generate.xsl#L57
This pull request parameterizes it.
With this change, you can quickly experiment query parameters such as recursive option:
```
C:\xspec>test\run-xspec-tests-ant.cmd -Dxspecfiles.dir="C:\test" -Dxspecfiles.dir.url.query="select=*.xspec;recurse=yes"
```
This change pertains only to [CI tests](https://github.com/xspec/xspec/wiki/How-to-Run-the-Test-Suite-Locally). Nothing is changed in XSpec itself.
I ran the following commands on the current master and on this pr branch
```
C:\xspec>test\run-xspec-tests-ant.cmd -Dthread.count=1 -logfile "test.log" …
```
=> Ant-based test: Parameterize query for fn:collection()

.travis.yml
When enabled, Travis CI [Build Config Validation](https://blog.travis-ci.com/2019-10-24-build-config-validation) throws these two informational messages:
* `root`: missing `os`, using the default `linux`
* `env`: key `matrix` is an alias for `jobs`, using `jobs`
This pull request just fixes them. No substantial change.
=> ci: fix .travis.yml according to build config validation message

.gitignore
This pull request just adds `/*.xpr` to `.gitignore` to ignore Oxygen XML Editor project files in the repository root.
=> Ignore Oxygen project file

test/run-bats.cmd, test/run-bats.sh, test/win-bats/collection.xml, test/win-bats/stub.cmd, test/xspec.bats
Fixes #583 
The current Bats script creates XSpec output directories here and there inside the repository, and deletes them later. That doesn't scale.
This pull request directs XSpec CLI and Ant to use a common work directory outside the repository.
**Current `master`**
https://github.com/xspec/xspec/blob/5c9015213238be365c5e9b016b5d420230b33c53/test/xspec.bats#L20-L36
**This pull request**
https://github.com/xspec/xspec/blob/f9eac4823bf420b074ac56c392be32b832c5c948/test/xspec.bats#L24-L34
Also
* Some other adjustments are made throughout the Bats script.
* Some test cases are added.
Remove `If you earlier ran tests manually without removing the temporary...` from [Wiki](https://github.com/xspec/xspec/wiki/How-to-Run-the-Test-Suite-Locally#tips).
=> Use Bats work dir by default

test/ant/worker/generate.xsl, test/xspec-xmlns.xspec
To avoid #720, this pull request just excludes `xspec-xmlns.xspec` from testing with Saxon 9.7.
I verified
* the test was skipped on Saxon-EE 9.7 on my local machine
* the test was *not* skipped on Saxon 9.8 and 9.9 on Azure, AppVeyor and Travis CI
=> Skip xspec-xmlns.xspec on Saxon 9.7

test/saxon-custom-options/config.xml, test/saxon-custom-options/test.xspec, test/saxon-custom-options/ws-only-text.xml, test/win-bats/collection.xml, test/xspec.bats
This pull request just adds a Bats test for a use case mentioned in https://github.com/xspec/xspec/issues/691#issuecomment-547137347.
The test enables the Saxon option `RECOGNIZE_­URI_­QUERY_­PARAMETERS` not directly in the `SAXON_CUSTOM_OPTIONS` environment variable but indirectly in `config.xml` Saxon configuration file.
Mention `?strip-space=` in [Wiki](https://github.com/xspec/xspec/wiki/Writing-Scenarios#whitespace-only-text-nodes).
=> Test with href strip-space=yes

src/compiler/generate-tests-helper.xsl, src/schematron/generate-step3-wrapper.xsl
`src/compiler/generate-tests-helper.xsl` is not a standalone stylesheet but a stylesheet *module* which is intended to be included/imported by the other stylesheets.
However, `generate-tests-helper.xsl` cannot be included/imported freely. It contains `xsl:namespace-alias` which affects the other stylesheets.
This pull request removes `xsl:namespace-alias` from `generate-tests-helper.xsl` so that we can reuse its functions more freely.
=> Remove namespace alias from generate-tests-helper.xsl

xspec.framework
This pull request adds **XSpec for _XQuery_ using XProc** transformation scenario to the Oxygen framework.
Aside from their names, the only difference between the existing **XSpec for _XSLT_ using XProc** and this new additional **XSpec for _XQuery_ using XProc** is this field:
```xml
<field name="inputXSLURL">
<String>${framework}/src/harnesses/saxon/saxon-xquery-harness.xproc</String>
</field>
```
That should be enough according to our [Wiki](https://github.com/xspec/xspec/wiki/Running-with-XProc).
On Oxygen 21.1 on Windows and Linux, I verified that the new **XSpec for XQuery using XProc** transformation scenario worked with `tutorial/xquery-tutorial.xspec` and `test/xspec-variable.xspec`.
=> Add Oxygen XQuery XProc transformation scenario

templates/xquery.properties, templates/xquery.xspec
This pull request adds an XQuery template for Oxygen.
With this change and `xspec.framework` enabled, Oyxgen menu - **File** - **New** will look like this:
The past directory structure of this repository suggests that the Oxygen template files should go in `editors/oxygen/templates/`, but that doesn't seem to fit very nicely into `[Oxygen installation]/frameworks/xspec`. Also `xspec.framework` already has this field:
```xml
<field name="templatesLocations">
<String-array>
<String>${frameworkDir}/templates</String>
</String-array>
</field>
```
That's why the files are placed in `templates/`.
=> Add XQuery template for Oxygen

templates/schematron.properties, templates/schematron.xspec
Like #737, this pull request adds an Oxygen template for Schematron XSpec.
Compared to the Oxygen 21.1's built-in template, this template is simplified and a little bit more focused on being a template than being a tutorial.
This template has the same name (**Schematron Unit Test**) as the Oxygen 21.1's built-in template in **New Document**. On Oxygen 21.1, the built-in one is a static template which does not have a custom dialog, so I think this pull request can just replace the built-in one. (On the other hand, the built-in **XSLT Unit Test** has a custom dialog. We can't replace it with a static template.)
If the situation remains unchanged on the next version of Oxygen, I would like SyncRO Soft to take this XSpec framework and remove the built-in one on the next version of Oxygen to …
=> Add Schematron template for Oxygen

editors/oxygen/add-on/description/0-0-1.xhtml, editors/oxygen/add-on/description/latest.xhtml, oxygen-addon.xml
This pull request publishes a snapshot of the development version of XSpec as an Oxygen add-on.
I would like to propose publishing a new development version via this add-on channel whenever a notable change gets merged into `master`.
The initial add-on version is v0.0.2 which installs the snapshot of XSpec b19ccd7e181fddc21bf191ce27d67cefd65bcd1f.
The add-on v0.0.1 exists too, but it's just for upgrade testing.
See an Oxygen [page](https://www.oxygenxml.com/addons.html). Their [video](https://youtu.be/hfV9Ouw22VY?t=90) demonstrates end-user experience.
Just a specific commit version of `master` branch.
No package built. We can take advantage of this repository's queer structure. (Cloning is deploying.)
This pull request just adds an add-on descriptor file …
=> Publish XSpec development version as Oxygen add-on

xspec.framework
Right now, **Run XSpec Test** transformation scenario 
* cannot test XQuery
* cannot test XSLT when XSpec is both for XSLT and Schematron
* [`test/xspec-uri.xspec`](https://github.com/xspec/xspec/blob/master/test/xspec-uri.xspec), for example, though I don't think there are many use cases like it
This pull request includes XQuery in the candidates of `test.type` of **Run XSpec Test** transformation scenario.
<details><summary>Initial comment (abandoned)</summary>
<div>
With this change, **Run XSpec Test** transformation scenario interactively asks which test type (XSLT, XQuery, or Schematron) the user wants to run.
Some users may find this feature annoying, because it's likely that most people write XSpec only for either XSLT or Schematron.
I wanted to make Oxygen run XSpec silently if …
=> Support XQuery in Run XSpec Test transformation scenario

xspec.framework
This pull request adds an Oxygen transformation scenario for Code Coverage.
Running this transformation scenario with XSLT XSpec file generates `[XSpec filename]-coverage.html` in the same directory as the `.xspec` file and opens it in the default Web browser.
We could avoid adding this new transformation scenario and just add the Code Coverage parameters (`xspec.coverage.enabled` (value `false`) and `xspec.coverage.html`) to the existing **Run XSpec Test** transformation scenario. But if we do so, those who want to try Code Coverage have to duplicate the transformation scenario, set `xspec.coverage.enabled` to `true` and update `locationToOpenInBrowserURL` to match `xspec.coverage.html`. That would be tedious, so this pull request provides a transformation scenario dedicated to Code …
=> Add Oxygen transformation scenario for Code Coverage

pom.xml
Based on our [workflow](https://github.com/xspec/xspec/wiki/Release-Workflow), this is the last pull request to be merged into master before the release of XSpec v1.5.0. (unless something goes wrong in deploying the XSpec artifact to Maven Central)
=> release: remove SNAPSHOT from version in pom.xml

editors/oxygen/add-on/description/latest.xhtml, oxygen-addon.xml
This pull request publishes XSpec v1.5.0 final via Oxygen add-on channel as discussed in https://github.com/xspec/xspec/pull/743#issuecomment-559925556
I tested this change on Oxygen 21.1 build 2019120214 using `https://github.com/AirQuick/xspec/raw/oxy-addon_0-0-4/oxygen-addon.xml`
=> release: oxygen add-on v0.0.4

test/ci/install-deps.cmd, test/ci/install-deps.sh
In response to https://links.sonatype.com/central/501-https-required, this pull request replaces `http://central.` with `https://repo1.`.
Just replacing `http:` with `https:` didn't work, because of the host name in the cert.
=> ci: use HTTPS for fetching Maven files

CONTRIBUTING.md, src/harnesses/harness-lib.xpl, test/end-to-end/processor/html/_normalizer.xsl, test/win-bats/collection.xml, test/win-bats/stub.cmd, test/xspec-72.xspec, test/xspec.bats
Fixes #766 
This pull request inserts a step into the common XProc harness so that the XML report is serialized (on memory) with indentation and reloaded before being consumed by the HTML report.
* fbd21af9e4d917df247d9a047d088bcda6647de9 tests the HTML report generated by XProc harness for Saxon. It fails as expected. ([macOS](https://xspec.visualstudio.com/xspec/_build/results?buildId=687&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=61b979ba-27c9-588c-740e-a675d85b471e&l=274), [Windows](https://ci.appveyor.com/project/xspec/xspec/builds/30483824#L459), [Linux](https://travis-ci.org/xspec/xspec/jobs/644300695#L715-L1269))
* c5b3020318bc9983e85980022adfd663b0e78423 fixes the problem
=> fix(xproc): indent results in HTML report

.travis.yml, appveyor.yml, azure-pipelines.yml
This pull request just updates the version of BaseX used for testing.
From now on, I'd like to update the BaseX version more frequently just like the other test dependencies such as Saxon and XML Calabash.
=> ci(deps): bump BaseX from 8.6.4 to 9.3.1

test/ci/run-codespell.cmd, test/ci/run-codespell.sh
Depending on the repository state, *codespell* may find "typo" in `.git` dir:
```console
$ test/ci/run-codespell.sh 
find spelling mistakes in source code
./.git/objects/ba/5426ab526c0cc52e49919213c9b4d645b27b75: ba  ==> by, be
```
This pull request excludes `.git` from *codespell*.
=> ci: skip codespell .git dir

test/ci/run-codespell.cmd, test/ci/run-codespell.sh
The latest *codespell* warns a lot about `thead  ==> thread` disabled in dictionary:
```console
$ pip install --upgrade git+https://github.com/codespell-project/codespell.git
...
Successfully installed codespell-1.17.0.dev0
$ codespell --quiet-level 2 --skip=".git,./src/schematron/iso-schematron"
./src/reporter/format-xspec-report.xsl:223: thead  ==> thread  | disabled due to the html tag
./src/reporter/format-xspec-report.xsl:232: thead  ==> thread  | disabled due to the html tag
./src/reporter/format-xspec-report.xsl:328: thead  ==> thread  | disabled due to the html tag
./src/reporter/format-xspec-report.xsl:338: thead  ==> thread  | disabled due to the html tag
./test/xspec-param-position.xspec:20: poisition  ==> position
...
```
The warnings are too many. To suppress it, this pull …
=> ci: suppress codespell warnings about fixes disabled in dictionary

test/xspec-param-position.xspec
Fixes a typo in a test label.
This typo is not detected by the current version of *codespell* (v1.16.0). It was not in the dictionary until  recently (codespell-project/codespell#1289).
=> test: fix typo 'poisition'

README.md
Mention Schematron in `README.md`, just like Wiki *[Home](https://github.com/xspec/xspec/wiki)* and *[What is XSpec](https://github.com/xspec/xspec/wiki/What-is-XSpec)*.
=> docs: mention Schematron in README.md

.travis.yml, appveyor.yml, azure-pipelines.yml, test/ci/azure-pipelines_windows.yml
This pull request just updates the versions of Saxon, Ant and XML Calabash used for testing in the latest Oxygen environment (22.0 build 2020021016).
=> ci(deps): bump Oxygen lib versions

xspec.framework, xspec.xpr
The Ant scenarios in `xspec.framework` do not work on Oxygen 22:
```console
...
BUILD FAILED
...\xspec\build.xml:366: The following error occurred while executing this line:
...\xspec\build.xml:178: java.lang.NoClassDefFoundError: org/apache/log4j/Logger
```
This pull request fixes it by copying the Ant scenario library configuration from Oxygen 22.0 build 2020021016.
Regarding the backward compatibility, I tested the updated Ant scenarios shortly on 21.1 and 19.0.
=> fix(oxygen): update Ant scenarios to support Oxygen 22.0

editors/oxygen/add-on/description/latest.xhtml, oxygen-addon.xml
Following #780, this pull request publishes the latest `master` via Oxygen add-on channel.
I tested this change on Oxygen 22.0 build 2020021016 using `https://github.com/AirQuick/xspec/raw/oxy-addon_0-0-5/oxygen-addon.xml`
=> build(oxygen): add-on v0.0.5

test/ant/README.md, test/ant/diagram.txt
`test/ant/` is used for testing `test/*.xspec` and also referenced from [Wiki](https://github.com/xspec/xspec/wiki/Running-with-Ant#using-ant-to-run-multiple-xspec-tests). However, I'm afraid it is somewhat blackboxed.
This pull request adds a PlantUML diagram to `README.md` and describes the overview.
=> docs: add PlantUML diagram to test/ant/README.md

test/ant/worker/generate.xsl, test/end-to-end/cases/xspec-report_schema-aware.xspec, test/generate-tests-utils_schema-aware.xspec
This XSLT
```xslt
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet exclude-result-prefixes="#all" version="3.0"
xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output indent="yes" omit-xml-declaration="yes" />
<xsl:template name="xsl:initial-template">
<prod>
<xsl:value-of select="system-property('xsl:product-version')" />
</prod>
<test>
<xsl:value-of select="'Available'" use-when="type-available('xs:ID')" />
</test>
</xsl:template>
</xsl:stylesheet>
```
behaves differently on Saxon-EE 9.7:
```console
C:\test>java -jar saxon9ee.jar -it -xsl:test.xsl
<prod>EE 9.7.0.21</prod>
<test/>
```
```
<prod>EE 9.8.0.1</prod>
<test>Available</test>
```
```
<prod>EE 9.8.0.12</prod>
<test>Available</test>
```
```
<prod>EE 9.8.0.14</prod> …
```
=> test(xslt): skip testing additional type report on Saxon 9.7

src/reporter/format-xspec-report.xsl, test/end-to-end/cases/expected/query/xspec-three-dots-result.html, test/end-to-end/cases/expected/stylesheet/xspec-three-dots-result.html
In preparation for #588, this pull request removes all whitespace at the end of the label when formatting the HTML report.
As demonstrated in `test/end-to-end/cases/expected/`, this change affects only some headings in the HTML report.
We could possibly perform whitespace normalization in another way. But doing that requires the specification of `@label` and `x:label` to be defined in more details. So this pull request just right-trims HTML headings. For further consideration, I left a [TODO](https://github.com/xspec/xspec/commit/48e3b8872e51dc849859b3c6c8f31303676841ca#diff-40221cb332026fb902b3c89c756e4062R373-R374) comment.
=> refactor(report): right-trim labels in HTML report

test/win-bats/collection.xml
There is an [error](https://xspec.visualstudio.com/xspec/_build/results?buildId=806&view=logs&j=166b8c02-95cc-5502-dd2b-44f9c8527e72&t=31cacdea-a5fc-5a98-b796-b9d255e3ef7e&l=321) in a Bats test for Windows:
```console
CASE #42: Ant with minimum properties (Schematron)
The system cannot find the batch label specified - rmdir-if-exists
...
```
This pull request [fixes](https://xspec.visualstudio.com/xspec/_build/results?buildId=808&view=logs&j=166b8c02-95cc-5502-dd2b-44f9c8527e72&t=31cacdea-a5fc-5a98-b796-b9d255e3ef7e&l=320) it.
=> test: fix nonexistent call rmdir-if-exists

src/compiler/generate-query-helper.xsl, src/compiler/generate-tests-helper.xsl
`generate-query-helper.xsl` and `generate-tests-helper.xsl` are formatted differently. That is acceptable if they were standalone. But actually, they implement mostly the same logic, just serving different languages (XQuery and XSLT). Different formatting makes it tedious to compare or copy the code.
This pull request aligns them. No actual code change. Just formatting changes. The diff appears large, just because the original `generate-tests-helper.xsl` did not indent the stylesheet children.
=> style: align generate-query-helper.xsl and generate-tests-helper.xsl

src/reporter/coverage-report.xsl, test/end-to-end/cases/.gitattributes, test/end-to-end/cases/expected/stylesheet/xspec-793-cr-coverage.html, test/end-to-end/cases/expected/stylesheet/xspec-793-cr-junit.xml, test/end-to-end/cases/expected/stylesheet/xspec-793-cr-result.html, test/end-to-end/cases/expected/stylesheet/xspec-793-cr-result.xml, test/end-to-end/cases/expected/stylesheet/xspec-793-crlf-coverage.html, test/end-to-end/cases/expected/stylesheet/xspec-793-crlf-junit.xml, test/end-to-end/cases/expected/stylesheet/xspec-793-crlf-result.html, test/end-to-end/cases/expected/stylesheet/xspec-793-crlf-result.xml, test/end-to-end/cases/expected/stylesheet/xspec-793-lf-coverage.html, test/end-to-end/cases/expected/stylesheet/xspec-793-lf-junit.xml, test/end-to-end/cases/expected/stylesheet/xspec-793-lf-result.html, test/end-to-end/cases/expected/stylesheet/xspec-793-lf-result.xml, test/end-to-end/cases/xspec-793-cr.xsl, test/end-to-end/cases/xspec-793-cr.xspec, test/end-to-end/cases/xspec-793-crlf.xsl, test/end-to-end/cases/xspec-793-crlf.xspec, test/end-to-end/cases/xspec-793-lf.xsl, test/end-to-end/cases/xspec-793-lf.xspec
Fixes #793
Before fixing the issue, CR lines were reported [as one line](https://htmlpreview.github.io/?https://github.com/xspec/xspec/blob/65052b4ddd18e7400178ffe119131817fc079b42/test/end-to-end/cases/expected/stylesheet/xspec-793-cr-coverage.html) and CR LF lines were reported [with `&#xD;`](https://github.com/xspec/xspec/blob/65052b4ddd18e7400178ffe119131817fc079b42/test/end-to-end/cases/expected/stylesheet/xspec-793-crlf-coverage.html), as demonstrated in an intermediate commit.
The test files (`test/end-to-end/cases/xspec-793-*.*`) were created by copying `test/end-to-end/cases/xspec-214.*` and saved with different line endings. See [`test/end-to-end/cases/.gitattributes`](https://github.com/xspec/xspec/blob/bdb517f4c4a9d13933a735f68ca16524c0e1f714/test/end-to-end/cases/.gitattribute …
=> fix(report): fix tokenizing stylesheet CR lines on code coverage

editors/oxygen/add-on/description/latest.xhtml, oxygen-addon.xml
Following #742, this pull request publishes the latest master via Oxygen add-on channel.
#795 is a new feature, but it doesn't help Oxygen users who already have in-app Saxon-PE+ license. That's why I didn't include it in the [changelog](https://github.com/xspec/xspec/pull/800/files#diff-0bbbd2c604be5224d8c4002e3df89307).
I tested this add-on version on Oxygen 22.0 build 2020021016 using `https://github.com/AirQuick/xspec/raw/oxy-addon_0-0-6/oxygen-addon.xml` and verified that
* SQF for XSpec worked
* **XSLT Code Coverage** transformation scenario worked with `test/end-to-end/cases/xspec-793-cr.xspec`
* **Run XSpec Test** transformation scenario worked with XSLT, XQuery and Schematron tutorial files
=> build(oxygen): add-on v0.0.6

test/xspec-avt.xspec, test/xspec-avt_stylesheet.xspec
Following f1dab868210d47b858e10e5aff3a0615dcd1b495, this pull request just adds comments to `test/xspec-avt*.xspec` about their relationship to `test/xspec-utils_stylesheet.xspec`.
=> test: comment in xspec-avt*.xspec about xspec-utils_stylesheet.xspec

src/compiler/generate-common-tests.xsl, src/compiler/generate-query-tests.xsl, src/compiler/generate-xspec-tests.xsl
The template name `x:compile-params` suggests it handles all `x:param`. Actually it handles global `x:param` and global `x:variable`.
This pull request just changes the template name to better reflect its responsibility. Also the term `test suite params` is removed, as it is not used elsewhere.
=> refactor: rename x:compile-params to x:compile-global-params-and-vars

.travis.yml, appveyor.yml, azure-pipelines.yml, test/ant/build.xml, test/ant/worker/config.xml, test/ci/azure-pipelines_windows.yml
This pull request updates the Saxon version used for testing.
9.9.1.7 changed the behavior of `collection()` (probably https://saxonica.plan.io/issues/4382).
In response to it, this pull request modifies `test/ant/build.xml`. This modification has no impact on XSpec itself.
=> ci(deps): bump Saxon from 9.9.1.6 to 9.9.1.7

test/xspec-utils_stylesheet.xspec
This pull request just removes unused stylesheet reference from `xspec-utils_stylesheet.xspec`.
=> test(xslt): remove unused item.xsl from xspec-utils_stylesheet.xspec

src/common/xspec-utils.xsl
This pull request just aligns an indent in `x:decimal-string()` with the other lines in the same file.
=> style: fix indent in x:decimal-string()

src/common/xspec-utils.xsl, src/compiler/generate-common-tests.xsl, src/reporter/format-xspec-report.xsl, test/variable/reserved-eqname.xspec, test/variable/reserved-name.xspec, test/win-bats/collection.xml, test/xspec-eqname.xspec, test/xspec-eqname_stylesheet.xspec, test/xspec-no-prefix_stylesheet.xspec, test/xspec-utils_stylesheet.xspec, test/xspec.bats
https://www.w3.org/TR/xslt-30/#qname (bold by me)
> [Definition: An EQName is a string representing an expanded QName where the string, **after removing leading and trailing whitespace**, is in the form defined by the EQName...
> [Definition: A lexical QName is a string representing an expanded QName where the string, **after removing leading and trailing whitespace**, is within the lexical space of the xs:QName datatype as defined in XML Schema...
XSpec does not perform the bold part. Names with leading or trailing whitespace sometimes work, sometimes crash XSpec. Inconsistent, at least.
This pull request fixes it by trimming names while gathering specs. Tests are incorporated into `test/xspec-eqname*.xspec`.
=> fix: trim names while gathering specs

test/xspec-utils_stylesheet.xspec
This pull request just replaces `xs:QName()` in a test with `QName()` which is more context-independent.
=> test: test x:resolve-URIQualifiedName() without using xs:QName()

src/common/xspec-utils.xsl
This pull request adds a stub function of `x:line-number()` so that without integrating its Java extension function, IDE such as Oxygen does not complain about the missing function and also `coverage-report.xsl` works on IDE.
Besides the automated tests on our CI, I manually ran the tests on Saxon-EE 9.9.1.7, 9.8.0.15, 9.7.0.21.
=> refactor: stub function of x:line-number()

src/common/xspec-utils.xsl, src/compiler/generate-common-tests.xsl, test/xspec-utils_stylesheet.xspec
This pull request adds the second parameter to `x:yes-no-synonym()` so that its caller can provide the default boolean value.
=> refactor: x:yes-no-synonym() with default value

src/schemas/xspec.rnc
When `x:description/@xslt-version` is not set, XSpec processes it as if it were `2.0`.
This pull request reflects it in the schema. In the near future, we'll update it to `3.0`.
I verified that Oxygen 22.0 picked up this default value in **Attributes** pane.
XSpec compiler for XQuery does not assume the default `@xquery-version`. So this pull request doesn't touch it.
=> refactor(schema): xslt-version default value

src/common/xspec-utils.xsl, src/compiler/generate-common-tests.xsl, src/compiler/generate-query-helper.xsl, src/compiler/generate-tests-helper.xsl, test/xspec-utils_stylesheet.xspec
There are multiple places where a lexical QName needs to be resolved without using the default namespace. This pull request sets up a utility function for it.
=> refactor: resolve lexical QName using a util function

test/global-override.xspec, test/global.xsl
This pull request just adds a test which checks to see if `x:param` and `x:variable` override `xsl:param` and `xsl:variable`.
=> test(xslt): overriding global param and variable

bin/xspec.bat, bin/xspec.sh, test/format-xspec-report-messaging.xsl, test/win-bats/collection.xml, test/xspec.bats
In `bin/xspec.*`, the path of `format-xspec-report.xsl` is hardcoded.
This pull request replaces it with an environment variable (`HTML_REPORTER_XSL`), just like Ant `xspec.html.reporter.xsl` property.
=> feat: specify CLI HTML reporter via environment variable

src/compiler/generate-common-tests.xsl, src/schemas/xspec.rnc, test/end-to-end/cases/expected/query/label-element-junit.xml, test/end-to-end/cases/expected/query/label-element-result.html, test/end-to-end/cases/expected/query/label-element-result.xml, test/end-to-end/cases/expected/schematron/label-element-junit.xml, test/end-to-end/cases/expected/schematron/label-element-result.html, test/end-to-end/cases/expected/schematron/label-element-result.xml, test/end-to-end/cases/expected/stylesheet/label-element-junit.xml, test/end-to-end/cases/expected/stylesheet/label-element-result.html, test/end-to-end/cases/expected/stylesheet/label-element-result.xml, test/end-to-end/cases/label-element.xspec, test/xspec-utils_stylesheet.xspec
Fixes #801 
This pull request changes the schema of `x:label` to disallow child elements.
Also,
* `mode="x:gather-specs"` is updated to always preserve whitespace-only text nodes in `x:label`.
* Some tests are added for `x:is-user-content()`, which ensures that `x:label//node()` is not handled in the same way as nodes under `x:param`, `x:context` etc.
=> fix: do not allow element in x:label element

bin/xspec.bat, bin/xspec.sh, test/custom-coverage-report.xsl, test/win-bats/collection.xml, test/xspec.bats
In `bin/xspec.*`, the path of `coverage-report.xsl` is hardcoded.
This pull request replaces it with an environment variable (`COVERAGE_REPORTER_XSL`), just like Ant `xspec.coverage.reporter.xsl` property.
=> feat: specify CLI coverage reporter via environment variable

test/atomic-value-eq.xspec
XSpec compares an actual atomic value and an expect atomic value using `fn:deep-equal()`. So, by design, their test passes even if they are not exactly equal to each other.
This pull request just adds some tests to confirm it.
=> test: atomic values which are not exactly equal to each other

src/common/xspec-utils.xsl, test/xspec-utils_stylesheet.xspec
This pull request adds a utility function for testing QName strictly. Without this, XSpec is a bit too generous (#828).
=> test: compare QNames using util function

azure-pipelines.yml
#832 made Azure Pipelines triggered on PR branches, but it's still not triggered by pushing commits.
This pull request adds a workaround per https://status.dev.azure.com/_event/179641421.
=> ci: specify all trigger branches in azure-pipelines.yml

.travis.yml, appveyor.yml, azure-pipelines.yml
https://raw.githubusercontent.com/BaseXdb/basex/master/CHANGELOG
> VERSION 9.3.2 (March 10, 2020) -----------------------------------------
>  - Minor bug fixes, numerous performance tweaks
=> ci(deps): bump BaseX from 9.3.1 to 9.3.2

src/common/xspec-utils.xsl, test/win-bats/collection.xml, test/xspec-826.xspec, test/xspec.bats
Fixes #826 
This pull request pleases Saxon by not passing the lexical QName directly to `fn:QName()`.
Tested on Saxon-EE 9.9.1.7 (Windows) and 9.9.1.5 (Linux).
=> fix: #826 (SXWN9000 when resolving QName with non-empty prefix)

editors/oxygen/add-on/description/latest.xhtml, oxygen-addon.xml
Following #711, this pull request publishes the latest `master` via Oxygen add-on channel.
I tested this change on Oxygen 22.0 build 2020030607 using `https://github.com/AirQuick/xspec/raw/oxy-addon_0-0-7/oxygen-addon.xml`
=> build(oxygen): add-on v0.0.7

test/xspec-junit.xspec
Indentation in `test/xspec-junit.xspec` is broken. This pull request fixes it. No logical change.
=> style: fix indentation in xspec-junit.xspec

src/common/xspec-utils.xsl, test/xspec-utils_stylesheet.xspec
On Saxon 10.0, `system-property('xsl:product-version')` returns a shorter string such as `EE 10.0` and `HE 10.0`.
https://sourceforge.net/p/saxon/mailman/message/36949659/
> In future we intend to use two-part version numbers rather than four-part:
> the next major release will be 11.0, the next maintenance release 10.1.
Reflecting it, this pull request adapts `x:extract-version()` to two-part version numbers
=> refactor: adapt x:extract-version() to two-part version numbers

test/xspec-junit.xspec
`test/xspec-junit.xspec` expects serialized element strings. Maintaining this fragile method has been a pain. Internal compiler changes or Saxon changes affect it.
This pull request replaces the expectation with `parse-xml()` so that we don't need to care about serialization.
=> test: parse failure element text in xspec-junit.xspec

test/end-to-end/ant/generate-expected/worker/generate.xsl
Saxon 10 has a subtle change in serialization. Generating end-to-end test expected results using Saxon 10 should be blocked until it's resolved.
Tested on Saxon 10 (blocked), 9.9.0.1 (blocked), 9.9.0.2 (allowed) and 9.9.1.7 (allowed) with #844 integrated.
=> test: block generating end-to-end expected results on Saxon 10

bin/xspec.bat, bin/xspec.sh, test/win-bats/collection.xml, test/xspec.bats
`coverage` option has been explicitly deprecated for more than 9 years (since 8829adaf).
This pull request removes it.
=> refactor: remove deprecated coverage option from CLI

src/reporter/test-report.css
Fixes #796 
This pull request takes `font-size` properties from Oxygen CSS attached to https://github.com/xspec/xspec/issues/92#issue-211892720.
Now the smallest font size in the report is 12px which I believe is the smallest common acceptable size in most languages including East Asians.
* [Coverage report](https://htmlpreview.github.io/?https://github.com/xspec/xspec/blob/3344732c30111e6a657aa3a1a872113d3ae06639/test/end-to-end/cases/expected/stylesheet/coverage-tutorial-coverage.html)
* [HTML report](https://htmlpreview.github.io/?https://github.com/xspec/xspec/blob/3344732c30111e6a657aa3a1a872113d3ae06639/test/end-to-end/cases/expected/stylesheet/xspec-serialize-result.html)
* [Coverage report](https://htmlpreview.github.io/?https://github.com/xspec/xspec/blob/003a8a4ad34c8585e9ec62fe0 …
=> fix(report): take font-size from Oxygen CSS

bin/xspec.bat, bin/xspec.sh, test/win-bats/collection.xml, test/xspec.bats
CLI contains some code for very old Saxon versions including Saxon 8.
This pull request removes it.
=> refactor: remove CLI code for stale Saxon versions

test/ant/worker/generate.xsl, test/end-to-end/cases/xspec-serialize.xspec
This pull request skips `test/end-to-end/cases/xspec-serialize.xspec` on Saxon 10.0 because of a Saxon [bug](https://saxonica.plan.io/issues/4483).
I verified that the test was skipped on Saxon 10.0 on my local machine.
=> test: skip xspec-serialize.xspec on Saxon 10.0

src/common/xspec-utils.xsl, src/compiler/generate-common-tests.xsl, test/ant/worker/generate.xsl, test/end-to-end/ant/generate-expected/worker/generate.xsl, test/xspec-utils_stylesheet.xspec
Saxon 10 changed the version number scheme. Reflecting it, this pull request makes x.y.z part optional in `x:pack-version()`.
=> refactor: make x.y.z part optional in x:pack-version()

.github/workflows/lint.yml, test/README, test/ci/run-codespell.sh
This pull request just adds a static code analysis workflow (only *codespell* at the moment) to GitHub Actions.
be26e85fca0a41a79da9df5dae052ec026b72c5b is a temporary commit to test misspelling.
=> ci: run codespell in GitHub Actions

test/global-override.xspec, test/global.xsl
This pull request just adds a test to `global-override.xspec` for verifying the template context.
=> test: test template context in global-override.xspec

appveyor.yml, test/ci/azure-pipelines_windows.yml, test/ci/compile-java.cmd, test/ci/compile-java.sh, test/ci/maven-package.cmd
This pull request moves some condition checks from `test/ci/azure-pipelines_windows.yml` to `test/ci/*.cmd` for reducing dependency on a specific CI.
=> ci: delegate Azure Pipelines condition to cmd

test/ant/worker/generate.xsl
This pull request skips Code Coverage in [the automated test](https://github.com/xspec/xspec/wiki/How-to-Run-the-Test-Suite-Locally) on Saxon 10 because it doesn't work (#852).
=> test(xslt): skip coverage test on Saxon 10

test/xspec-tested.xsl
This pull request just adds `xsl:mode` to `xspec-tested.xsl` so that it can be easily included in XSLT pacakges.
=> test: add xsl:mode to xspec-tested.xsl

.travis.yml, appveyor.yml, azure-pipelines.yml, src/common/xspec-utils.xsl, test/ci/azure-pipelines_windows.yml, test/xspec-utils_stylesheet.xspec
This pull request adds Saxon 10.0 to Azure Pipelines (Windows) and Travis CI (Linux).
AppVeyor (Windows) and macOS (Azure Pipelines) remain 9.9, because 10 is not considered as mainstream.
Add 10 to [Wiki](https://github.com/xspec/xspec/wiki/Requirements#saxon).
=> ci: add Saxon 10.0 to CI matrix

test/ant/build.xml, test/ant/worker/generate.xsl, test/caps/hof.xquery, test/caps/hof.xsl, test/end-to-end/cases/expected/query/xspec-355-junit.xml, test/end-to-end/cases/expected/query/xspec-355-result.html, test/end-to-end/cases/expected/query/xspec-355-result.xml, test/end-to-end/cases/expected/stylesheet/xspec-355-junit.xml, test/end-to-end/cases/expected/stylesheet/xspec-355-result.html, test/end-to-end/cases/expected/stylesheet/xspec-355-result.xml, test/end-to-end/cases/xspec-355.xspec, test/end-to-end/cases/xspec-report.xspec
Now that higher-order functions are available on Saxon-HE, this pull request enables [the automated test](https://github.com/xspec/xspec/wiki/How-to-Run-the-Test-Suite-Locally) to handle XSpec files containing HOF.
=> test: test with higher-order functions if possible

.github/workflows/lint.yml, .travis.yml, appveyor.yml, test/README, test/ci/azure-pipelines_windows.yml, test/ci/run-codespell.cmd, test/ci/run-codespell.sh
Following #864, this pull request removes *codespell* from AppVeyor, Azure Pipelines and Travis CI.
By this change, we lose redundancy of the spellcheck test, which I think is ok, because it isn't a critical part of CI.
`test/ci/run-codespell.cmd` is no longer necessary, but this pull request doesn't delete it, because it can be used in *git* pre-commit hook or possible future migration to another CI.
e17c6e16d0fc1bc5a68dd72028e1e9c07e177b22 is a temporary commit to verify this change.
* Add *codespell* GitHub Actions workflow to the `master` branch protection rule
=> ci: run codespell only in GitHub Actions

src/common/xspec-utils.xsl, src/compiler/generate-tests-utils.xsl, test/end-to-end/cases/expected/query/xspec-355-junit.xml, test/end-to-end/cases/expected/query/xspec-355-result.html, test/end-to-end/cases/expected/query/xspec-355-result.xml, test/end-to-end/cases/expected/stylesheet/xspec-355-junit.xml, test/end-to-end/cases/expected/stylesheet/xspec-355-result.html, test/end-to-end/cases/expected/stylesheet/xspec-355-result.xml, test/end-to-end/cases/expected/stylesheet/xspec-report-result.html, test/end-to-end/cases/expected/stylesheet/xspec-report-result.xml, test/end-to-end/cases/xspec-355.xspec, test/xspec-utils_stylesheet.xspec, test/xspec-utils_stylesheet_hof.xspec
Now that `function(*)` is available on Saxon-HE, this pull request enables `test:report-sequence` to handle it in a bit more details.
Current `master`:
* [XSLT](https://htmlpreview.github.io/?https://github.com/xspec/xspec/blob/b75f426f0a35010927194c0b08c15294782208eb/test/end-to-end/cases/expected/stylesheet/xspec-355-result.html)
* [XQuery](https://htmlpreview.github.io/?https://github.com/xspec/xspec/blob/b75f426f0a35010927194c0b08c15294782208eb/test/end-to-end/cases/expected/query/xspec-355-result.html)
After this change:
* [XSLT](https://htmlpreview.github.io/?https://github.com/xspec/xspec/blob/e2555099ab084dc3fc96a9bcc82a1ec95bae29e1/test/end-to-end/cases/expected/stylesheet/xspec-355-result.html)
* [XQuery](https://htmlpreview.github.io/?https://github.com/xspec/xspec/blob/e2555099 …
=> feat(report): report non-array non-map function(*)

test/mirror.xsl, test/multiple-context-items.xspec, test/multiple-context-nodes.xspec, test/multiple-context-values.xspec
This branch is not tested with multiple items stored in the variable of `${test:variable-name($context)}`:
https://github.com/xspec/xspec/blob/7e673316b510b3bd5315be3fe63e7331c3df227a/src/compiler/generate-xspec-tests.xsl#L325-L330
This pull request adds some tests for it.
=> test(xslt): multiple context items

src/compiler/generate-common-tests.xsl, test/import/file-not-found.xspec, test/import/no-href.xspec, test/schema/build.xml, test/win-bats/collection.xml, test/xspec.bats
XSpec does not error out when `x:import/@href` is unreachable or the attribute does not exist.
This pull request fixes it.
=> fix: detect broken x:import

test/global-override.xspec, test/global.xsl
This pull request adds a test for *apply-templates* invocation to the template context test in `global-override.xspec`.
The template context and the global context item are somewhat entangled in `fn:transform()`. That's why the template context inspection is added to `global-override.xspec`.
=> test(xslt): add apply-templates invocation to template context test

test/win-bats/collection.xml, test/xspec.bats
Some Bats tests unset `TEST_DIR` (CLI) or `xspec.dir` (Ant), or set relative `TEST_DIR`. They pollute `tutorial/` and `test/` directories.
This pull request copies `tutorial/` to the work directory and runs the tests there so that they do not pollute the repository directories.
=> test: do not pollute repository dir in Bats test

test/schematron/schematron-xslt-compile.xsl, test/schematron/schematron-xslt-expand.xsl, test/schematron/schematron-xslt-include.xsl, test/schematron/schematron-xslt.sch, test/schematron/schematron-xslt.xspec, test/win-bats/collection.xml, test/xspec.bats
While the tests for `SCHEMATRON_XSLT_*` (CLI) and `xspec.schematron.preprocessor.step?` (Ant) ensures that the specified XSLT files are invoked in order, they do not ensure that the transformation results are chained in order. This pr ensures it.
=> test(schematron): test external XSLT file chain

test/ant/worker/build-worker_util.xml, test/ant/worker/generate.xsl, test/end-to-end/cases/expected/stylesheet/format-xspec-report-folding-junit.xml, test/end-to-end/cases/expected/stylesheet/format-xspec-report-folding-result.html, test/end-to-end/cases/expected/stylesheet/format-xspec-report-folding-result.xml, test/end-to-end/cases/format-xspec-report-folding.xspec, test/end-to-end/processor/html/_deserializer.xsl, test/end-to-end/processor/html/_normalizer.xsl, test/win-bats/collection.xml, test/xspec.bats
`src/reporter/format-xspec-report-folding.xsl` is not tested at all.
This pull request tests it in the end-to-end test. ([Live expected result](https://htmlpreview.github.io/?https://github.com/xspec/xspec/blob/ccc36c276fb8d1ae72d518d97b49d0b9feedd17b/test/end-to-end/cases/expected/stylesheet/format-xspec-report-folding-result.html))
=> test: test format-xspec-report-folding.xsl in end-to-end test

.github/CODEOWNERS
I thought it would be nice to set @cmarchand in [`CODEOWNERS`](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) as the owner of `/pom.xml`.
Based on its [commit history](https://github.com/xspec/xspec/commits/master/pom.xml), the primary responsibility of the owner would be reviewing and approving these changes in `pom.xml`:
* Update of dependencies submitted by *dependabot*
* Manipulation of the version number regarding the releases
* And, of course, any significant changes
@cmarchand 
Is this fine with you?
=> ci: set cmarchand as pom.xml owner in CODEOWNERS

CONTRIBUTING.md, pom.xml
Following our [workflow](https://github.com/xspec/xspec/wiki/Release-Workflow#updating-pomxml), this pull request increases the version of the XSpec release and adds the snapshot suffix. 
As usual, this should be the first pull request to be merged into `master` in order to start the development of XSpec v2.0.0.
Considering this kind of commits, this pull request adds `maven` to the commit scope list in `CONTRIBUTING.md`.
=> build(maven): bump pom.xml to 2.0.0-SNAPSHOT

editors/oxygen/add-on/description/latest.xhtml, oxygen-addon.xml
Following our [workflow](https://github.com/xspec/xspec/wiki/Release-Workflow#updating-oxygen-add-on), this pull request publishes XSpec v1.6.0 final via Oxygen add-on channel. 
As usual, this should be the 2nd pull request to be merged into `master` in order to start the development of XSpec v2.0.0. (The 1st one should be #902.)
I will test this change on Oxygen 22.1 build 2020030607 using `https://github.com/AirQuick/xspec/raw/oxy-addon_0-0-9/oxygen-addon.xml`
=> build(oxygen): add-on v0.0.9

.github/workflows/test.yml, .travis.yml, test/ci/azure-pipelines_windows.yml, test/ci/env/saxon-9-7.env
This pull request removes Saxon 9.7 from the CI test matrix and retreats Saxon 9.8 to the lowest priority.
Update [Wiki](https://github.com/xspec/xspec/wiki/Requirements#saxon)
=> ci: remove Saxon 9.7

CONTRIBUTING.md
This pull request retires Commit Lint from `CONTRIBUTING.md` in favor of Semantic Pull Requests.
=> docs: replace Commit Lint with Semantic Pull Requests in CONTRIBUTING.md

CONTRIBUTING.md
* Trivial fixes
* Do not list every non GitHub CI system, because we sometimes switch CI systems depending on their performance/stability.
=> docs: fix CONTRIBUTING.md details

.travis.yml
This pull request stops specifying an old version of Ubuntu in `.travis.yml`
=> ci: remove dist from .travis.yml

src/compiler/generate-query-tests.xsl, src/compiler/generate-xspec-tests.xsl, tutorial/under-the-hood/Compilation.md, tutorial/under-the-hood/compilation-simple-suite.xquery, tutorial/under-the-hood/compilation-simple-suite.xsl, tutorial/under-the-hood/compilation-simple-suite.xspec, tutorial/under-the-hood/compilation-sut.xquery, tutorial/under-the-hood/compilation-sut.xsl, tutorial/under-the-hood/compilation-sut_query.xspec, tutorial/under-the-hood/compilation-sut_stylesheet.xspec
As mentioned in #797 and #505, the Compilation wiki needed some updates. This pull request has these pieces:
- (738ffeb) Update sample code in Compilation wiki.
- (82b7eaa) Commit some code files that represent the sample code in the wiki. These files should make future updates easier.
- (4e52abf) Modify compiler so high-level comments in the Compilation wiki's sample code actually appear in the compiled stylesheet and query files.
Regarding the last piece: I didn't try to be comprehensive, because automating the wiki updates too much could be counterproductive. It's useful for a person to look over the code, decide where to replace code with "..." for clarity in the example, and make sure the comments are still accurate as the compiler evolves.
=> docs: update "Compilation" doc

test/ant/worker/generate.xsl, test/end-to-end/ant/base/worker/generate.xsl, test/end-to-end/processor/base/_normalizer.xsl, test/end-to-end/processor/base/compare.xsl, test/override-id/generate-xspec-tests.xsl
This pull request just simplifies some expressions in `test/**/*.xsl`.
=> test: refactor expressions in test/**/*.xsl with XPath 3

src/compiler/generate-common-tests.xsl
Just cleans up some expressions in `src/compiler/generate-common-tests.xsl`. Its logic is not modified.
=> refactor: details in generate-common-tests.xsl

src/compiler/generate-query-utils.xql
Just removes verbose `fn` prefix from `src/compiler/generate-query-utils.xql`.
=> refactor(xquery): remove verbose fn prefix from generate-query-utils.xql

src/compiler/generate-query-utils.xql, src/compiler/generate-tests-utils.xsl
deep-equal functions in `src/compiler/generate-*-utils.*` are a bit complicated.
To simplify them, this pull request extracts two functions from `generate-tests-utils.xsl`.
`generate-query-utils.xql` will be refactored in another PR.
=> refactor(xslt): extract deep-equal utils

src/reporter/coverage-report.xsl
`src/reporter/coverage-report.xsl` lacks `@as` here and there. This pull request adds it.
=> refactor(xslt): add attribute(as) to coverage-report.xsl

test/ci/env/global.env
https://raw.githubusercontent.com/BaseXdb/basex/master/CHANGELOG
> VERSION 9.3.3 (May 15, 2020) -------------------------------------------
> 
>  - Minor bug fixes, performance tweaks, new query optimizations
=> ci(deps): bump BaseX from 9.3.2 to 9.3.3

.commitlintrc.json, .dependabot/config.yml, CONTRIBUTING.md
**dependabot** detects development dependencies and sets `deps-dev` scope which is not configurable. This pull request reflects it in `commitlint` config.
Also fixes the prefix for JavaScript and Python. They aren't used for build and release.
=> docs: adjust dependabot config

.github/workflows/lint.yml, requirements-dev.txt
`codespell` 1.17.0 package published for Python 2 is broken. (Dictionary files are missing.)
This pull request sets up Python 3 before running `codespell`.
=> ci(deps-dev): run codespell 1.17.0 on Python 3.x

pom.xml
Related to #938 
This pull request sets [`targetPath`](https://github.com/apache/maven/blob/d657c9c6b467db60c932799485fb4210c0bd1fe0/maven-model/src/main/mdo/maven.mdo#L1780-L1795) so that the "resources" (some selected files from the XSpec repository) are stored under `io/xspec/xspec/impl/[original directory]`.
Keeping the (relative) original directory structure of the repository is important, because a file may reference another file ([example](https://github.com/xspec/xspec/blob/5836b905b23a07451e20966a7c3916056fda608d/src/schematron/generate-step3-wrapper.xsl#L34)). That's why
- the `targetPath` ends with `[original directory]`.
- [the built-in Schematron _skeleton_ implementation](https://github.com/xspec/xspec/tree/master/src/schematron/iso-schematron) is kept as is.
=> build(maven): put resources under unique root

build.xml, src/ant/generate-catalog.xsl, test/win-bats/collection.xml, test/xspec.bats, xspec.framework
Closes #898 
Following #913, this pull request enables CLI and Ant to use multiple catalog file URI including multiple URIs.
* New Ant property `catalog.is.uri`
* Default `false` in `build.xml`.
* Default `true` in `xspec.framework`.
* Will not be documented in Wiki for the time being.
* `catalog` Ant property can be either file path (if `catalog.is.uri` is `false`) or URI (if `catalog.is.uri` is `true`). Must not mix file path and URI.
* Regardless of `catalog.is.uri`, relative paths in `catalog` are resolved with Ant `basedir` property.
* Default `catalog` property in `xspec.framework` is now `${xmlCatalogFilesList}`.
* On Oxygen 22.1 build 2020051804, `${xmlCatalogFilesList}` has many items even when **Use default catalog** is _not_ checked and **Catalogs** list is empty in …
=> feat: catalog file URIs

tutorial/schematron/demo-02.sch
Just fixes a warning in `tutorial/schematron/demo-02.sch`:
```console
C:\xspec>bin\xspec.bat -s tutorial\schematron\demo-02-PhaseA.xspec
Saxon script not found, invoking JVM directly instead.
Creating XSpec Directory at C:\xspec\tutorial\schematron\xspec...
Setting up Schematron preprocessors...
Converting Schematron into XSLT...
Converting Schematron XSpec into XSLT XSpec...
Creating Test Stylesheet...
Running Tests...
Warning at function local:add on line 31 of demo-02-PhaseA-sch-preprocessed.xsl:
SXWN9000: A function that computes atomic values should use xsl:sequence rather than xsl:value-of
Testing with SAXON EE 9.9.1.7
Pattern 1
assert t1-1 warn
not assert t2-1
Pattern 3 - Shared
assert t3-1
Pattern 4 - example of a second level of imported scenarios
report t4-1 warn
Formatting …
```
=> docs(schematron): replace xsl:value-of with xsl:sequence in demo-02.sch

editors/oxygen/add-on/description/latest.xhtml, oxygen-addon.xml, xspec.xpr
Closes #940
* Version is `2.0.0` based on #940
* Oxygen 19 (bundled with Saxon 9.7) is dropped
* I tweaked **Document Type Association** preferences in `xspec.xpr` so that the add-on gets disabled while `xspec.xpr` is active.
I tested this change on Oxygen 22.1 (build 2020051804) and 20.0 (build 2018042410) using `https://github.com/AirQuick/xspec/raw/oxy-addon_2-0-0/oxygen-addon.xml`
=> build(oxygen): add-on v2.0.0

src/common/xspec-utils.xsl, src/compiler/generate-common-tests.xsl, src/schematron/schut-to-xspec.xsl, test/win-bats/collection.xml, test/win-bats/collection.xsd, test/xspec-987_child.xspec, test/xspec-987_parent.xspec, test/xspec-utils_stylesheet.xspec, test/xspec.bats
Fixes a problem where `x:import` fails to eliminate duplicates.
- 72a24af24260df12378bf517ee236d02a30fca44 reproduces the problem on Saxon 9.9 and 10.1
- 870419cd1db8eb79a6e59e1d411092c2de3765c1 fixes it by comparing actual document URI _in addition to_ node identity
=> fix: fix #987 (circular imports)

src/compiler/generate-query-utils.xql
This pull request just simplifies `test:atom-type()` using `typeswitch`.
The function already has tests in `test/generate-x-utils.xspec` and `generate-query-utils_schema-aware.xspec`.
=> refactor(xquery): typeswitch in test:atom-type()

test/xspec-avt.xspec, test/xspec-avt_schematron.xspec, test/xspec-avt_stylesheet.xspec
This pull request just prepends a prefix to functions in the AVT tests, to make sure that namespace prefixes are available in AVT.
=> test: test AVT with namespace prefix

src/common/xspec-utils.xsl, src/compiler/generate-query-tests.xsl, test/xspec-utils_stylesheet.xspec
The compiled XQuery occupies `output` namespace prefix. This pull request frees it by replacing the option declarations with URIQualifiedName.
=> refactor(xquery): do not occupy output namespace

test/ant/worker/generate.xsl, test/xspec-1029.xsl, test/xspec-1029.xspec
Closes #1029 
This test assumes the Saxon bug will be fixed in Saxon 10.2 (only).
=> test(xslt): catch xsl:message in atomic value function/template

src/reporter/format-utils.xsl
This pull request just replaces the deprecated namespace axis with our util function.
=> refactor(report): do not use namespace axis

src/compiler/generate-query-utils.xqm, src/compiler/generate-tests-utils.xsl, src/reporter/coverage-report.xsl, src/reporter/format-utils.xsl
Just removes the second argument from `string-join()` wherever possible.
=> refactor: use the single-argument version of string-join()

src/common/xspec-utils.xsl, src/compiler/generate-common-tests.xsl, src/compiler/generate-tests-helper.xsl, src/compiler/generate-tests-utils.xsl, src/reporter/format-utils.xsl, src/schematron/schut-to-xspec.xsl, test/xspec-453_local.xspec, test/xspec-utils_stylesheet.xspec
Fixes #1031 
`@namespace` was missing from `xsl:element` created by `test:create-node-generator` mode.
This pull request fixes it and also adds `@namespace` to some other instances of `xsl:element` and `xsl:attribute`.
=> fix(xslt): set namespace on node generator

test/ci/build_install-deps.xml
Following BaseXdb/basex#1859, this pull request just replaces `http:` with `https:` for accessing `files.basex.org`.
=> ci(basex): download BaseX using secure channel

test/generate-xspec-tests.xspec
`test/generate-xspec-tests.xspec` has a stale workaround for `$xspec-prefix`. This pull request removes it.
=> test: remove $xspec-prefix workaround from generate-xspec-tests.xspec

src/compiler/generate-query-helper.xsl, src/compiler/generate-query-tests.xsl, src/compiler/generate-tests-helper.xsl, src/compiler/generate-xspec-tests.xsl, test/end-to-end/ant/generate-expected/build.xml, test/under-the-hood_compilation-sut_function.xspec, test/under-the-hood_compilation-sut_template.xspec, tutorial/under-the-hood/Compilation.md, tutorial/under-the-hood/compilation-sut_function.xspec, tutorial/under-the-hood/compilation-sut_template.xspec, tutorial/under-the-hood/compilation-variables-scope.xspec
The XQuery compiler has been putting ad hoc indentation into the compiled query, but it is failing miserably. It simply doesn't scale. This pull request gives up all the indentation in the compiled query. Just put line breaks.
This change affects only the compiled query. The report XML file generated by the compiled query is not changed.
If we want to indent the compiled query, I think it should be done by a code formatter. (I have no candidate.)
=> style(xquery): do not indent the compiled query

src/compiler/generate-common-tests.xsl
Just relocates `x:xspec-prefix()` within the `generate-common-tests.xsl` file. For historical reasons, it was located unfittingly near the file head.
=> refactor: relocate x:xspec-prefix()

test/generate-query-utils.xspec, test/generate-query-utils_schema-aware.xspec, test/generate-x-utils.xspec
Following #982 and #1041, this pull request uses the `test` prefix in some tests for convenience.
=> test: use xmlns:test in tests

src/compiler/generate-common-tests.xsl, src/compiler/generate-query-tests.xsl, src/compiler/generate-xspec-tests.xsl, test/end-to-end/cases/expected/query/ambiguous-expect-result.xml, test/end-to-end/cases/expected/query/issue-448-result.xml, test/end-to-end/cases/expected/query/issue-450-451-result.xml, test/end-to-end/cases/expected/query/report-result.xml, test/end-to-end/cases/expected/query/report_schema-aware-result.xml, test/end-to-end/cases/expected/query/serialize-result.xml, test/end-to-end/cases/expected/query/shared-like-result.xml, test/end-to-end/cases/expected/query/three-dots-result.xml, tutorial/under-the-hood/Compilation.md
Following #1055, this pull request invokes XQuery SUT using URIQualifiedName.
This change inevitably contains a fix for a longstanding internal bug where the XQuery test result XML contains garbage instances of `<x:result>`.
=> refactor(xquery): invoke SUT using URIQualifiedName

src/compiler/generate-common-tests.xsl, src/compiler/generate-query-helper.xsl, src/compiler/generate-query-tests.xsl, src/compiler/generate-tests-helper.xsl, src/compiler/generate-xspec-tests.xsl, test/end-to-end/cases/expected/query/issue-467-result.xml, test/end-to-end/cases/expected/query/serialize-result.xml, test/end-to-end/cases/expected/stylesheet/issue-467-result.xml, test/end-to-end/cases/expected/stylesheet/serialize-result.xml, tutorial/under-the-hood/Compilation.md
Following #1064, this pull request makes `mode="test:create-node-generator"` create indirect node generators instead of direct ones.
=> refactor: indirect node generator

test/ci/env/global.env
There seems to be no breaking changes in https://raw.githubusercontent.com/BaseXdb/basex/master/CHANGELOG
=> ci(deps): bump BaseX from 9.3.3 to 9.4

src/compiler/generate-common-tests.xsl, src/compiler/generate-query-tests.xsl, src/compiler/generate-xspec-tests.xsl, test/output-scenario-error/xquery_context.xspec, test/output-scenario-error/xquery_no-call.xspec, test/output-scenario-error/xquery_template-call.xspec, test/win-bats/collection.xml, test/xspec.bats
`x:output-scenario` templates in XSLT compiler and XQuery compiler output errors in different ways. This pull request does it in a single template `x:output-scenario-error`.
As a result, `x:XSPEC003`, `x:XSPEC004` and `x:XSPEC005` are removed. I believe the removal is fine because
- The facility for those XSpec error codes has never been established.
- The error codes have brought virtually no benefits, while their ad hoc usage just complicates the implementation and the tests.
If we want to reinstate those error codes, I think it should be done _after_ establishing the facility. For example, DITA-OT does it in a [template](https://github.com/dita-ot/dita-ot/blob/master/src/main/plugins/org.dita.base/xsl/common/output-message.xsl) and a …
=> refactor: error template for x:output-scenario templates

src/compiler/generate-query-tests.xsl, src/compiler/generate-xspec-tests.xsl, test/end-to-end/cases/expected/schematron/schematron-import_demo-02-PhaseB-result.xml, test/end-to-end/cases/expected/stylesheet/format-xspec-report-folding-result.xml, test/end-to-end/cases/expected/stylesheet/xslt2-result.xml, test/generate-xspec-tests.xspec, tutorial/under-the-hood/Compilation.md
Following #1064, this pull request replaces `x:scenario` literal result elements with its indirect constructor.
=> refactor(report): create x:scenario indirectly

src/common/xspec-utils.xqm, src/compiler/generate-query-utils.xqm, src/compiler/generate-tests-utils.xsl, test/generate-x-utils.xspec, test/xspec-utils.xspec, test/xspec-utils_stylesheet.xspec
The literal XSpec namespace URI is still used in some places. This pull request replaces it with the `$x:xspec-namespace` variable.
=> refactor: do not use XSpec namespace URI directly

.github/workflows/maven-deploy.yml
actions/setup-java#63 has been reviewed and merged.
This pull request replaces `samuelmeuli/action-maven-publish` with it, preferring the standard GitHub Action.
=> ci(maven): replace action-maven-publish with actions/setup-java

src/compiler/generate-query-helper.xsl, src/compiler/generate-tests-helper.xsl, tutorial/under-the-hood/Compilation.md
Removes a temporary URI variable (`$...-uri`) from variable declarations. Now, URI is escaped and inserted directly in the `doc()` expression.
=> refactor: remove temp URI var from var decl

src/schematron/generate-step3-wrapper.xsl, test/generate-step3-wrapper_custom.xspec, test/generate-step3-wrapper_default.xspec
`src/schematron/generate-step3-wrapper.xsl` creates `$x:schematron-uri` as `xsl:variable`. It should be `xsl:param`, although there is virtually no difference. This pull request fixes it and adds some tests for preventing similar issues.
=> fix(schematron): generate $x:schematron-uri as xsl:param

src/compiler/generate-common-tests.xsl, src/compiler/generate-query-tests.xsl, src/compiler/generate-xspec-tests.xsl, test/generate-xspec-tests.xspec, test/generate-xspec-tests/expect.xspec, test/generate-xspec-tests/scenario.xspec, test/schema/build.xml
Assign `(x:scenario | x:expect)/@id` at an earlier stage (immediately after unsharing scenarios) so that the assigned `@id` can be used in other ways.
=> refactor: assign x:scenario x:expect ID right after unsharing scenarios

src/compiler/generate-common-tests.xsl, src/compiler/generate-query-tests.xsl, src/compiler/generate-xspec-tests.xsl, test/win-bats/collection.xml, test/xspec.bats
Lexical QName is dangerous and should be used with constraint. This pull request adds comments to clarify why lexical QName generated by `x:xspec-name()` is used in some places.
=> docs: comment why lexical QName from x:xspec-name() is used

src/compiler/generate-xspec-tests.xsl, test/generate-xspec-tests.xspec, tutorial/under-the-hood/Compilation.md
Just outputs `xsl:context-item` into the generated templates to clarify their required context.
=> refactor(xslt): xsl:context-item in generated named templates

src/compiler/generate-xspec-tests.xsl, tutorial/under-the-hood/Compilation.md
Namespaces should be handled at each exact point where they are required, because each `//x:*` requires a different set of namespaces. Copying namespaces to every scenario `xsl:template` in the compiled stylesheet should be considered as harmful. This pull request removes it.
=> refactor(xslt): do not copy namespaces to scenario templates

src/schemas/xspec.rnc
Just fixes a typo in a schema annotation.
=> docs(schema): fix a typo 'paraemeters'

test/eqname.xspec, test/variable.xspec
This minor test refactoring aims to keep similar things together. Fixes issue #927.
=> test: relocate test for redefining variable while mixing notations

test/.gitignore, test/run-bats.cmd, test/win-bats/collection.xml, test/win-bats/generate.xsl, test/win-bats/stub.cmd
This pull request adds `--filter` option to `test/run-bats.cmd`. It works like the same Bats option introduced in its [1.2.0](https://github.com/bats-core/bats-core/releases/tag/v1.2.0).
e2f579f37ab6134b19d3ae63ddac5727ad1e5ea6 is a deliberate failure to verify that the updated `run-bats.cmd` is still able to catch test failures.
Update [Tips in Wiki](https://github.com/xspec/xspec/wiki/How-to-Run-the-Test-Suite-Locally#tips) with these examples:
__Linux/macOS__
```console
$ test/run-bats.sh --filter "CUSTOM|HOME"
✓ XSPEC_HOME 
✓ XSPEC_HOME is not a directory 
✓ XSPEC_HOME seems to be corrupted 
✓ SAXON_CP has precedence over SAXON_HOME 
✓ invoking xspec using SAXON_HOME finds Saxon jar and XML Catalog Resolver jar 
✓ invoking xspec for XSLT with SAXON_CUSTOM_OPTIONS 
✓ invoking xspec for …
```
=> ci: support filtering Windows Bats-like tests

build.xml, test/override-id/generate-query-tests.xsl, test/win-bats/collection.xml, test/xspec.bats
This pull request allows the Ant user to set an alternative XSpec compiler per language (XQuery or XSLT).
This change will allow [Oxygen XSpec Helper View](https://github.com/xspec/oXygen-XML-editor-xspec-support/blob/7240b9bf2229676c4a8097425a6cf8bd5759ca9e/frameworks/xspec/xspec.framework#L840-L862) to run XQuery XSpec.
This is an advanced internal feature so I don't think the new Ant properties (`xspec.xquery.compiler.xsl` and `xspec.xslt.compiler.xsl`) should be documented.
=> feat: override compiler per language in Ant build

test/ci/build_test-maven-jar.xml
Ensure that all the built-in `.class` files are identified (and deleted) before testing Maven jar.
=> ci(maven): ensure built-in class files are deleted before jar test

src/compiler/generate-xspec-tests.xsl
Just updates a comment to clarify why the cache must be disabled in `@run-as="external"`.
=> docs: update a comment about transform cache=false

build.xml, src/compiler/generate-common-tests.xsl, src/reporter/format-xspec-report-folding.xsl, src/reporter/format-xspec-report.xsl, test/ant/worker/build-worker_util.xml, test/ant/worker/generate.xsl, test/ci/build_install-deps.xml, test/ci/env/README.md, test/ci/print-env.cmd, test/ci/print-env.sh, test/end-to-end/cases/expected/query/force-focus_focus-1-junit.xml, test/end-to-end/cases/expected/query/force-focus_focus-1-result.html, test/end-to-end/cases/expected/query/force-focus_focus-1-result.xml, test/end-to-end/cases/expected/stylesheet/force-focus_escape-for-regex-junit.xml, test/end-to-end/cases/expected/stylesheet/force-focus_escape-for-regex-result.html, test/end-to-end/cases/expected/stylesheet/force-focus_escape-for-regex-result.xml, test/end-to-end/cases/expected/stylesheet/force-focus_focus-1-junit.xml, test/end-to-end/cases/expected/stylesheet/force-focus_focus-1-result.html, test/end-to-end/cases/expected/stylesheet/force-focus_focus-1-result.xml, test/end-to-end/cases/force-focus-reporter.xsl, test/end-to-end/cases/force-focus_escape-for-regex.xspec, test/end-to-end/cases/force-focus_focus-1.xspec, test/win-bats/collection.xml, test/xspec.bats
[Oxygen XSpec Helper View](https://github.com/xspec/oXygen-XML-editor-xspec-support) has an ability to rerun only the failed tests. Unfortunately the way it's implemented breaks `x:variable`, because the target scenario templates are called [directly](https://github.com/xspec/oXygen-XML-editor-xspec-support/blob/7240b9bf2229676c4a8097425a6cf8bd5759ca9e/frameworks/xspec/oxygen-results-view/compile-driver.xsl#L31-L34).
This pull request provides a standard interface for that use case. It's controlled by a new Ant property `xspec.force.focus` which is a string of one or more scenario IDs separated by whitespace characters. If the property is set, the string is passed on to `src/compiler/generate-common-tests.xsl` who sets `@focus` on the corresponding scenarios and removes `@focus` from the …
=> feat: force focus on demand in Ant build

src/reporter/coverage-report.xsl, test/issue-1135.xspec, test/issue-1135/issue-1135.xsl
Fixes #1135
- c6c538941f1c672afe16bbeec74a00acff4b6ad6 reproduces the bug
- c2168cd0a7735e0a40cbf9fe79b3e7777aefd7e0 fixes it by resolving `@stylesheet` with the base URI
=> fix(report): resolve coverage stylesheet URI via xml:base

editors/oxygen/add-on/description/latest.xhtml, oxygen-addon.xml, xspec.xpr
Following #1103, this pull request publishes the latest `master` via Oxygen add-on channel.
I tested this change on Oxygen 22.1 build 2020072902 using `https://github.com/AirQuick/xspec/raw/oxy-addon_2-0-3/oxygen-addon.xml`.
=> build(oxygen): add-on v2.0.3

src/compiler/gatherer.xsl, src/compiler/generate-common-tests.xsl
At least three players need to handle `x:import`, but they take different strategies:
- `src/compiler/generate-common-tests.xsl`: Most advanced
- `src/schematron/schut-to-xspec.xsl`: Primitive
- `src/schematron/generate-step3-wrapper.xsl`: None (#733)
This pull request extracts some components from `generate-common-tests.xsl` and put them into `gatherer.xsl`. It will facilitate resolving various `x:import` issues.
=> refactor: extract gatherer.xsl from generate-common-tests.xsl

src/schematron/schut-to-xspec.xsl
Just relocate some templates within `src/schematron/schut-to-xspec.xsl` so that the default mode templates are grouped together.
=> refactor(schematron): group default mode templates

test/end-to-end/processor/base/compare.xsl
Print the unparsed text of the result, in addition to the normalized result, on end-to-end test failure.
=> test: print unparsed result on end-to-end test failure

test/ant/worker/generate.xsl, test/end-to-end/cases/xml-1-1_schematron.xspec
Skip `xml-1-1_schematron.xspec` on Travis CI due to #1156, because the compiled stylesheet on a failed job seems sound and there seems to be nothing we can do in the short term.
=> test(schematron): skip xml-1-1_schematron.xspec on Travis CI

editors/oxygen/add-on/description/latest.xhtml, oxygen-addon.xml, xspec.xpr
Following the recent changes, this pull request publishes the latest `master` via Oxygen add-on channel.
I tested this change on Oxygen 22.1 build 2020072902 using `https://github.com/AirQuick/xspec/raw/oxy-addon_2-0-4/oxygen-addon.xml`.
=> build(oxygen): add-on v2.0.4

src/common/xspec-utils.xsl, test/xspec-utils_stylesheet.xspec
Remove `test` prefix support from `x:known-UQName()`, as #1149 has obsoleted it.
=> refactor: remove `test` prefix support from x:known-UQName()

src/compiler/compile-xslt-tests.xsl, src/compiler/xslt/compile/compile-expect.xsl, src/compiler/xslt/compile/compile-scenario.xsl
Just remove some duplicate `xsl:namespace-alias`.
=> refactor(xslt): remove duplicate xsl:namespace-alias

test/ant/worker/generate.xsl
Skip `xml-1-1_schematron.xspec` on macOS on GitHub Actions due to #1156. 
Using another XML parser may possibly fix it, but I'm reluctant to try it, as the problem has not been reproduced on my local machine and not always be reproduced on CI systems. Also, I don't want to introduce another test dependency at this moment.
=> test(schematron): skip xml-1-1_schematron.xspec on GitHub Actions macOS

editors/oxygen/add-on/description/latest.xhtml, oxygen-addon.xml, xspec.xpr
Following #1222, this pull request publishes the latest `master` via Oxygen add-on channel.
I tested this change on Oxygen 22.1 build 2020072902 using `https://github.com/AirQuick/xspec/raw/oxy-addon_2-0-5/oxygen-addon.xml`.
=> build(oxygen): add-on v2.0.5

test/ci/env/global.env, test/ci/print-env.sh
Skip 9.4.2. It has a [bug](https://mailman.uni-konstanz.de/pipermail/basex-talk/2020-August/015642.html) which prevents XSpec from working.
=> ci(deps): bump BaseX from 9.4.1 to 9.4.3

test/select-node.xspec, test/x-context.xspec
Like #320, this pull request just hardens some `@test` expressions in test files.
Note that `@test` is a tricky attribute as demonstrated below.
```xspec
<x:scenario label="Test">
<x:call function="zero-or-one">
<x:param as="empty-sequence()" />
</x:call>
<x:variable as="element(e)" name="e">
<e />
</x:variable>
<x:expect label="This x:expect is Success" test="$x:result is $e" />
</x:scenario>
```
=> test: harden risky attribute(test)

src/compiler/xslt/external/transform-options.xsl
When a scenario does not specify parameters, `x:transform-options` template still creates map entries like this:
```xslt
<xsl:map-entry key="'template-params'">
<xsl:map/>
</xsl:map-entry>
```
They are harmless but clutter up the compiled stylesheet. This pull request suppresses them.
=> refactor(xslt): suppress meaningless map-entry for $transform-options

.github/workflows/test.yml
Reflecting actions/upload-artifact#104, this pull request adds `if-no-files-found: error`.
=> ci(maven): error when no files found in upload-artifact action

src/compiler/base/resolve-import/gather/gather-specs.xsl
Just move some comments from `mode="x:gather-specs"` to its worker `mode="local:gather-user-content"`.
=> docs: split x:gather-specs mode comments

test/external_param-position.xsl, test/external_param-position.xspec, test/param-position.xqm, test/param-position.xsl, test/param-position.xspec
Test `x:call[@function]/x:param/@position` with `@run-as="external`.
Some patterns of `@position` look bad, but that's how `@position` has been working:
- `@position` can be duplicate.
- `@position` is not absolute but relative.
- `@position[. le 0]` is allowed.
- `x:param[empty(@position)]` precedes `x:param[@position >= 1]`.
=> test: function-param attribute(position) with run-as=external

test/common-utils.xspec, test/deep-equal.xspec, test/format-utils.xspec, test/report-sequence.xspec, test/report-sequence_query.xspec, test/report-sequence_query_schema-aware.xspec, test/report-sequence_stylesheet.xspec, test/report-sequence_stylesheet_schema-aware.xspec, test/uqname-utils.xspec, test/user-content-utils.xspec, test/version-utils.xspec, test/wrap.xspec, test/xspec-name.xspec
Just consolidate some `x:call` in `test/*.xspec` using [nesting](https://github.com/xspec/xspec/wiki/Nesting-Scenarios).
=> test: consolidate x:call using nesting

src/schemas/xspec.rnc, test/tunnel-param.xspec
`src/schemas/xspec.rnc` defines `x:param/@tunnel` as `"yes" | "no"`, whereas XSLT 3.0 `xsl:param/@tunnel` is [boolean](https://www.w3.org/TR/xslt-30/#notation).
This pull request aligns `xspec.rnc` with XSLT 3.0.
=> feat(xslt): boolean attribute(tunnel)

src/compiler/base/combine/mode/unshare-scenarios.xsl, src/schemas/xspec.rnc, test/end-to-end/cases/expected/query/shared-like-junit.xml, test/end-to-end/cases/expected/query/shared-like-result.html, test/end-to-end/cases/expected/query/shared-like-result.xml, test/end-to-end/cases/expected/stylesheet/shared-like-junit.xml, test/end-to-end/cases/expected/stylesheet/shared-like-result.html, test/end-to-end/cases/expected/stylesheet/shared-like-result.xml, test/end-to-end/cases/shared-like.xspec
For consistency with the other attributes, this pull request defines `x:scenario/@shared` as `boolean.datatype`.
=> feat: boolean attribute(shared)

src/compiler/base/compile/compile-child-scenarios-or-expects.xsl, test/nested-context.xspec, test/nested-function-call.xspec, test/nested-template-call.xspec, test/param-position.xspec
Related to #1262 
Currently `@position` in nested scenarios is accumulated whereas `@name` is overridden.
This pull request makes `@position` overridable.
=> fix: make x:param[attribute(position)] overridable

test/ci/test-maven-jar.cmd, test/ci/test-maven-jar.sh
In response to https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/ , this pull request replaces the deprecated `set-env` commands in GitHub Actions workflows with the new [environment files](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files).
=> ci(maven): replace `set-env` command with environment file

editors/oxygen/add-on/description/latest.xhtml, oxygen-addon.xml, xspec.xpr
- The [changelog](https://htmlpreview.github.io/?https://github.com/AirQuick/xspec/blob/ea78100bc514891cedbfc497467ea18aab70c77a/editors/oxygen/add-on/description/latest.xhtml) denotes this version as "Release Candidate of the stable release".
- #1276 is not mentioned in the changelog, because it has nothing to do with Oxygen.
I tested this change on Oxygen 22.1 build 2020100710 using `https://github.com/AirQuick/xspec/raw/oxy-addon_2-0-6/oxygen-addon.xml`:
- All the 4 transformation scenarios work including **Run XSpec Test** with XSLT, XQuery, Schematron and the latest visible change (#1273).
- DITA DTD takes effect via `${xmlCatalogFilesList}` (#980).
- Loading `xspec.xpr` disables the add-on.
=> build(oxygen): add-on v2.0.6

editors/oxygen/add-on/description/latest.xhtml, oxygen-addon.xml, pom.xml, xspec.xpr
This pull request increments the version numbers in `pom.xml` and `oxygen-addon.xml`, which makes the official stable release of `v2.0`. (technically `v2.0.7`, based on #940)
As for the file paths in `oxygen-addon.xml`, I used the last `master` SHA rather than the git tag `v2.0.7`, because we haven't had the actual tag yet and therefore cannot test it. I tested the Oxygen add-on on Oxygen 23.0 build 2020111805 using `https://github.com/AirQuick/xspec/raw/rel_2-0-7/oxygen-addon.xml`.
=> build: release v2.0.7

pom.xml
As per our [workflow](https://github.com/xspec/xspec/wiki/Release-Workflow#updating-pomxml), this pull request increases the version of the XSpec release and adds the snapshot suffix. 
As usual, this should be the first pull request to be merged into `master` in order to start the development of XSpec v2.1.
=> build(maven): bump pom.xml to 2.1-SNAPSHOT

test/ci/env/global.env, test/ci/print-env.sh
> VERSION 9.4.4 (November 6, 2020) ---------------------------------------
> 
>  - Performance tweaks, minor bug fixes
"minor bug" includes [a bug](https://mailman.uni-konstanz.de/pipermail/basex-talk/2020-September/015743.html) that affected `test/ci/print-env.sh`.
=> ci(deps): bump BaseX from 9.4.3 to 9.4.4

test/ci/env/global.env, test/ci/print-env.sh
(This pull request should be handled after #1286.)
> VERSION 9.4.5 (November 24, 2020) --------------------------------------
> 
>  - Minor bug fixes
=> ci(deps): bump BaseX from 9.4.4 to 9.4.5

bin/xspec.sh
`xspec.sh` has broken `[1]` link in one of its comments:
https://github.com/xspec/xspec/blob/cd3e7622bc550285ae75c060da7a24f94a4fb0d2/bin/xspec.sh#L57-L63
This pr fixes it by reverting a part of #66.
=> docs(cli): revert 33684b7 with regard to xspec.sh

src/compiler/xslt/compile/compile-expect.xsl, tutorial/under-the-hood/Compilation.md
One of the compiled stylesheet comments assumes that `@test` context (if not absent) is always a node. In fact, it can be a non-node item. (otherwise a [tutorial](https://github.com/xspec/xspec/blob/cd3e7622bc550285ae75c060da7a24f94a4fb0d2/tutorial/escape-for-regex.xspec#L65) wouldn't work.)
This pr fixes the comment.
=> docs(xslt): attribute(test) context may not always be node

tutorial/xquery-tutorial.xqm
`tutorial/xquery-tutorial.xqm` takes a function from FunctX XQuery library without mentioning it.
This pull request adds its source URL, just like [tutorial/escape-for-regex.xsl](https://github.com/xspec/xspec/blob/e7755c7c42c49c2eb4edf84f187390ca15def8b7/tutorial/escape-for-regex.xsl#L11).
(Strictly speaking, I guess we should attach its license or use our original function.)
=> docs(xquery): credit for functx:capitalize-first()

.github/workflows/test.yml
From [Requirement](https://github.com/xspec/xspec/wiki/Requirements#saxon-98-is-deprecated):
> ### Saxon 9.8 is deprecated
>
> XSpec is partially tested on Saxon 9.8.
Reflecting its status, this pull request excludes Saxon 9.8 from Windows and macOS matrix in GitHub Actions Test workflow.
=> ci: exclude Saxon 9.8 from Windows and macOS in GitHub Actions Test

editors/oxygen/add-on/description/latest.xhtml, oxygen-addon.xml, xspec.xpr
I tested this change on Oxygen 23.0 build 2020111805 using `https://github.com/AirQuick/xspec/raw/oxy-addon_2-1-0/oxygen-addon.xml`.
=> build(oxygen): add-on v2.1.0

test/catch_stylesheet.xspec, test/compiler-yes-no-utils.xspec, test/external_tutorial_global-context-item_original.xspec, test/external_xslt-package_arith_private.xspec, test/issue-1029.xspec, test/issue-700.xspec, test/version-utils.xspec, test/xsl-result-document.xspec, test/xspec-name.xspec
Just remove verbose `$x:result` from `$x:result?err` in `x:expect/@test` in `test/*.xspec`.
In essence, nothing has been changed by this removal.
=> test(xslt): remove verbose $x:result from attribute(test)

xspec.xpr
Loading a project file in Oxygen 23.0 removes `@version` from it. This pull request reflects it.
=> refactor(oxygen): update xspec.xpr using Oxygen 23.0 build 2020121712

src/common/report-sequence.xsl, test/report-sequence.xspec, test/report-sequence_stylesheet.xspec, test/win-bats/collection.xml, test/xspec.bats
Different processors support different types. To make sure of compatibility, this pull request tests `src/common/report-sequence.xqm` with BaseX.
=> test(basex): test report-sequence.xqm with BaseX

src/common/report-sequence.xqm, src/common/report-sequence.xsl, test/ant/build.xml, test/ant/worker/generate.xsl, test/caps/java-reflexive-ext-fn.xq, test/caps/java-reflexive-ext-fn.xsl, test/end-to-end/cases/expected/query/issue-355-result.html, test/end-to-end/cases/expected/query/issue-355-result.xml, test/end-to-end/cases/expected/query/report_java-object-junit.xml, test/end-to-end/cases/expected/query/report_java-object-result.html, test/end-to-end/cases/expected/query/report_java-object-result.xml, test/end-to-end/cases/expected/stylesheet/report_java-object-junit.xml, test/end-to-end/cases/expected/stylesheet/report_java-object-result.html, test/end-to-end/cases/expected/stylesheet/report_java-object-result.xml, test/end-to-end/cases/report_java-object.xspec
Use the adaptive output method of serialization, when the type of an item cannot be identified.
With this change, XQuery report for functions is slightly improved:
- [old](https://htmlpreview.github.io/?https://github.com/xspec/xspec/blob/5d0080032d479190acf2e6c38112ef096929f941/test/end-to-end/cases/expected/query/issue-355-result.html)
- [new](https://htmlpreview.github.io/?https://github.com/xspec/xspec/blob/1d92fe3b61958e7f08c8fa4fec5db19dc426cbe1/test/end-to-end/cases/expected/query/issue-355-result.html)
=> feat: report serialized form of unknown type

src/common/report-sequence.xqm, src/common/report-sequence.xsl, test/end-to-end/cases/expected/query/report-junit.xml, test/end-to-end/cases/expected/query/report-result.html, test/end-to-end/cases/expected/query/report-result.xml, test/end-to-end/cases/expected/stylesheet/report-junit.xml, test/end-to-end/cases/expected/stylesheet/report-result.html, test/end-to-end/cases/expected/stylesheet/report-result.xml, test/end-to-end/cases/report.xspec, test/report-sequence_stylesheet.xspec
Report `xs:dateTimeStamp`. ([example](https://htmlpreview.github.io/?https://github.com/xspec/xspec/blob/ec80dbae5c9b9304af83789614dcb8daff547379/test/end-to-end/cases/expected/stylesheet/report-result.html#scenario8-scenario1-scenario1-expect1))
Not for XQuery, because BaseX [doesn't support](https://mailman.uni-konstanz.de/pipermail/basex-talk/2017-November/012690.html) `xs:dateTimeStamp`.
=> feat(xslt): report xs:dateTimeStamp

src/compiler/base/compile/compile-child-scenarios-or-expects.xsl, src/compiler/base/invoke-compiled/invoke-compiled-child-scenarios-or-expects.xsl, src/compiler/base/main.xsl, src/compiler/xquery/compile/compile-scenario.xsl, src/compiler/xslt/compile/compile-scenario.xsl
Right now the XSpec compiler assumes that only `x:variable` contributes to the stack of scenario variables.
In preparation for #991, this pr generalizes it a bit so that other elements (namely `x:param`) can be inserted to the stack smoothly.
=> refactor: generalize variable declaration stack

src/compiler/xquery/compile/compile-expect.xsl
Just remove an unused `@expand-text` from `src/compiler/xquery/compile/compile-expect.xsl`.
=> refactor(xquery): remove unused attribute(expand-text)

test/end-to-end/cases/expected/query/three-dots-junit.xml, test/end-to-end/cases/expected/query/three-dots-result.html, test/end-to-end/cases/expected/query/three-dots-result.xml, test/end-to-end/cases/expected/stylesheet/three-dots-junit.xml, test/end-to-end/cases/expected/stylesheet/three-dots-result.html, test/end-to-end/cases/expected/stylesheet/three-dots-result.xml, test/end-to-end/cases/three-dots.xqm, test/end-to-end/cases/three-dots.xsl, test/end-to-end/cases/three-dots.xspec
Remove some dependency on `*.(xqm|xsl)` from `test/end-to-end/cases/three-dots.xspec`.
=> test: make three-dots.xspec less language-dependent

src/compiler/base/combine/mode/check-combined-doc.xsl, test/variable-overriding-param/global-variable.xspec, test/variable-overriding-param/local-variable/description-param.xspec, test/win-bats/collection.xml, test/xspec.bats
With `@run-as="external"`, only `/x:description/x:param` is supposed to take effect in SUT. `x:variable` is not.
However, `x:variable` can override `x:param` and effectively go into SUT. For example:
With this stylesheet
```xslt
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:param name="p" />
<xsl:template name="get-p">
<xsl:sequence select="$p" />
</xsl:template>
<xsl:param name="v" />
<xsl:template name="get-v">
<xsl:sequence select="$v" />
</xsl:template>
</xsl:stylesheet>
```
and this XSpec
```xspec
<?xml version="1.0" encoding="UTF-8"?>
<x:description run-as="external" stylesheet="test.xsl"
xmlns:x="http://www.jenitennison.com/xslt/xspec">
<x:param name="p">global-p</x:param>
<x:variable …
```
=> feat: do not allow x:variable to override x:param

test/ci/env/global.env
> VERSION 9.4.6 (January 7, 2021) ----------------------------------------
> 
>  - Performance tweaks, minor bug fixes
=> ci(deps): bump BaseX from 9.4.5 to 9.4.6

test/schxslt/base-uri.xsl
Just update the SchXslt version used for testing.
Skip v1.6 and v1.6.1 due to these bugs:
- schxslt/schxslt#157
- schxslt/schxslt#158
=> test(schematron): test with SchXslt v1.6.2

src/compiler/base/compile/compile-child-scenarios-or-expects.xsl, src/compiler/base/compile/compile-scenario.xsl, src/compiler/base/invoke-compiled/invoke-compiled-child-scenarios-or-expects.xsl, src/compiler/xquery/compile/compile-expect.xsl, src/compiler/xquery/compile/compile-scenario.xsl, src/compiler/xquery/invoke-compiled/invoke-compiled-current-scenario-or-expect.xsl, src/compiler/xslt/compile/compile-expect.xsl, src/compiler/xslt/compile/compile-scenario.xsl, src/compiler/xslt/external/transform-options.xsl, src/compiler/xslt/invoke-compiled/invoke-compiled-current-scenario-or-expect.xsl, src/reporter/format-utils.xsl, test/compile-xslt-tests.xspec
Add `required="yes"` to some `xsl:param` that may be empty. This clarifies who is responsible for creating the parameters.
This change is partly in preparation for #991.
=> refactor: required=yes for clarifying responsibility of some xsl:param

src/compiler/base/invoke-compiled/invoke-compiled-child-scenarios-or-expects.xsl, src/compiler/xquery/compile/compile-scenario.xsl, src/compiler/xquery/main.xsl, src/compiler/xslt/compile/compile-scenario.xsl, src/compiler/xslt/main.xsl
Pass the handled `x:param | x:variable` to the `x:invoke-compiled-child-scenarios-or-expects` template so that the `local:invoke-compiled-scenarios-or-expects` mode can forget about the logic behind selecting `x:param | x:variable`.
This change is partly in preparation for #991.
=> refactor: pass handled variable declarations

src/compiler/base/compile/compile-child-scenarios-or-expects.xsl, src/compiler/base/invoke-compiled/invoke-compiled-child-scenarios-or-expects.xsl, src/compiler/base/util/compiler-misc-utils.xsl, src/compiler/xquery/compile/compile-expect.xsl, src/compiler/xquery/compile/compile-scenario.xsl, src/compiler/xquery/declare-variable/declare-variable.xsl, src/compiler/xslt/compile/compile-expect.xsl, src/compiler/xslt/compile/compile-scenario.xsl, src/compiler/xslt/declare-variable/declare-variable.xsl, test/end-to-end/cases/expected/query/issue-1340-junit.xml, test/end-to-end/cases/expected/query/issue-1340-result.html, test/end-to-end/cases/expected/query/issue-1340-result.xml, test/end-to-end/cases/expected/stylesheet/issue-1340-junit.xml, test/end-to-end/cases/expected/stylesheet/issue-1340-result.html, test/end-to-end/cases/expected/stylesheet/issue-1340-result.xml, test/end-to-end/cases/issue-1340.xspec
Fixes #1340 
XSpec compiler searches any elements for `@focus` when it should have searched only `x:scenario`. This pull request fixes it.
=> fix: search only x:scenario for attribute(focus)

src/common/deep-equal.xqm, src/common/deep-equal.xsl
The 4th branch in `deep-equal-v1()` is never fired, because `$seq1[. instance of xs:integer]` enters the 3rd branch (`xs:decimal`). This pull request removes the unused 4th branch.
=> refactor: remove unused branch from deep-equal-v1()

test/variable.xspec
`$myv:test-data` in `test/variable.xspec` is not used.
In its initial commit (76c9ac59cafc54d5ca1b0baa0edb9a4b83d5e933), `$myv:test-data` seems to test referencing a global variable from another global variable. So this pull request just adds a reference from `$myv:test-string` to `$myv:test-data`.
=> test: use $myv:test-data in variable.xspec

test/variable.xspec
Now that we can use XPath 3, this pr just replaces `concat()` in `variable.xspec` with the `||` operator.
=> test: replace concat() with || in variable.xspec

src/compiler/xquery/compile/compile-scenario.xsl, src/compiler/xslt/compile/compile-scenario.xsl
Small refactoring about `$local-preceding-vardecls` in `compile-scenario.xsl`.
This is meant to reduce noise in the upcoming pr for #991.
=> refactor: use predicate for selecting $local-preceding-vardecls

test/end-to-end/cases/expected/stylesheet/issue-793-cr-junit.xml, test/end-to-end/cases/expected/stylesheet/issue-793-cr-result.html, test/end-to-end/cases/expected/stylesheet/issue-793-cr-result.xml, test/end-to-end/cases/expected/stylesheet/issue-793-crlf-junit.xml, test/end-to-end/cases/expected/stylesheet/issue-793-crlf-result.html, test/end-to-end/cases/expected/stylesheet/issue-793-crlf-result.xml, test/end-to-end/cases/expected/stylesheet/issue-793-lf-junit.xml, test/end-to-end/cases/expected/stylesheet/issue-793-lf-result.html, test/end-to-end/cases/expected/stylesheet/issue-793-lf-result.xml, test/end-to-end/cases/issue-793-cr.xspec, test/end-to-end/cases/issue-793-crlf.xspec, test/end-to-end/cases/issue-793-lf.xspec
`issue-793-cr.xsl` must have CR line ending, but Git sees the file as a binary file and therefore its line ending is prone to be broken.
This pr adds some scenarios for inspecting the line ending of the stylesheet being tested.
=> test(xslt): verify stylesheet line ending in testing issue 793

.github/workflows/rebase-schxslt.yml
Add a GitHub Actions workflow that keeps rebasing `schxslt` branch onto `master` branch. See #1380 for the purpose.
[A test run](https://github.com/xspec/xspec/actions/runs/660524515) worked successfully on this pr branch. So I presume it will also work after merging this into `master`.
Anticipating this pr and #1380, I created a branch protection rule for `schxslt` branch at the [repository settings](https://github.com/xspec/xspec/settings/branches).
=> ci(schematron): rebase schxslt branch onto master branch

.github/workflows/rebase-schxslt.yml
Fixes "Committer identity unknown" error in GitHub Actions `rebase-schxslt` workflow.
=> ci(schematron): set git user email and name when rebasing schxslt branch

test/xspec-sch.xspec
`@location` in `test/xspec-sch.xspec` has predicates in an older form. (Every expression step has a positional predicate.)
This pr removes or replaces them with less context-dependent ones.
=> test(schematron): safer attribute(location) in xspec-sch.xspec

test/external_scenario-param.sch, test/external_scenario-param.sch.included.xsl, test/external_scenario-param_schematron.xspec
`test/external_scenario-param.sch` uses a foreign element `xsl:param`, but SchXslt 1.6.2 discards it.
This pr replaces `xsl:param` with `xsl:include` which is accepted by SchXslt. `xsl:param` is declared there.
=> test(schematron): adapt external_scenario-param.sch to SchXslt

src/compiler/base/combine/mode/force-focus.xsl, src/compiler/base/combine/mode/unshare-scenarios.xsl
`mode="x:force-focus"` and `mode="x:unshare-scenarios"` in `x:combine()` have templates for user-content. They were useful when some `test/**/*.xspec` files contained `x:*` elements in user-content for testing purposes. Now the `x:*` elements in user-content are basically gone, this pull request removes the unnecessary templates.
=> refactor: remove unnecessary user-content templates from x:combine()

lib/schxslt/1.0/compile-for-svrl.xsl, lib/schxslt/1.0/compile/compile-1.0.xsl, lib/schxslt/1.0/expand.xsl, lib/schxslt/1.0/version.xsl, lib/schxslt/2.0/compile/compile-2.0.xsl, lib/schxslt/2.0/compile/functions.xsl, lib/schxslt/2.0/compile/templates.xsl, lib/schxslt/2.0/expand.xsl, lib/schxslt/2.0/include.xsl, lib/schxslt/2.0/pipeline.xsl, lib/schxslt/2.0/svrl.xsl, lib/schxslt/2.0/version.xsl, lib/schxslt/README.md, test/ant/worker/generate.xsl, test/end-to-end/cases/expected/schematron/issue-693-result.html, test/end-to-end/cases/expected/schematron/issue-693-result.xml, test/end-to-end/cases/expected/schematron/schematron-023-result.html, test/end-to-end/cases/expected/schematron/schematron-023-result.xml, test/end-to-end/cases/expected/schematron/schematron-import_demo-02-PhaseB-result.xml, test/end-to-end/cases/expected/schematron/tvt_label_schematron-result.xml, test/end-to-end/cases/expected/schematron/xml-1-1_schematron-result.html, test/end-to-end/cases/expected/schematron/xml-1-1_schematron-result.xml, test/schematron-020.xspec
Replace the built-in SchXslt v1.6.2 with v1.7.
=> feat(schematron): bump built-in SchXslt from 1.6.2 to 1.7

test/ant/worker/generate.xsl, test/schematron-020.xspec
SchXslt v1.7 no longer needs a test workaround. This pull request removes it.
This change is a backport from `schxslt` branch.
=> test(schematron): remove SchXslt 1.6.2 test workaround

test/external_unfocused-param.xspec, test/unfocused-param.xspec, test/unfocused-variable.xspec
Test `(/x:description|//x:scenario)/(x:param|x:variable)` when they are out of a focused scenario.
=> test: unfocused param and variable

src/reporter/coverage-report.xsl, test/end-to-end/cases/expected/stylesheet/issue-1411_entity-coverage.html, test/end-to-end/cases/expected/stylesheet/issue-1411_entity-junit.xml, test/end-to-end/cases/expected/stylesheet/issue-1411_entity-result.html, test/end-to-end/cases/expected/stylesheet/issue-1411_entity-result.xml, test/end-to-end/cases/expected/stylesheet/issue-1411_no-entity-coverage.html, test/end-to-end/cases/expected/stylesheet/issue-1411_no-entity-junit.xml, test/end-to-end/cases/expected/stylesheet/issue-1411_no-entity-result.html, test/end-to-end/cases/expected/stylesheet/issue-1411_no-entity-result.xml, test/end-to-end/cases/issue-1411_entity.xsl, test/end-to-end/cases/issue-1411_entity.xspec, test/end-to-end/cases/issue-1411_no-entity.xsl, test/end-to-end/cases/issue-1411_no-entity.xspec
This should resolve the issue that doctypes are not recognized (at least for the way I use them in my stylesheets).
=> fix(report): recognize doctypes in stylesheets

src/reporter/coverage-report.xsl, test/end-to-end/cases/expected/stylesheet/custom-coverage-report-coverage.html, test/end-to-end/cases/expected/stylesheet/external_issue-1410_invoke-empty-coverage.html, test/end-to-end/cases/expected/stylesheet/external_issue-1410_invoke-not-empty-coverage.html, test/end-to-end/cases/expected/stylesheet/external_tutorial_coverage_demo-coverage.html, test/end-to-end/cases/expected/stylesheet/issue-1411_entity-coverage.html, test/end-to-end/cases/expected/stylesheet/issue-1411_no-entity-coverage.html, test/end-to-end/cases/expected/stylesheet/issue-214-coverage.html, test/end-to-end/cases/expected/stylesheet/issue-793-cr-coverage.html, test/end-to-end/cases/expected/stylesheet/issue-793-crlf-coverage.html, test/end-to-end/cases/expected/stylesheet/issue-793-lf-coverage.html, test/end-to-end/cases/expected/stylesheet/tutorial_coverage_demo-coverage.html
Just remove empty `<span>` from the coverage report HTML.
=> refactor(report): do not emit empty span in coverage report

lib/schxslt/1.0/version.xsl, lib/schxslt/2.0/compile/compile-2.0.xsl, lib/schxslt/2.0/version.xsl, test/end-to-end/cases/expected/schematron/issue-693-result.html, test/end-to-end/cases/expected/schematron/issue-693-result.xml, test/end-to-end/cases/expected/schematron/schematron-023-result.html, test/end-to-end/cases/expected/schematron/schematron-023-result.xml, test/end-to-end/cases/expected/schematron/schematron-import_demo-02-PhaseB-result.xml, test/end-to-end/cases/expected/schematron/tvt_label_schematron-result.xml, test/end-to-end/cases/expected/schematron/xml-1-1_schematron-result.html, test/end-to-end/cases/expected/schematron/xml-1-1_schematron-result.xml
Replace the built-in SchXslt v1.7 with v1.7.1.
=> feat(schematron): bump built-in SchXslt to v1.7.1

test/end-to-end/cases/expected/stylesheet/issue-1411_entity_single-line-coverage.html, test/end-to-end/cases/expected/stylesheet/issue-1411_entity_single-line-junit.xml, test/end-to-end/cases/expected/stylesheet/issue-1411_entity_single-line-result.html, test/end-to-end/cases/expected/stylesheet/issue-1411_entity_single-line-result.xml, test/end-to-end/cases/issue-1411_entity_single-line.xsl, test/end-to-end/cases/issue-1411_entity_single-line.xspec
Test code coverage with a stylesheet that consists of a single line (no CR or LF).
=> test(report): code coverage with single line stylesheet

test/line-number_disabled.xspec, test/line-number_enabled.xspec
Remove verbose `x:call/@function` from `test/line-number_*abled.xspec`.
=> test: consolidate x:call/attribute(function) in line-number_*abled.xspec

editors/oxygen/add-on/description/latest.xhtml, oxygen-addon.xml, xspec.xpr
The [changelog](https://htmlpreview.github.io/?https://github.com/AirQuick/xspec/blob/d847643/editors/oxygen/add-on/description/latest.xhtml) denotes this version as "Release Candidate of the stable release".
I tested this change on Oxygen 23.1 build 2021030206 using `https://github.com/AirQuick/xspec/raw/oxy-addon_2-1-3/oxygen-addon.xml`:
- All the 4 transformation scenarios work including **Run XSpec Test** with XSLT, XQuery, Schematron and the latest visible change (#1412).
- Loading `xspec.xpr` disables the add-on and enables its own framework.
=> build(oxygen): add-on v2.1.3

editors/oxygen/add-on/description/latest.xhtml, oxygen-addon.xml, pom.xml, xspec.xpr
This pull request increments the version numbers in `pom.xml` and `oxygen-addon.xml`, which makes the official stable release of `v2.1`. (technically `v2.1.4`, based on #940)
As for the file paths in `oxygen-addon.xml`, I used the last `master` SHA rather than the git tag `v2.1.4`, because we haven't had the actual tag yet and therefore cannot test it. I tested the Oxygen add-on on Oxygen 23.1 build 2021040908 using `https://github.com/AirQuick/xspec/raw/rel_2-1-4/oxygen-addon.xml`.
=> build: release v2.1.4

pom.xml
As per our [workflow](https://github.com/xspec/xspec/wiki/Release-Workflow#updating-pomxml), this pull request increases the version of the XSpec release and adds the snapshot suffix. 
As usual, this should be the first pull request to be merged into `master` in order to start the development of XSpec v2.2.
=> build(maven): bump pom.xml to 2.2-SNAPSHOT

.github/workflows/rebase-schxslt.yml
Looks like the automated rebasing of `schxslt` branch is not triggering GitHub Actions in that branch. (Azure Pipelines and AppVeyor are triggered.)
As per https://github.community/t/push-from-action-does-not-trigger-subsequent-action/16854 , this pr tries fixing it by adding `token` to `checkout` action.
=> ci(schematron): checkout action with GITHUB_TOKEN in rebase-schxslt.yml

appveyor.yml
For performance reasons, this pr skips AppVeyor on
- `schxslt` branch
- tag push
- branches with open pull request
=> ci: skip AppVeyor on schxslt branch or tags or branch with open pr

.github/workflows/rebase-schxslt.yml
This reverts commit f4b86ec27598f119205449dc45d517d4e6788081 which didn't work. Looks like the token in this case must be a real personal access token which I'm reluctant to create.
Still, the `schxslt` branch is always tested by Azure Pipelines and sometimes (when pushed by a human) by GitHub Actions. That would be suffice for now.
=> revert(schematron): "co w/ GITHUB_TOKEN in rebase-schxslt.yml (#1463)"

.github/dependabot.yml
Closes #1019 
Following #1460, this pr adds `package-ecosystem: github-actions` to `.github/dependabot.yml`.
=> ci(deps): add GitHub Actions to Dependabot config

azure-pipelines.yml
For performance reasons, this pr skips Azure Pipelines on
- push in Dependabot branch; it's still triggered by pr event.
- tag push; it's still triggered by commit push.
=> ci: skip Azure Pipelines on Dependabot push or any tag

test/ci/azure-pipelines_windows.yml
Somehow Azure Pipelines is getting slower nowadays. This pull request removes deprecated Saxon 9.8 from Azure Pipelines and sets `timeoutInMinutes: 0`.
=> ci: remove Saxon 9.8 from Azure Pipelines

.github/workflows/lint.yml, .github/workflows/test.yml
Add [`workflow_dispatch`](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/) to `lint.yml` and `test.yml` in `.github/workflows/` so that we can trigger them in the `schxslt` branch (or any others) at any time.
=> ci: add `workflow_dispatch` to GitHub Actions Lint and Test workflow

.codespellrc
The current *codespell* configuration ignores everything in `lib/` including `lib/README.md`.
This pr fixes it so that only the subdirs of `lib/` are ignored.
=> ci: codespell immediate child files of lib dir

pom.xml
https://issues.apache.org/jira/browse/MGPG-59 suggests that a workaround configuration of maven-gpg-plugin is no longer necessary on 3.0.0 or later. This PR removes it.
I'm not entirely sure about the fix, so I'm just merging this PR and will see if it works. I'll revert it immediately on failure.
=> build(maven): remove `--pinentry-mode` gpg arg from maven-gpg-plugin

lib/schxslt/1.0/version.xsl, lib/schxslt/2.0/expand.xsl, lib/schxslt/2.0/version.xsl, test/end-to-end/cases/expected/schematron/issue-693-result.html, test/end-to-end/cases/expected/schematron/issue-693-result.xml, test/end-to-end/cases/expected/schematron/schematron-023-result.html, test/end-to-end/cases/expected/schematron/schematron-023-result.xml, test/end-to-end/cases/expected/schematron/schematron-import_demo-02-PhaseB-result.xml, test/end-to-end/cases/expected/schematron/tvt_label_schematron-result.xml, test/end-to-end/cases/expected/schematron/xml-1-1_schematron-result.html, test/end-to-end/cases/expected/schematron/xml-1-1_schematron-result.xml
Replace the built-in SchXslt v1.7.1 with v1.7.2.
=> feat(schematron): bump built-in SchXslt to v1.7.2

test/end-to-end/cases/expected/schematron/focus-vs-pending_schematron-result.html, test/end-to-end/cases/expected/schematron/focus-vs-pending_schematron-result.xml, test/end-to-end/cases/expected/schematron/pending_schematron-result.html, test/end-to-end/cases/expected/schematron/pending_schematron-result.xml, test/end-to-end/processor/html/_normalizer.xsl
#1446 needs an adjustment in normalizing the test result HTML generated with SchXslt. This pull request updates `test/end-to-end/processor/html/_normalizer.xsl` and regenerates the expected results of #1446 for SchXslt.
=> test(schematron): normalize SchXslt attribute(documents) in a new line

editors/oxygen/add-on/description/latest.xhtml, oxygen-addon.xml, xspec.xpr
I tested this change on Oxygen 23.1 build 2021040908 using `https://github.com/AirQuick/xspec/raw/oxy-addon_2-2-0/oxygen-addon.xml`.
=> build(oxygen): add-on v2.2.0

test/ci/env/global.env
> VERSION 9.5.2 (May 27, 2021) -------------------------------------------
> 
>  - Performance tweaks, minor bug fixes
=> ci(deps): bump BaseX from 9.5.1 to 9.5.2

.github/workflows/maven-deploy.yml, .github/workflows/test.yml
Specify minor and patch versions for `actions/setup-java` and `actions/upload-artifact`. That will make it easier to track changes of their releases.
=> ci: specify GitHub Actions minor patch version

test/ci/env/global.env
This pull request just updates the Ant version used for testing.
=> ci(deps): bump Ant from 1.10.10 to 1.10.11

test/end-to-end/processor/html/_normalizer.xsl
Backport `test/end-to-end/processor/html/_normalizer.xsl` from `schxslt` branch to `master` so that the end-to-end tests work with both SchXslt and the "skeleton" Schematron implementation.
=> test(schematron): backport e2e test HTML normalizer from schxslt branch

lib/schxslt/1.0/compile/compile-1.0.xsl, lib/schxslt/1.0/version.xsl, lib/schxslt/2.0/compile/templates.xsl, lib/schxslt/2.0/version.xsl, test/end-to-end/cases/expected/schematron/focus-vs-pending_schematron-result.html, test/end-to-end/cases/expected/schematron/focus-vs-pending_schematron-result.xml, test/end-to-end/cases/expected/schematron/issue-693-result.html, test/end-to-end/cases/expected/schematron/issue-693-result.xml, test/end-to-end/cases/expected/schematron/pending_schematron-result.html, test/end-to-end/cases/expected/schematron/pending_schematron-result.xml, test/end-to-end/cases/expected/schematron/schematron-023-result.html, test/end-to-end/cases/expected/schematron/schematron-023-result.xml, test/end-to-end/cases/expected/schematron/schematron-import_demo-02-PhaseB-result.xml, test/end-to-end/cases/expected/schematron/tvt_label_schematron-result.xml, test/end-to-end/cases/expected/schematron/xml-1-1_schematron-result.html, test/end-to-end/cases/expected/schematron/xml-1-1_schematron-result.xml
Replace the built-in SchXslt v1.7.2 with v1.7.3.
=> feat(schematron): bump built-in SchXslt to v1.7.3

test/end-to-end/cases/expected/schematron/focus-vs-pending_schematron-result.html, test/end-to-end/cases/expected/schematron/focus-vs-pending_schematron-result.xml, test/end-to-end/cases/expected/schematron/issue-693-result.html, test/end-to-end/cases/expected/schematron/issue-693-result.xml, test/end-to-end/cases/expected/schematron/pending_schematron-result.html, test/end-to-end/cases/expected/schematron/pending_schematron-result.xml, test/end-to-end/cases/expected/schematron/schematron-023-result.html, test/end-to-end/cases/expected/schematron/schematron-023-result.xml, test/end-to-end/cases/expected/schematron/schematron-import_demo-02-PhaseB-result.xml, test/end-to-end/cases/expected/schematron/tvt_label_schematron-result.xml, test/end-to-end/cases/expected/schematron/xml-1-1_schematron-result.html, test/end-to-end/cases/expected/schematron/xml-1-1_schematron-result.xml, test/end-to-end/processor/html/_normalizer.xsl, test/end-to-end/processor/xml/_normalizer.xsl
To reduce noise, this pull request normalizes SchXslt version numbers in the result report XML and HTML while performing end-to-end tests.
=> test: normalize SchXslt version in result report XML and HTML

lib/schxslt/1.0/version.xsl, lib/schxslt/2.0/compile/compile-2.0.xsl, lib/schxslt/2.0/version.xsl
Replace the built-in SchXslt v1.7.3 with v1.7.4.
=> feat(schematron): bump built-in SchXslt to v1.7.4

.github/workflows/test.yml, azure-pipelines.yml
`bats` on macOS is stale (0.4.0) on both GitHub Actions and Azure Pipelines.
This pull request replaces it with the latest package (1.3.0 at the time of this writing).
=> ci(deps): replace bats with bats-core on macOS

test/schematron/bad-location/atomic/expect-assert.xspec, test/schematron/bad-location/atomic/expect-not-assert.xspec, test/schematron/bad-location/atomic/expect-not-report.xspec, test/schematron/bad-location/atomic/expect-report.xspec, test/schematron/bad-location/context.xml, test/schematron/bad-location/empty/expect-assert.xspec, test/schematron/bad-location/empty/expect-not-assert.xspec, test/schematron/bad-location/empty/expect-not-report.xspec, test/schematron/bad-location/empty/expect-report.xspec, test/schematron/bad-location/multiple/expect-assert.xspec, test/schematron/bad-location/multiple/expect-not-assert.xspec, test/schematron/bad-location/multiple/expect-not-report.xspec, test/schematron/bad-location/multiple/expect-report.xspec, test/schematron/bad-location/test.sch, test/win-bats/collection.xml, test/xspec.bats
Related to https://github.com/xspec/xspec/pull/1506#issuecomment-882099608.
This pull request tests bad `@location` in Schematron `x:expect-*` where `@location` selects an atomic value, an empty sequence or multiple nodes.
=> test(schematron): test bad attribute(location)

editors/oxygen/add-on/description/latest.xhtml, oxygen-addon.xml, xspec.xpr
Following #1506, this pull request publishes the latest `master` via Oxygen add-on channel.
I tested this change on Oxygen 23.1 build 2021061407 using `https://github.com/AirQuick/xspec/raw/oxy-addon_2-2-2/oxygen-addon.xml`.
=> build(oxygen): add-on v2.2.2

test/end-to-end/processor/html/_normalizer.xsl
Make `$NORMALIZE-HTML-DATETIME` in `test/end-to-end/processor/html/_normalizer.xsl` static and make a template `@match` a little bit simpler.
=> test(report): static $NORMALIZE-HTML-DATETIME

test/ci/env/global.env
> VERSION 9.6.1 (August 26, 2021) ----------------------------------------
> 
> - GUI bug fix, XQuery performance tweaks
=> ci(deps): bump BaseX from 9.6 to 9.6.1

pom.xml
Set [`<notimestamp>true</notimestamp>`](https://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html#notimestamp) on `maven-javadoc-plugin` configuration.
This change removes timestamps from Javadoc HTML files:
```diff
<html lang="en">
<head>
-
+
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Uses of Class com.jenitennison.xslt.tests.XSLTCoverageTraceListener (XSpec implementation 2.2-SNAPSHOT API)</title>
-<meta name="date" content="2021-08-29">
<link rel="stylesheet" type="text/css" href="../../../../../stylesheet.css" title="Style">
```
By removing them, verifying Javadoc artifact changes will be easier whenever we upgrade `maven-javadoc-plugin` version.
=> build(maven): notimestamp for javadoc

editors/oxygen/add-on/description/latest.xhtml, oxygen-addon.xml, xspec.xpr
The [changelog](https://htmlpreview.github.io/?https://github.com/AirQuick/xspec/blob/6709444/editors/oxygen/add-on/description/latest.xhtml) denotes this version as "Release Candidate of the stable release".
I tested this change on Oxygen 23.1 build 2021082307 using `https://github.com/AirQuick/xspec/raw/oxy-addon_2-2-3/oxygen-addon.xml`:
- All the 4 transformation scenarios work including **Run XSpec Test** with XSLT, XQuery, Schematron and the latest visible change (#1506).
- Loading `xspec.xpr` disables the add-on and enables its own framework.
=> build(oxygen): add-on v2.2.3

lib/schxslt/1.0/compile-for-svrl.xsl, lib/schxslt/1.0/compile/compile-1.0.xsl, lib/schxslt/1.0/version.xsl, lib/schxslt/2.0/compile/compile-2.0.xsl, lib/schxslt/2.0/compile/templates.xsl, lib/schxslt/2.0/svrl.xsl, lib/schxslt/2.0/version.xsl, src/schematron/generate-step3-wrapper.xsl, test/end-to-end/cases/expected/schematron/focus-vs-pending_schematron-result.html, test/end-to-end/cases/expected/schematron/focus-vs-pending_schematron-result.xml, test/end-to-end/cases/expected/schematron/issue-693-result.html, test/end-to-end/cases/expected/schematron/issue-693-result.xml, test/end-to-end/cases/expected/schematron/pending_schematron-result.html, test/end-to-end/cases/expected/schematron/pending_schematron-result.xml, test/end-to-end/cases/expected/schematron/schematron-023-result.html, test/end-to-end/cases/expected/schematron/schematron-023-result.xml, test/end-to-end/cases/expected/schematron/schematron-import_demo-02-PhaseB-result.xml, test/end-to-end/cases/expected/schematron/tvt_label_schematron-result.xml, test/end-to-end/cases/expected/schematron/xml-1-1_schematron-result.html, test/end-to-end/cases/expected/schematron/xml-1-1_schematron-result.xml, test/end-to-end/processor/html/_normalizer.xsl, test/end-to-end/processor/xml/_normalizer.xsl, test/generate-step3-wrapper_custom.xspec, test/generate-step3-wrapper_default.xspec
- Replace the built-in SchXslt v1.7.4 with v1.8.
- Disable `schxslt.compile.metadata` (schxslt/schxslt#206) so that we can simplify not only the test result report HTML but also the end-to-end test normalizers.
---
Although schxslt/schxslt@bba1f70e5f67e43cb4bf78111f5e59043b3b03ad is [tagged as v1.8](https://github.com/schxslt/schxslt/releases/tag/v1.8), I'm not sure if it's considered as an official release. That's why this pull request is still a draft.
=> feat(schematron): bump built-in SchXslt to v1.8.2

editors/oxygen/add-on/description/latest.xhtml, oxygen-addon.xml, pom.xml, xspec.xpr
This pull request increments the version numbers in `pom.xml` and `oxygen-addon.xml`, which makes the official stable release of `v2.2`. (technically `v2.2.4`, based on #940)
As for the file paths in `oxygen-addon.xml`, I used the last `master` SHA rather than the git tag `v2.2.4`, because we haven't had the actual tag yet and therefore cannot test it. I tested the Oxygen add-on on Oxygen 23.1 build 2021082307 using `https://github.com/AirQuick/xspec/raw/rel_2-2-4/oxygen-addon.xml`.
=> build: release v2.2.4

pom.xml
As per our [workflow](https://github.com/xspec/xspec/wiki/Release-Workflow), this pull request increases the version of the XSpec release and adds the snapshot suffix. 
As usual, this should be the first pull request to be merged into `master` in order to start the development of XSpec v2.3.
=> build(maven): bump pom.xml to 2.3-SNAPSHOT

lib/schxslt/1.0/version.xsl, lib/schxslt/2.0/compile/compile-2.0.xsl, lib/schxslt/2.0/version.xsl
Replace the built-in SchXslt v1.8.2 with v1.8.4[^1].
[^1]: v1.8.3 should be skipped. It was an erroneous release.
=> feat(schematron): bump built-in SchXslt to v1.8.4

test/ci/run-shellcheck.sh
Just exclude `/node_modules/` directory from `shellcheck` (executed by `.github/workflows/lint.yml`).
=> test: exclude /node_modules/ from shellcheck

bin/xspec.sh, test/win-bats/collection.xml, test/xspec.bats
Using `$(dirname "$0")` is not a safe way to get the location of a running script. 
For example, if you run:
```
cd ~/xspec/bin
./xspec.sh -h
```
the value of `XSPEC_HOME` will be `.`. Not what you want. More reliable to `cd && pwd`
=> fix(cli): properly detect XSPEC_HOME

lib/schxslt/1.0/expand.xsl, lib/schxslt/1.0/version.xsl, lib/schxslt/2.0/compile/compile-2.0.xsl, lib/schxslt/2.0/compile/templates.xsl, lib/schxslt/2.0/svrl.xsl, lib/schxslt/2.0/version.xsl, lib/schxslt/README.md
Replace the built-in SchXslt v1.8.4 with v1.8.5.
=> feat(schematron): bump built-in SchXslt to v1.8.5

test/ci/env/global.env
This pull request just updates the Apache Log4j (for XML Calabash 1.3.2+) version used for testing.
=> ci(deps): bump Log4j from 2.14.1 to 2.15.0

test/ci/env/global.env
> VERSION 9.6.4 (December 17, 2021) --------------------------------------
> 
>  - Performance tweaks, minor fixes
=> ci(deps): bump BaseX from 9.6.3 to 9.6.4

test/ci/env/global.env
This pull request just updates the Apache Log4j (for XML Calabash 1.3.2+) version used for testing.
=> ci(deps): bump Log4j from 2.17.0 to 2.17.1

lib/schxslt/1.0/compile-for-svrl.xsl, lib/schxslt/1.0/expand.xsl, lib/schxslt/1.0/version.xsl, lib/schxslt/2.0/svrl.xsl, lib/schxslt/2.0/version.xsl, test/end-to-end/cases/expected/schematron/focus-vs-pending_schematron-result.html, test/end-to-end/cases/expected/schematron/focus-vs-pending_schematron-result.xml, test/end-to-end/cases/expected/schematron/pending_schematron-result.html, test/end-to-end/cases/expected/schematron/pending_schematron-result.xml, test/end-to-end/cases/expected/schematron/schematron-import_demo-02-PhaseB-result.xml
Replace the built-in SchXslt v1.8.5 with v1.8.6.
=> feat(schematron): bump built-in SchXslt to v1.8.6

bin/xspec.sh
Detect [MSYS](https://www.msys2.org/) usage, in addition to cygwin, for Java classpath separators.
MSYS2 is pre-installed on Windows Github Action environments and is generally a lighter-weight alternative to cygwin.
For reference, the output of `uname` with MSYS looks like this:
```
$ uname
MSYS_NT-10.0-14393
```
=> fix(cli): support MSYS2 on Windows

.codespellrc
Skip package-lock.json to avoid false positives
Part of "integrity" property value can look like an incorrectly
spelled word, but it is not meant as a word.
This change is motivated by the spell checking failure mentioned in https://github.com/xspec/xspec/pull/1640#issuecomment-1172408885.
Without this change, manually added `vew` to the end of one of the integrity values in `package-lock.json` and checked that codespell found it.
```
C:\github\xspec>test\ci\run-codespell.cmd
C:\github\xspec>echo Install codespell
Install codespell
C:\github\xspec>pip3 install     --disable-pip-version-check     --requirement requirements-dev.txt
Requirement already satisfied: codespell==2.1.0 in C:\[...]\lib\site-packages (from -r requirements-dev.txt (line 1)) (2.1.0)
C:\github\xspec>echo Run codespell …
```
=> ci: skip codespell package-lock.json file

test/rnc.bats, test/xspec.bats
The site now uses shfmt v3.5.1 instead of v3.3.1 and some
syntax rules have changed. This commit makes the .bats
files compliant with the shfmt v3.5.1 rules.
=> ci: make bats files compliant with shfmt v3.5.1 formatting

assembly/enduser-files.xml
We use [Maven Assembly Plugin 3.4.2](https://github.com/xspec/xspec/blob/a104cb1ef403881ff38c8821963a6c3dca0fbb3b/pom.xml#L172-L173) as of now and for that version, its schema should be 2.2.1:
https://maven.apache.org/plugins/maven-assembly-plugin/#assembly-and-component-descriptor-schemas-xsd
> Assembly and Component Descriptor Schemas (XSD)
> https://maven.apache.org/xsd/assembly-2.1.1.xsd, https://maven.apache.org/xsd/assembly-component-2.1.1.xsd (for version 3.4.0 and higher)
I verified that with this change, Oxygen 24.1 was able to perform validation.
=> build(maven): bump Maven Assembly Plugin XSD from 2.0.0 to 2.1.1

.github/workflows/test.yml, azure-pipelines.yml, test/ci/uninstall-bats-macos.sh
https://github.com/actions/runner-images/issues/4060#issuecomment-1023546603
> The migration is completed — all the jobs on `macos-latest` now run on `macos-11`.
And `macos-11` doesn't seem to have Bats. We no longer have to uninstall it.
I guess that's also the case on Azure Pipelines.
=> ci: no need to check and uninstall stale Bats on macOS 11 image

lib/schxslt/1.0/compile-for-svrl.xsl, lib/schxslt/1.0/compile/compile-1.0.xsl, lib/schxslt/1.0/expand.xsl, lib/schxslt/1.0/version.xsl, lib/schxslt/2.0/compile/compile-2.0.xsl, lib/schxslt/2.0/expand.xsl, lib/schxslt/2.0/svrl.xsl, lib/schxslt/2.0/version.xsl
Replace the built-in SchXslt v1.8.6 with v1.9.3.
=> feat(schematron): bump built-in SchXslt to v1.9.3

lib/schxslt/1.0/version.xsl, lib/schxslt/2.0/svrl.xsl, lib/schxslt/2.0/version.xsl
Replace the built-in SchXslt v1.9.3 with v1.9.4.
=> feat(schematron): bump built-in SchXslt to v1.9.4

xspec.framework
This pull request adds some `.jar` files to `xspec.framework` so that the Ant transformation scenarios for XSpec work on Oxygen 24.1.
This change is based on https://github.com/xspec/oXygen-XML-editor-xspec-support/commit/b9cf8cf3f74bbe3e9645416e82006b6a3c1840b2 and https://github.com/xspec/oXygen-XML-editor-xspec-support/commit/51b6e219574173ec2fbce8f4fa3573aa8be72037.
With this change, I verified that the **Run XSpec Test** transformation scenario worked on Oxygen 24.1 build 2022092207.
Note that the **XSLT Code Coverate** transformation scenario does not work correctly on Oxygen 24.1, as the code coverage feature doesn't support Saxon 10. Supporting the code coverage on Saxon 10 has been blocked by [a Saxon bug](https://saxonica.plan.io/issues/5112). The bug seems to be fixed on Saxon …
=> feat(oxygen): add library jar files for Oxygen 24.1

.github/workflows/lint.yml, package-lock.json, test/ci/npm-ci.sh
`npm` v9.0.0 has [removed](https://github.blog/changelog/2022-10-24-npm-v9-0-0-released/#:~:text=npm%20bin%20has%20been%20removed) `npm bin` command. This pr replaces it with `npm prefix` + the hardcoded (but [documented](https://docs.npmjs.com/cli/v9/configuring-npm/folders?v=true#:~:text=When%20in%20local%20mode%2C%20executables%20are%20linked%20into%20./node_modules/.bin)) suffix. (f954707df060715c524f376fdae1749f4b83d4c5)
While working on it, I noticed:
- `package-lock.json` old version warning. 67bd218a943f5221323facbe19dec8dacd424c78 fixes it.
- `npm ci` was performed for `shellcheck`, which should be unnecessary. 4c1b6650912d20771c6f3a8496b0bc8806f748de removes it.
=> ci: adapt to npm v9

test/bats-helper.bash
This pr addresses `BW02` warnings from Bats:
https://github.com/xspec/xspec/actions/runs/4262150688/jobs/7417307594#step:3:28
> BW02: Using flags on `run` requires at least BATS_VERSION=1.5.0. Use `bats_require_minimum_version 1.5.0` to fix this message.`
Details are in https://bats-core.readthedocs.io/en/stable/warnings/BW02.html
=> test: bats_require_minimum_version 1.5.0

lib/schxslt/1.0/version.xsl, lib/schxslt/2.0/compile/compile-2.0.xsl, lib/schxslt/2.0/version.xsl
Replace the built-in SchXslt v1.9.4 with v1.9.5, using download from https://github.com/schxslt/schxslt/releases/download/v1.9.5/schxslt-1.9.5-xslt-only.zip
=> feat(schematron): bump built-in SchXslt to v1.9.5

xspec.framework
This pull request adds some .jar files to xspec.framework so that the Ant transformation scenarios for XSpec work with Oxygen 25.1.
This change is based on https://github.com/xspec/oXygen-XML-editor-xspec-support/commit/cb9e3844feb8d39b3d17ef4351dd512c6bda3f04 and https://github.com/xspec/oXygen-XML-editor-xspec-support/commit/f619afaa4e69cc880b55a1b7de89add9d9fd9b7d .
With this change, I verified that the **Run XSpec Test** transformation scenario worked on Oxygen 25.1 build 2023031510.
About the the **XSLT Code Coverage** transformation scenario: Despite the fixes mentioned in #852, Oxygen 25.1 using Saxon 11.4 still shows the same symptom as in #1705. The sample file I used was `test/end-to-end/cases/custom-coverage-report.xspec`. I haven't looked into whether the Saxon fixes might be …
=> feat(oxygen): add library jar files for Oxygen 25.1

src/schematron/step3.xsl, test/issue-1618.xspec, test/issue-1618_step3.xsl
As mentioned in https://github.com/xspec/xspec/issues/1618#issuecomment-1257168030 and https://github.com/xspec/xspec/issues/1618#issuecomment-1257185678, #1618 is just one of many bugs in the *skeleton* implementation. Fixing them is beyond the scope of XSpec.
That being said, testing #1618 is still beneficial as it ensures that XSpec can handle curly brackets in `sch:assert/@test`. This pull request enables the fix #1626 only when testing `test/issue-1618.xspec`.
=> refactor(schematron): override skeleton impl for testing purposes only

.github/workflows/maven-deploy.yml, .github/workflows/test.yml
GitHub Actions workflow currently employs the Azul Zulu distribution of Java with no strong reason, as stated in its [commit comment](https://github.com/xspec/xspec/pull/1466/commits/fd3392ef2f45963503ac8f4ec1e1a27ea5f10a27).
This pull request replaces it with the Eclipse Temurin distribution which comes bundled with Oxygen 25+ and therefore offers a more suitable alternative.
=> ci: use Eclipse Temurin distribution

.github/workflows/test.yml, azure-pipelines.yml, test/ci/azure-pipelines_windows.yml, test/ci/compile-java.cmd, test/ci/compile-java.sh
This pull request replaces Java 11 with Java 17 in the test matrix of GitHub Actions and Azure Pipelines.
While working on this, I noticed `cleanDestinationDirectory` was no longer necessary. (Probably fixed by microsoft/azure-pipelines-tasks#13657.) 60b46b0fa349931443afb8c5354ae5b66683d583 removes it.
The latest version of Java LTS is 17.
Also, Oxygen 24+ is shipped with 17.
Update [Wiki](https://github.com/xspec/xspec/wiki/Requirements#java).
=> ci: test with Java 17

appveyor.yml, azure-pipelines.yml, test/ci/set-env.cmd, test/ci/set-env.sh
Now that XSpec warns that Saxon 9.9 is not recommended, the default should be a newer version of Saxon.
This update should have been part of https://github.com/xspec/xspec/pull/1652, but I wasn't familiar with this bit of code at the time.
=> test: default to Saxon 10, not Saxon 9

test/ci/print-env.cmd, test/ci/print-env.sh, test/win-bats/collection.xml, test/xspec.bats
Despite the changes made in #1730, the BaseX server test encountered an intermittent [failure](https://github.com/xspec/xspec/actions/runs/4950109318/jobs/8853269124#step:5:659).
Looking back its log, it was found that `basexhttpstop.bat` [failed](https://github.com/xspec/xspec/actions/runs/4950109318/jobs/8853269124#step:5:130) to stop the server long before initiating the entire test suite. This probably caused the subsequent test to fail, as the server was still running.
To mitigate this issue, this PR
- adds a 5-second delay before connecting to the server
- stops the server (as a precautionary measure), before starting it for test
=> test(basex): start and stop BaseX server more safely

src/schematron/schut-to-xslt.xsl
`src/schematron/schut-to-xslt.xsl` fails to obtain the Step 3 XSLT URI, when the Step 3 XSLT document is provided by the `+` command line parameter. (probably related to https://saxonica.plan.io/issues/4837)
This pr fixes it.
=> fix(schematron): construct $STEP3-PREPROCESSOR-URI using base-uri()

test/ci/env/oxygen.env, test/ci/env/saxon-10.env, test/ci/env/saxon-11.env, test/ci/env/saxon-9-9.env, test/win-bats/collection.xml, test/xspec.bats
With #1739, `SAXON_DOCUMENT_URI_FIXED` is no longer necessary. This PR removes it and re-enables the skipped tests.
The failures of the skipped tests were not caused by the *skeleton* Schematron implementation. They were caused by a breaking change in Saxon 11 where `document-uri()` had stopped working with the `+` command line parameter.
=> test(schematron): remove SAXON_DOCUMENT_URI_FIXED

test/format-xspec-report-messaging.xsl, test/win-bats/collection.xml, test/xspec.bats
Since `test/format-xspec-report-messaging.xsl` is mentioned in https://github.com/xspec/xspec/pull/791#issuecomment-596095233, it would be nice if we could keep its original behavior.
=> test(report): expect any line num when testing custom HTML reporter CLI

test/saxon-custom-options/test.xspec, test/saxon-custom-options/ws-only-text-copy.xml
Just simplifies `test/saxon-custom-options/ws-only-text-copy.xml` using XInclude.
=> test: test RECOGNIZE_URI_QUERY_PARAMETERS using XInclude

src/common/uri-utils.xsl, test/ci/build_install-deps.xml, test/ci/env/global.env, test/ci/env/oxygen.env, test/ci/env/saxon-10.env, test/ci/env/saxon-11.env, test/ci/env/saxon-9-9.env, test/ci/print-env.cmd, test/ci/print-env.sh, test/ci/set-env.cmd, test/ci/set-env.sh, test/run-bats.cmd, test/run-bats.sh, test/schut-to-xslt.xspec, test/uri-utils.xspec, test/win-bats/collection.xml, test/win-bats/stub.cmd, test/xspec.bats
There are two implementations of XML resolver. Now it's unclear what "XML Resolver" is and what the catalog test facilities are dealing with.
This PR
- Calls the traditional Apache resolver "Apache XML Resolver"
- Calls the new xmlresolver.org resolver "XMLResolver.org XML Resolver"
- Renames the environment variables
- Consolidates two `invoking xspec using SAXON_HOME finds Saxon jar and XML Catalog Resolver jar` Bats tests into one
=> test: distinguish Apache XML Resolver from XMLResolver.org one

src/common/uri-utils.xsl, src/schematron/schut-to-xspec.xsl, test/catalog/01/example.dtd, test/uri-utils.xspec
This pull request removes unnecessary `@use-when` from `x:document-actual-uri()`.
The tests in `test/uri-utils.xspec` are revised so that they describe the expected behaviors more clearly.
=> refactor: redirect x:document-actual-uri() to x:base-uri()

src/compiler/base/util/compiler-pending-utils.xsl
To simplify `xsl:accumulator-rule` in `compiler-pending-utils.xsl`, this PR just replaces its enclosed sequence constructor with a `select` attribute.
=> refactor: simplify xsl:accumulator-rule for $stacked-explicit-pending

test/ci/env/global.env
In the following list of changes in v5.2.1, nothing jumped out at me as looking unsafe.
https://github.com/xmlresolver/xmlresolver/compare/5.2.0...5.2.1
- https://github.com/xmlresolver/xmlresolver/pull/151
- https://github.com/xmlresolver/xmlresolver/pull/152
=> ci(deps): bump XMLResolver.org XML Resolver version from 5.2.0 to 5.2.1

test/ci/env/saxon-11.env
This pull request just updates the Saxon 11 version used for testing.
=> ci(deps): bump Saxon from 11.5 to 11.6

test/schematron/schematron-01.xml
I came across a typo in an example file that supports a test.
=> test(schematron): fix typo in test example file

editors/oxygen/add-on/description/latest.xhtml, oxygen-addon.xml, xspec.xpr
The [changelog](https://htmlpreview.github.io/?https://github.com/AirQuick/xspec/blob/a0163a9c8184d742fdf92d1b50fbf1f5bffe45b0/editors/oxygen/add-on/description/latest.xhtml) denotes this version as "Release Candidate of the stable release".
I tested this change on Oxygen 25.1 build 2023070306 and 24.1 build 2022110312 using `https://github.com/AirQuick/xspec/raw/oxy-addon_2-3-1/oxygen-addon.xml`:
- All the 4 transformation scenarios work including **Run XSpec Test** with XSLT, XQuery and Schematron. (**XSLT Code Coverage** transformation scenario generates uselses reports (#852).)
- Loading `xspec.xpr` disables the add-on and enables its own framework.
XSpec's Ant transformation scenarios will not work on Oxygen …
=> build(oxygen): add-on v2.3.1

pom.xml
As per our [workflow](https://github.com/xspec/xspec/wiki/Release-Workflow), this pull request increases the version of the XSpec release and adds the snapshot suffix.
As usual, this should be the first pull request to be merged into `master` in order to start the development of XSpec v3.0.
=> build(maven): bump pom.xml to 3.0-SNAPSHOT

test/ci/env/global.env
Looks like this version is merely a submodule update (the standard DTDs and schemas that ship with the resolver).
=> ci(deps): bump XMLResolver.org XML Resolver from 5.2.1 to 5.2.2

test/schematron-019.xspec
This pull request merely fixes a typo in a scenario label. This is the only instance of this particular typo that I found.
=> test(schematron): fix typo 'Schematrion' in scenario label

editors/oxygen/add-on/description/latest.xhtml, oxygen-addon.xml, xspec.xpr
I tested this change on Oxygen 26.0 build 2023100905 using `https://github.com/AirQuick/xspec/raw/oxy-addon_3-0-0/oxygen-addon.xml`:
- All the 4 transformation scenarios work including **Run XSpec Test** with XSLT, XQuery and Schematron. (**XSLT Code Coverage** transformation scenario generates useless reports (#852).)
- **Schematron Unit Test** and **XQuery Unit Test** templates are available in **File** - **New** dialog.
- Loading `xspec.xpr` disables the add-on and enables its own framework.
=> build(oxygen): add-on v3.0.0

src/compiler/base/invoke-compiled/threads.xsl
This pull request fixes an instance of the typo "XLST" in a code comment.
There are a few [other instances](https://github.com/search?q=repo%3Axspec%2Fxspec+xlst&type=code) of the same typo in this repo, but they are under `lib/` where I think the policy is not to change those files. If you do want me to fix the typos there, let me know.
I considered whether the codespell project should have XLST in its list of typos, which would help us detect new instances of XLST in this repo. However, that acronym apparently is not a typo when it has the following meaning: https://whatext.com/xlst
=> fix: typo in code comment (XLST)

src/schematron/generate-step3-wrapper.xsl, test/generate-step3-wrapper_custom.xspec, test/generate-step3-wrapper_default.xspec, test/schematron-global-xspec-uri.xspec
While working on tests for #1771, I got an error when a test for Schematron referenced `$x:xspec-uri` in a global XSpec variable (`/x:description/x:variable`).
```
[xslt] Loading stylesheet C:\...\src\schematron\schut-to-xslt.xsl
[xslt] C:\...\src\compiler\xslt\declare-variable\declare-variable.xsl: Fatal Error! Variable $x:xspec-uri has not been declared (or its declaration is not in scope)
[xslt] Fatal error during transformation using C:\...\src\schematron\schut-to-xslt.xsl: Variable $x:xspec-uri has not been declared (or its declaration is not in scope); SystemID: file:/C:/.../src/compiler/xslt/declare-variable/declare-variable.xsl; Line#: -1; Column#: -1
```
The file `test/schematron-global-xspec-uri.xspec` reproduces the problem.
This fix provides the definition of `$x:xspec-uri` in …
=> fix(schematron): make wrapper define $x:xspec-uri

src/schemas/xspec.rnc
In `x:expect-*` elements that refer to the `common-schematron-assert-report-expect-attributes` RelaxNG pattern, the `id` <s>or `role`</s> attribute can match one in the grandparent pattern if neither the original element nor its parent rule has such an attribute. Add mention of the pattern to the schema annotation.
I noticed a discrepancy between the schema doc (and wiki, which I can update after this PR is merged) and the software behavior. The behavior seems intentional, based on #149, which included "Extended the `@id` attribute matching to include the `@id` attribute on the Schematron pattern element." and made the following change affecting both `@id` and `@role`:
https://github.com/xspec/xspec/pull/149/files#diff-86c7b8ace6363b8f27bc79fdc83ee00461da0216a2c68c840a5f5913d225a54bL131-L1 …
=> docs(schema): inheritance of id from Schematron pattern

.commitlintrc.json, CONTRIBUTING.md, test/end-to-end/cases/expected/query/force-focus_none-junit.xml, test/end-to-end/cases/expected/query/force-focus_none-result.html, test/end-to-end/cases/expected/query/force-focus_none-result.xml, test/end-to-end/cases/expected/schematron/force-focus_none-junit.xml, test/end-to-end/cases/expected/schematron/force-focus_none-result.html, test/end-to-end/cases/expected/schematron/force-focus_none-result.xml, test/end-to-end/cases/expected/stylesheet/force-focus_none-junit.xml, test/end-to-end/cases/expected/stylesheet/force-focus_none-result.html, test/end-to-end/cases/expected/stylesheet/force-focus_none-result.xml, test/end-to-end/cases/focus-without-pending.xspec, test/end-to-end/cases/force-focus_none.xspec
Closes #1811
This PR adds another test for Ant property `xspec.force.focus`.
`#none` (case sensitive) should always invalidate `//x:scenario/@focus`.
(Given that the intricate feature of `xspec.force.focus` is only necessary for [Oxygen XSpec Helper View](https://github.com/xspec/oXygen-XML-editor-xspec-support), Wiki should mention only `#none`.)
=> feat(ant): xspec.force.focus=#none

test/tutorial_namespaces_query.xspec, test/tutorial_namespaces_stylesheet.xspec, tutorial/namespaces/namespace-demo.xqm, tutorial/namespaces/namespace-demo.xsl, tutorial/namespaces/namespace-demo_query.xspec, tutorial/namespaces/namespace-demo_stylesheet.xspec
#229 asks for enhancements in the wiki and tutorials to help XSpec users who are working with elements in namespaces.
There is already a set of tutorial files that illustrate namespace usage in XSpec tests for Schematron:
https://github.com/xspec/xspec/blob/master/tutorial/schematron/demo-04.xspec
This pull request adds tutorial files that show some options for referring to elements in namespaces in XSpec tests for XSLT and XQuery.
Follow-up:
=> docs: namespace demo files for XSLT and XQuery

.prettierrc.json, package-lock.json, package.json
This PR just adds [`prettier-plugin-properties` plugin](https://github.com/eemeli/prettier-plugin-properties) to Prettier, so that `*.properties` file style can be checked by GitHub Actions [`Lint` workflow](https://github.com/xspec/xspec/blob/ecad57a4f445dab36e3eba51b7036061f7a3f5c5/.github/workflows/lint.yml#L33-L41).
=> ci: check .properties style

src/schemas/xspec.rnc
`x:like` does not support text value templates, so it should not permit the `expand-text` attribute. This pull request removes the `expand-text` attribute from the `x:like` content model, leaving the rest of the content model unchanged.
Fixes #1836 using approach 3 under "Possible fixes".
I validated the `.rnc` file. I validated all the `.xspec` files under `test/` on this branch and the master branch, and there are no differences between the branches.   Then I modified one of the files by adding
```
<x:like expand-text="yes"><x:label>{blah}</x:label></x:like>
<x:like expand-text="yes" label="blah"/>
```
and I got the expected validation error for both lines:
```
error: attribute "expand-text" not allowed here; expected attribute "label" or an attribute from another namespace
```
=> fix(schema): remove expand-text from x:like content model

test/win-bats/collection.xml, test/xspec.bats
This PR toward the master branch just moves the code added in #1780 to a different spot in the file relative to the `Bad Schematron @location` section.
The schxslt automatic rebase wants to delete the `SVRL @location fails to select text node #396` test case within the `Bad Schematron @location` section. Keeping it at the same location of the file where it had been (before #1780) might avoid recurring merge conflicts during the rebase operation.
=> ci: move code to avoid conflict in schxslt rebase

src/schemas/xspec.rnc
- There is no XSpec element named "assertion". It should say "expect".
- The annotation about the mode attribute had extra verbiage unrelated to that attribute.
- End attribute description with period, for consistency with other attribute descriptions.
I confirmed in Oxygen that the tooltips for `x:context/@mode` and a few elements' `@expand-text` attributes reflect these fixes. I don't think the annotations that said `<assertion>` showed up as Oxygen tooltips in the first place.
=> docs(schema): schema doc corrections

test/external_global-context_stylesheet.xspec, test/external_x-context.xspec, test/external_x-context_schematron.xspec, test/x-context.xsl, test/x-context.xspec, test/x-context_schematron.xspec
This pull request adds more tests for `$x:context` to prepare for documenting this predefined variable as part of #1771.
The original design of `$x:context` in #1089 makes the variable available in `x:expect/(@select|@test)`. In fact, `$x:context` is usable in other situations, too, but not all. The pending test scenarios here are outside the scope of #1089. I'd like to make `$x:context` available even in scenarios that don't contain `x:expect` as a child. I will do that in a separate pull request.
=> test: test $x:context variable more, mainly in x:expect

src/schemas/xspec.rnc
This PR removes the `expand-text` attribute from the schema definitions of `<x:import>` and `<x:helper>` because these empty elements can't support text value templates. If any users have XSpec code that uses `expand-text` on these two elements 
(which I expect to be unlikely), the attribute has no effect and should be removed.
I validated the `.rnc` file. I validated all the `.xspec` files under `test/` and `tutorial/` on this branch and the master branch, and there are no differences between the branches. Then I modified one of the files temporarily by adding
```
<x:import expand-text="blah" href="test.xspec"/>
<x:helper expand-text="blah" stylesheet="blah.xsl"/>
```
and I got validation errors as expected:
```
error: attribute "expand-text" not allowed here; expected attribute "href" …
```
=> refactor(schema): remove expand-text from empty elements

package-lock.json, package.json
This PR bumps both `@commitlint/cli` and `@commitlint/config-angular` to the latest bug-fix version of major version 19.
It seems that v19 of these packages has some breaking changes, and maybe that's why #1869 and #1868 had errors,
```
/home/runner/work/xspec/xspec/node_modules/@commitlint/cli/lib/cli.js:123
throw err;
^
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/xspec/xspec/node_modules/@commitlint/config-angular/index.js from /home/runner/work/xspec/xspec/node_modules/@commitlint/resolve-extends/lib/index.js not supported.
Instead change the require of /home/runner/work/xspec/xspec/node_modules/@commitlint/config-angular/index.js in /home/runner/work/xspec/xspec/node_modules/@commitlint/resolve-extends/lib/index.js to a dynamic import() which is available in all …
```
=> ci(deps-dev): bump commitlint from 18.6.1 to 19.1.0

.github/workflows/maven-deploy.yml
Maven deployment broke when xspec repo bumped maven-gpg-plugin from 3.1.0 to 3.2.0 (#1874).
```
[INFO] Signer 'gpg' is signing 6 files
gpg: signing failed: No pinentry
gpg: signing failed: No pinentry
```
Runs that showed the same failure:
* https://github.com/xspec/xspec/actions/runs/8256289815
* https://github.com/xspec/xspec/actions/runs/8258185796
This change imitates the fix in another repo that had the "gpg: signing failed: No pinentry" error with that version of the plugin.
References:
* https://maven.apache.org/plugins-archives/maven-gpg-plugin-LATEST/examples/deploy-signed-artifacts.html#sign-using-bc-signer
* https://issues.apache.org/jira/projects/MGPG/issues/MGPG-90?filter=allopenissues (see comments in 3/2024)
* Example, https://github.com/xerial/sqlite-jdbc/pull/1082
=> build(maven): use BC signer, with maven-gpg-plugin 3.2.0

src/compiler/base/combine/mode/check-combined-doc.xsl, src/compiler/base/compile/compile-scenario.xsl, src/schemas/xspec.rnc, test/ant/worker/generate.xsl, test/call-disallowed/external_function-in-variable.xspec, test/function-in-variable.sch, test/function-in-variable.xqm, test/function-in-variable.xsl, test/function-in-variable.xspec, test/win-bats/collection.xml, test/xspec.bats
This PR adds support for `<x:call function="..." call-as="variable">` so that a scenario can test a function that is stored in an XSLT variable or XQuery variable. This design is like [AirQuick's suggestion](https://github.com/xspec/xspec/issues/1748#issuecomment-1849008579) except that the new attribute is named `call-as` instead of `type`. Thanks for the suggestion, @AirQuick !
If the `call-as` attribute is missing, the default value of `"module-function"` provides the usual `x:call[@function]` behavior.
- Not supported when the test has `x:description/@run-as="external"`. External transformations use the `transform` XPath function, and I believe that function's `'initial-function'` option must point to a module function rather than a variable.
- Requires Saxon 10 or later, or Saxon 9.9 …
=> feat: support calling XPath function defined in variable

editors/oxygen/add-on/description/latest.xhtml, oxygen-addon.xml, xspec.xpr
This v3.0.1 add-on has most of the changes we expect to be in XSpec v3.0, but it excludes the XSLT Code Coverage upgrade.
The next add-on version will include the XSLT Code Coverage upgrade. Creating separate add-on versions might make it easier for users to compare the old and new functionality.
I tested this change in Oxygen 26.0 build 2023100905 using `https://github.com/galtm/xspec/raw/oxygen-3.0.1/oxygen-addon.xml`. The transformation scenarios work, except that the XSLT Code Coverage scenario produces a mostly blank report that says "not used". This result is expected for this add-on because it doesn't include the changes from #1833.
=> build(oxygen): add-on v3.0.1

.github/workflows/test.yml, test/ci/azure-pipelines_windows.yml, test/ci/env/saxon-9-9.env
Following #1833, this pr removes Saxon 9.9 from GitHub Actions and Azure Pipelines, which means XSpec no longer supports Saxon 9.9.
After merging this, we can start deleting code specifically designed for Saxon 9.9.
=> ci: remove Saxon 9.9 from CI matrix

src/common/report-sequence.xqm, src/common/report-sequence.xsl, src/compiler/xslt/main.xsl, test/ant/build.xml, test/ant/worker/generate.xsl, test/catalog/01/imported-xspec-uri.xspec, test/ci/build_install-deps.xml, test/ci/set-env.cmd, test/ci/set-env.sh, test/end-to-end/cases/expected/query/issue-355-result.html, test/end-to-end/cases/expected/query/issue-355-result.xml, test/end-to-end/cases/expected/query/three-dots-result.xml, test/end-to-end/cases/issue-355.xspec, test/end-to-end/cases/issue-778_ws.xspec, test/external_xslt-package_arith_use-1.xspec, test/external_xslt-package_arith_use-2.xspec, test/external_xslt-package_filter_use.xspec, test/function-in-variable.xspec, test/issue-638.xspec, test/issue-700.xspec, test/report-sequence.xspec, test/report-sequence_stylesheet_hof.xspec, test/version-utils.xspec, test/win-bats/collection.xml, test/xspec-uri.xspec, test/xspec-uri_stylesheet.xspec, test/xspec.bats
This pull request removes Saxon 9.9 support from the code base, or at least the vestiges I'm aware of.
Related to #1834 and #1835.
Fixes #1826.
=> refactor: drop support for Saxon 9.9

editors/oxygen/add-on/description/latest.xhtml, oxygen-addon.xml, xspec.xpr
This v3.0.2 add-on has all the changes we expect to be in XSpec v3.0, including the XSLT Code Coverage upgrade.
I tested this change in Oxygen 26.1 build 2024031806 using https://github.com/galtm/xspec/raw/oxygen-3.0.2/oxygen-addon.xml. All the transformation scenarios work. Note that Oxygen 26.1 uses Saxon 12.3. Under 12.3, the XSLT Code Coverage scenario produces a report with some content (not merely "not used") but the console says Saxon 12.3 is not recommended.
---
\* Unless you're using a special add-on that accesses Saxon 12.4 (https://www.oxygenxml.com/doc/versions/26.1/ug-editor/topics/saxon-transformer-addon.html)
=> build(oxygen): add-on v3.0.2

pom.xml
The Maven repository uses a three-part version number, so use 3.0.3 instead of 3.0.
This pull request fixes a mistake I made in #1904.
=> build(maven): use 3.0.3 in pom.xml, not 3.0

pom.xml
As per our [workflow](https://github.com/xspec/xspec/wiki/Release-Workflow), this pull request increases the version of the XSpec release and adds the snapshot suffix.
As usual, this should be the first pull request to be merged into `master` in order to start the development of XSpec v3.1.
=> build(maven): bump pom.xml to 3.1-SNAPSHOT

appveyor.yml
AppVeyor has been fairly consistently timing out upon reaching 60-minute time limit. This PR implements idea "A" in #1900.
@xspec/xspec : I'm still open to alternate suggestions, but I'd like to get this repo fairly soon to a state where AppVeyor completes successfully most of the time.
Closes #1900 .
=> ci: make AppVeyor testing include bats only

README.md
The XSpec discussion list has had no user input in more than a year, and I don't think anyone on the XSpec team is monitoring the list. For support requests, I think we should point users only to GitHub.
cc'ing @xspec/xspec in case anyone has a different perspective.
=> docs: point only to GitHub for support requests

.github/workflows/test.yml
Temurin distribution is not available for Java 8 with macos-14 on M1.
This pull request changes as little as possible in the test environments, so macOS with Java 8 uses Liberica and everything else (including macOS with Java 17) uses Temurin.
Fixes #1919.
---
When the GitHub Actions ran in my own fork, I checked the **Run actions/setup-java@v4** > **Installed distributions** section of the [test logs](https://github.com/galtm/xspec/actions/runs/8884405147) for all the Saxon 12 runs. They all say `Distribution: temurin` except that the `macos-latest, 8, saxon-12` run says `Distribution: liberica`.
The full macOS/Java8/Saxon12 installation log says:
```
Trying to resolve the latest version from remote
Resolved latest version as 8.0.412+9
Trying to download...
Downloading Java 8.0.412+9 …
```
=> ci: on macOS with Java 8, use liberica instead of temurin

test/xmlns.sch, test/xmlns_schematron.xspec
The `location` attribute of Schematron `x:expect-*` elements holds an XPath expression. The expression can use element names with namespace prefixes that have been declared in the XSpec file. Also, when the Schematron schema declares prefixes for the same element names, those prefixes are allowed to differ from the prefixes used in XSpec.
This pull request enhances an existing test to demonstrate use of namespace prefixes in `@location` and different prefixes between Schematron and XSpec. I skimmed through the comments in #640, which introduced this test, and I didn't see anything that suggested these aspects were omitted deliberately.
=> test(schematron): test prefix usage in location attribute

test/global-override.xspec
This pull request merely fixes two labels that use the wrong word. The `run-as` attribute value other than `import` is `external`, not `export`.
=> test: fix typo in label (export -> external)

test/end-to-end/cases-coverage/expected/stylesheet/xsl-param-01-coverage.html, test/end-to-end/cases-coverage/expected/stylesheet/xsl-param-01-coverage.xml, test/end-to-end/cases-coverage/xsl-param-01.xsl, test/end-to-end/cases-coverage/xsl-param-01.xspec
This pull request is to shepherd some test updates from @birdya22 (attached to #1935 and explained there) through GitHub.
I reviewed the .xsl and .xspec files, and the only change I made was a typo fix in a code comment.
I regenerated expected result files in the usual way: from `test\end-to-end`, I ran `generate-expected.cmd -Dcases.dir=cases-coverage`. (The so-called expected results reflect some flaws in the underlying code coverage feature, not bugs in the test files in this PR. For more information, see the `## xsl:param` section in https://github.com/xspec/xspec/pull/1934/files .)
Adrian, thank you for your continued contributions to XSpec!
---
Fixes #1935.
=> test(report): additional coverage test cases for xsl:param

docs/xslt-code-coverage-by-element.md
This pull request adds documentation for XSLT code coverage reporting at a per-element level for most XSLT elements. The main reason it is a repo file rather than a wiki page is so that it can be in the same pull request with code changes (and we anticipate code changes in the code coverage functionality the near future).
Adrian Bird (@birdya22 in GitHub) wrote the document that I committed in c67c0ec4b2119e21cf753931d8a3550535795285; see https://github.com/xspec/xspec/issues/1921#issuecomment-2162786270.
I made some editorial tweaks in 017160c724677f80efa2f4d26863cba2cd7d5122 and then added mention of the Saxon version in 63a2710bff920b5654401837ad6770aa4b5a88ed. Adrian, please let me know if my modifications inadvertently changed the underlying meaning. Feel free to ask me to revert any …
=> docs: code coverage behavior by element

docs/xslt-code-coverage-by-element.md, test/end-to-end/cases-coverage/expected/stylesheet/xsl-map-01-coverage.html, test/end-to-end/cases-coverage/expected/stylesheet/xsl-map-01-coverage.xml, test/end-to-end/cases-coverage/xsl-map-01.xsl, test/end-to-end/cases-coverage/xsl-map-01.xspec
This pull request is to shepherd some test updates from @birdya22 (attached to #1953 and explained there) through GitHub. Thank you, Adrian!
I reviewed the .xsl and .xspec files, making no changes.
I regenerated expected result files in the usual way: from `test\end-to-end`, I ran `generate-expected.cmd -Dcases.dir=cases-coverage`.
Fixes #1953. (I think we should have a separate issue in GitHub to discuss what the coverage logic for the map-related elements should be, and restrict #1953 to the test enhancement.)
=> test(report): additional coverage test cases for xsl:map

src/schemas/xspec.rnc, src/schemas/xspec.sch, test/tvt.xspec, test/tvt/detect-expand-text-user-content-xslt.xspec, test/xspec-sch.xspec
**Background**: To control text value templates in XSpec from a user content element, `x:expand-text` is the correct attribute to use and it has an enumerated set of Boolean values. On a user content element, the `expand-text` attribute has no effect on text value templates in XSpec.
This pull request enhances the RelaxNG and Schematron schemas for XSpec to help users set these attributes correctly in user content.
1. RelaxNG enforces the Boolean values for `x:expand-text`. Without this change, an incorrect value leads to a fatal compiler error when you run the test, but the error message doesn't have a user perspective and doesn't say where the problem is in the user's file: 
```
...\xspec\src\common\yes-no-utils.xsl:16:0: Fatal Error! Conditional expression: None of the conditions is …
```
=> feat(schema): constrain x:expand-text and help users fix expand-text

test/end-to-end/cases-coverage/expected/stylesheet/xsl-element-01-coverage.html, test/end-to-end/cases-coverage/expected/stylesheet/xsl-element-01-coverage.xml, test/end-to-end/cases-coverage/xsl-element-01.xsl, test/end-to-end/cases-coverage/xsl-element-01.xspec
This pull request is to shepherd some test updates from @birdya22 (attached to #1964 and explained there) through GitHub. Thanks, Adrian!
I reviewed the .xsl and .xspec files, making no changes other than tweaking code comments.
I regenerated expected result files in the usual way: from `test\end-to-end`, I ran `generate-expected.cmd -Dcases.dir=cases-coverage`.
Fixes #1964.
=> test(report): additional coverage test cases for xsl:element

src/reporter/coverage-compute-status.xsl, src/reporter/coverage-report.xsl
This pull request refactors the XSLT code that computes code coverage status based on the trace data produced by the Java trace listener. The goal is to make rules like "use trace data", "use child data", "use parent data", or element-specific logic more apparent and easier to maintain.
Between now and the next XSpec release, we plan to change some of the logic in this XSLT code in ways that will change the expected coverage reports. This pull request excludes any such changes -- even bug fixes. In other words, this pull request is pure refactoring.
=> refactor(report): simplify XSLT computation of code coverage status

src/reporter/coverage-compute-status.xsl, src/reporter/coverage-report.xsl, test/end-to-end/cases-coverage/expected/stylesheet/xsl-for-each-group-01-coverage.html, test/end-to-end/cases-coverage/expected/stylesheet/xsl-for-each-group-01-coverage.xml, test/end-to-end/cases-coverage/expected/stylesheet/xsl-map-01-coverage.html, test/end-to-end/cases-coverage/xsl-for-each-group-01.xsl, test/end-to-end/cases-coverage/xsl-for-each-group-01.xspec
The commits dated "Jul 9, 2024" are merely a repeat of the commits from #1966 because I wanted to build upon that refactoring.
This pull request fixes a bug and non-conformance issue for `xsl:for-each` and `xsl:for-each-group`.
- 1c9ce4732fa7a58e2307f2d1ad8e3bfb21969716 adds a test case showing that #1950 is a bug.
- 5986c78337e8287d9ceaee5b6f3ec7693a718d53 fixes the coverage reporting XSLT code. When `xsl:for-each` and `xsl:for-each-group` no longer match the template that implements the "Use Child Data" rule, the trace hits on these elements take effect.
- 77b20a191a7eb103af66b8761bfadb965958ba97 reflects the bug fixes in two tests.
---
Fixes #1949
Fixes #1950
=> fix(report): coverage for xsl:for-each and xsl:for-each-group

src/reporter/coverage-compute-status.xsl, src/reporter/coverage-report.xsl, test/end-to-end/cases-coverage/expected/stylesheet/xsl-param-01-coverage.html
The commits dated "Jul 9, 2024" are merely a repeat of the commits from #1966 because I wanted to build upon that refactoring.
This pull request fixes the logic for children of `xsl:stylesheet` and `xsl:transform`.
- 4fd8cfda285545b40399b737259683dfd44527ba: If the child element is not in the XSLT namespace, the element and all its descendant nodes should be ignored
- d4c795d396b59aa960c58886759c12294b3cc6ae : If the child element is in the XSLT namespace _and_ is a declaration that's supposed to use the "Always Ignore" rule, then ignore it.
- Some XSLT-namespace children of `xsl:stylesheet` and `xsl:transform` are not ignored, such as `xsl:param`, `xsl:template`, and `xsl:function`. 9c94c573147675c2cbcde7091fe3ce44d6f7c14f shows a case where this change fixes a bug.
---
Cc: @birdya22
=> fix(report): coverage for top-level elements in stylesheet

docs/xslt-code-coverage-by-element.md, src/reporter/coverage-compute-status.xsl, test/end-to-end/cases-coverage/expected/stylesheet/xsl-accumulator-01-coverage.html, test/end-to-end/cases-coverage/expected/stylesheet/xsl-attribute-01-coverage.html, test/end-to-end/cases-coverage/expected/stylesheet/xsl-attribute-set-01-coverage.html
This pull request implements the XSLT code coverage status rule "Ignore Element and All Descendants". This rule is needed for the `xsl:accumulator-rule` element and for the  `xsl:attribute` element when it is a child of `xsl:attribute-set`.
I checked that the changes in results of end-to-end coverage tests are the same changes mentioned in #1939 and #1941.
Fixes #1939
Fixes #1941
---
Cc: @birdya22
=> fix(report): coverage rule "Ignore Element and All Descendants"

docs/xslt-code-coverage-by-element.md, src/reporter/coverage-compute-status.xsl, test/end-to-end/cases-coverage/expected/stylesheet/xsl-merge-01-coverage.html, test/end-to-end/cases-coverage/xsl-merge-01.xsl
Fixes #1959.
Note: In the expected coverage report, line 26 has a CSS class of "unknown". That's correct, though it won't render distinctively because there is no style for that class yet in this repo's `master` branch. #1974 adds a CSS style for the "unknown" class.
---
Cc: @birdya22
=> fix(report): coverage updates for xsl:merge and descendants

src/reporter/coverage-compute-status.xsl, test/end-to-end/cases-coverage/expected/stylesheet/xsl-analyze-string-01-coverage.html, test/end-to-end/cases-coverage/expected/stylesheet/xsl-choose-01-coverage.html, test/end-to-end/cases-coverage/expected/stylesheet/xsl-fallback-01-coverage.html, test/end-to-end/cases-coverage/expected/stylesheet/xsl-iterate-01-coverage.html, test/end-to-end/cases-coverage/expected/stylesheet/xsl-where-populated-01-coverage.html, test/end-to-end/cases-coverage/expected/stylesheet/xsl-where-populated-01-coverage.xml, test/end-to-end/cases-coverage/xsl-where-populated-01.xsl, test/end-to-end/cases-coverage/xsl-where-populated-01.xspec
This pull request makes `xsl:where-populated` follow the Use Child Data rule and adds test cases for the "unknown" status that can result from that rule.
Note: This pull request does not include the changes in the open pull request #1978. Eventually, everything will get merged together, but I didn't want to make this simpler pull request depend on that more complicated one.
Fixes #1946.
---
Cc: @birdya22
=> fix(report): coverage update for xsl:where-populated

docs/xslt-code-coverage-by-element.md, src/reporter/coverage-compute-status.xsl, test/end-to-end/cases-coverage/expected/stylesheet/xsl-assert-01-coverage.html, test/end-to-end/cases-coverage/expected/stylesheet/xsl-assert-01-coverage.xml, test/end-to-end/cases-coverage/expected/stylesheet/xsl-where-populated-01-coverage.html, test/end-to-end/cases-coverage/expected/stylesheet/xsl-where-populated-01-coverage.xml, test/end-to-end/cases-coverage/xsl-assert-01.xsl, test/end-to-end/cases-coverage/xsl-assert-01.xspec, test/end-to-end/cases-coverage/xsl-where-populated-01.xsl, test/end-to-end/cases-coverage/xsl-where-populated-01.xspec
- f2438cdba6fc11fcd9350af9183c728ee378eeaa adds test cases that reproduce #1980
- 90a1f71b5c197b56cb9a82982258aa2767686dfe fixes #1980
- ce2521974eca50d18bb7ab16b64b80c9e20f7fc9 updates the `xslt-code-coverage-by-element.md` file to reflect the fixed logic, and also changes the name of the rule to **Use Descendant Data**
---
Cc: @birdya22
=> fix(report): fix Use Child Data rule and rename as Use Descendant Data

test/ci/env/global.env
Release notes:
https://github.com/xmlresolver/xmlresolver/releases/tag/5.2.4
=> ci(deps): bump XMLResolver.org XML Resolver from 5.2.3 to 5.2.4

lib/schxslt/1.0/compile-for-svrl.xsl, lib/schxslt/1.0/compile/compile-1.0.xsl, lib/schxslt/1.0/expand.xsl, lib/schxslt/1.0/include.xsl, lib/schxslt/1.0/version.xsl, lib/schxslt/2.0/compile/compile-2.0.xsl, lib/schxslt/2.0/compile/functions.xsl, lib/schxslt/2.0/expand.xsl, lib/schxslt/2.0/include.xsl, lib/schxslt/2.0/pipeline.xsl, lib/schxslt/2.0/svrl.xsl, lib/schxslt/2.0/version.xsl, lib/schxslt/README.md, test/do-nothing.sch, test/schematron/schematron-019.sch
Replace the built-in SchXslt v1.9.5 with v1.10, using download from
https://github.com/schxslt/schxslt/releases/download/v1.10/schxslt-1.10-xslt-only.zip
Seeing an item in the release notes about empty patterns (https://github.com/schxslt/schxslt/issues/341), I wondered if we could remove the dummy rules that exist in two Schematron schemas in our test suite. ada97f391cce4316267151680d18c5d4d696e18a does that. Note: Those files still need the dummy _pattern_, though, to avoid a hard error when running the XSpec test suite.
=> feat(schematron): bump built-in SchXslt to v1.10

src/schemas/xspec.rnc, test/multiple-filtered-items.xspec, test/multiple-filtered-items_schematron.xspec
The schema annotation for `x:expect` said that when `@test` is used for filtering, it returns an item -- which suggests exactly one item. The wiki section https://github.com/xspec/xspec/wiki/Writing-Scenarios#describing-the-expected-result-and-filtering-the-actual-result doesn't mention multiplicity and its examples use one item per `<x:expect>` element.
However, it is fine if a non-Boolean `@test` returns zero items or multiple items. Tests for issue #59 exercise the multiple-item capability in the scenarios labeled "Multiple nodes", "Multiple values", and "Nodes and value".
- https://github.com/xspec/xspec/blob/e9d4527f200e776b84953230bef7280dc8488cef/test/issue-59_query.xspec
- https://github.com/xspec/xspec/blob/e9d4527f200e776b84953230bef7280dc8488cef/test/issue-59_stylesheet.xspec …
=> test: filtered result not limited to one item

docs/xslt-code-coverage-by-element.md, src/reporter/coverage-compute-status.xsl, test/end-to-end/cases-coverage/expected/stylesheet/non-xsl-top-level-element-01-coverage.html, test/end-to-end/cases-coverage/expected/stylesheet/xsl-accumulator-01-coverage.html, test/end-to-end/cases-coverage/expected/stylesheet/xsl-accumulator-01-coverage.xml, test/end-to-end/cases-coverage/expected/stylesheet/xsl-assert-01-coverage.html, test/end-to-end/cases-coverage/non-xsl-top-level-element-01.xsl, test/end-to-end/cases-coverage/non-xsl-top-level-element-01A.xsl, test/end-to-end/cases-coverage/xsl-accumulator-01.xsl, test/end-to-end/cases-coverage/xsl-assert-01.xsl
This pull request marks xsl:assert and all its descendants as "unknown" except where certain higher-priority templates apply. This pull request also adds some test cases that illustrate the xsl:assert rule being lower priority than another template.
Note: This pull request does not include the changes in the open pull request https://github.com/xspec/xspec/pull/1978.
Fixes https://github.com/xspec/xspec/issues/1940.
---
Cc: @birdya22
=> fix(report): coverage update for xsl:assert

docs/xslt-code-coverage-by-element.md, src/reporter/coverage-compute-status.xsl, test/end-to-end/cases-coverage/expected/stylesheet/xsl-analyze-string-01-coverage.html, test/end-to-end/cases-coverage/expected/stylesheet/xsl-evaluate-01-coverage.html, test/end-to-end/cases-coverage/expected/stylesheet/xsl-map-01-coverage.html, test/end-to-end/cases-coverage/expected/stylesheet/xsl-on-non-empty-01-coverage.html, test/end-to-end/cases-coverage/expected/stylesheet/xsl-sequence-01-coverage.html, test/end-to-end/cases-coverage/expected/stylesheet/xsl-sequence-01-coverage.xml, test/end-to-end/cases-coverage/xsl-evaluate-01.xsl, test/end-to-end/cases-coverage/xsl-map-01.xsl, test/end-to-end/cases-coverage/xsl-on-non-empty-01.xsl, test/end-to-end/cases-coverage/xsl-sequence-01.xsl, test/end-to-end/cases-coverage/xsl-sequence-01.xspec
This pull request marks `xsl:sequence` as 'hit' if the trace contains a hit for that element, and otherwise follows the **Use Descendant Data** rule. This pull request also adds more test cases to the coverage test for `xsl:sequence`.
At this point in the code base, the `getLocation` method is not part of the trace listener. I plan to return to #1983, currently in draft, afterward.
Fixes #1945.
---
Cc: @birdya22
=> fix(report): coverage update for xsl:sequence

test/ci/env/global.env
Release notes:
https://github.com/xmlresolver/xmlresolver/releases/tag/5.2.5
=> ci(deps): bump XMLResolver.org XML Resolver from 5.2.4 to 5.2.5

test/global-override-query.xspec, test/global-override.xqm
If an XQuery variable is declared with the `external` keyword and you run the XSpec test with Saxon, you can pass in a value of the variable from outside XSpec and override the default value. This test demonstrates that capability using Saxon custom options.
(I could be wrong, but I don't think the BaseX harnesses in this repository support passing in an external variable value when running an XSpec test with BaseX. BaseX itself supports passing in such values, though; see my BaseX command below.)
I ran the following commands on Windows, from the `test` directory. All verifications passed.
```
set SAXON_CUSTOM_OPTIONS={x-urn:test:xspec-global-override}external-value_vs_global-variable=override {x-urn:test:xspec-global-override}empty-external-value_vs_global-variable= …
```
=> test(xquery): external override of global XQuery variable

test/end-to-end/cases-coverage/expected/stylesheet/xsl-message-01-coverage.html, test/end-to-end/cases-coverage/expected/stylesheet/xsl-message-01-coverage.xml, test/end-to-end/cases-coverage/expected/stylesheet/xsl-message-02-coverage.html, test/end-to-end/cases-coverage/expected/stylesheet/xsl-message-02-coverage.xml, test/end-to-end/cases-coverage/xsl-message-01.xsl, test/end-to-end/cases-coverage/xsl-message-01.xspec, test/end-to-end/cases-coverage/xsl-message-02.xsl, test/end-to-end/cases-coverage/xsl-message-02.xspec
Based on https://github.com/xspec/xspec/issues/1963#issuecomment-2258477981, this pull request adds code coverage test cases for `xsl:message` with:
- Only text nodes as children.
- The example from https://saxonica.plan.io/issues/6492, which reports the expected coverage in Saxon 12.4 but not 12.5. I made that a separate XSLT file to simplify citing the Saxonica issue page for that XSLT code only.
=> test(report): enhance coverage tests for xsl:message

test/end-to-end/cases-coverage/expected/stylesheet/non-xsl-top-level-element-01-coverage.html, test/end-to-end/cases-coverage/non-xsl-top-level-element-01A.xsl
When evaluating the prototype Saxon listener linked from https://saxonica.plan.io/issues/6507, I realized that the unhit templates in `non-xsl-top-level-element-01.xsl` and `non-xsl-top-level-element-01A.xsl` should have distinct names. Otherwise, the latter file's template is shadowed by the importing stylesheet and an XSpec test can't possibly reach the template. My original intention with this test was for the template to be available but unreached. (The prototype listener considers the shadowed case as "unknown" but the available-unreached case as "missed.")
=> test(report): use distinct template name in imported XSLT

src/schemas/xspec.sch, test/schematron/xspec-sch-pending-focus.xspec, test/xspec-sch.xspec
This pull request addresses the part of #575 that says, "Consider creating Schematron rules for detecting meaningless `x:pending`, `@pending` or `@focus`".
This pull request includes Schematron warnings for low-hanging-fruit cases where `@focus` or `@pending` on `<x:scenario>` has no effect because of another attribute on the same element.
I considered adding a warning for `<x:pending>` all of whose child elements have `@focus` but didn't implement it. The wiki has documented `@focus` and `@pending` since 2015 (https://github.com/xspec/xspec/wiki/Writing-Scenarios/589e001005853dd24f8f6790c5f44b1ea8b8f9d1) or earlier, and I'm not aware that ineffective attributes are a large area of confusion for XSpec users.
I also considered whether an additional quick fix offer could be to remove the …
=> feat(schema): add Schematron for ineffective pending/focus attributes

src/reporter/coverage-report.xsl
As noted in https://github.com/xspec/xspec/pull/1918#discussion_r1626385686 the conditional logic is not needed. We are not actually filtering hits based on class name or associated element name. Those names have changed across recent Saxon releases and are not documented in the Saxon doc, so it is preferable not to depend on them.
Cc: @birdya22
=> refactor(report): remove unneeded code to filter coverage hits

test/ci/env/global.env
#1988 mentioned a problem testing with BaseX 11.1 in server mode. This pull request moves to 11.2, which doesn't seem to have the same problem.
---
From https://github.com/BaseXdb/basex/blob/main/CHANGELOG :
VERSION 11.2 (August 15, 2024) -----------------------------------------
- [ADD] New XQuery 4 features
- [ADD] XQuery: proc:system: new 'environment' option
- [MOD] GUI: Global Ctrl-ENTER shortcut
- [MOD] XQuery: faster evaluation of recursive functions
- [MOD] XQuery: faster invocation of HOF function parameters
- [MOD] XQuery: distinct-values: faster processing of numeric input
- [MOD] XQuery: fewer redundant type checks
- [FIX] XQuery: circularity/self-dependency checks revised
- [FIX] WebSockets (Jetty 11): Idle timeout increased to 1 hour
VERSION 11.1 (July 10, 2024) …
=> ci(deps): bump BaseX from 11.0 to 11.2

lib/schxslt/1.0/version.xsl, lib/schxslt/2.0/compile/compile-2.0.xsl, lib/schxslt/2.0/version.xsl
Replace the built-in SchXslt v1.10 with v1.10.1, using download from https://github.com/schxslt/schxslt/releases/download/v1.10.1/schxslt-1.10.1-xslt-only.zip
=> feat(schematron): bump built-in SchXslt to v1.10.1

tutorial/helper/ws-only-text/test-helper.xqm
I can imagine users copying the whitespace helper files from the XSpec tutorial directory for use in their own projects. They might want to copy only the helper file they need, plus the license file -- instead of copying the entire set of end-user files. It would be helpful if each of the helper files was self-contained. In the XSLT case, it already is. In the XQuery case, the helper module depends on one of the files under `src/`. This pull request replaces that import with similar code directly in the helper module, making the helper module self-contained.
The replacement code is not exactly the same, as the original also sorts namespace declarations and excludes the `xml` namespace. I think the helper module doesn't need these extra pieces of functionality, so I opted to make the …
=> docs(xquery): make whitespace helper file self-contained

editors/oxygen/add-on/description/latest.xhtml, oxygen-addon.xml, pom.xml, xspec.xpr
This v3.1.3 add-on has the bug fix in #2027, which motivated this release. The v3.1.3 add-on also has several changes that were merged onto the `master` branch since the start of v3.2 development. The only one I think is worth mentioning is the SchXslt upgrade.
I tested this change in Oxygen 26.1 build 2024031806 using https://github.com/galtm/xspec/raw/v3.1.3/oxygen-addon.xml . I checked the subbullets under "Test the add-on 3.1.3 with latest Oxygen" in #2031 and noticed no problems.
**This PR is seeking to merge to the `v3.1.3-release` branch, not the `master` branch.**
In a separate pull request, I will push the Oxygen commit to the `master` branch as well. I'll wait until after this PR is merged, just in case anything changes between now and then.
=> build(oxygen): add-on v3.1.3

src/schematron/schut-to-xspec.xsl, test/issue-547.xml, test/issue-547.xspec, test/schema/build.xml, test/schematron/schut-to-xspec-007-select-in.xspec, test/schematron/schut-to-xspec-007-select-out.xspec, test/schematron/schut-to-xspec-007.xml, test/schematron/schut-to-xspec-008-select-in.xspec, test/schematron/schut-to-xspec-008-select-out.xspec, test/schut-to-xspec.xspec
Issue #547 is about a Schematron validation context that uses the `select` attribute with embedded XML content. The problem was fixed in #549 by wrapping the selection in a document node, if possible.
An analogous problem occurs when the context uses the `select` attribute with `href`. You get an error, `XPDY0002  The context item is absent`, pointing to the compiled XSLT file.
This pull request adds a scenario in `issue-547.xspec` to reproduce that problem, and then provides an analogous fix.
Note: In tests for Schematron, the node selection operation of `x:context[@href][@select]` should consider the base URI to be undefined, which is like the embedded case but unlike other node selection operations that use `@href`.
=> fix(schematron): handle Schematron context with href and select

test/ci/env/global.env
From https://github.com/BaseXdb/basex/blob/main/CHANGELOG
VERSION 11.6 (November 28, 2024) ---------------------------------------
- [ADD] New XQuery 4 features (sibling axes, civil-timezone, etc)
- [ADD] job:execute: Run XQuery scripts
- [ADD] Permissions: Access to request headers and query parameters
- [ADD] New options: LOGEXCLUDE, LOGCUT
- [ADD] JSON serialization: Improved double representation
- [ADD] JSON serialization: json-lines support
- [FIX] Tomcat: improved job handling
VERSION 11.5 (October 29, 2024) ----------------------------------------
- [ADD] New XQuery 4 features (support for named record type, etc)
- [MOD] XQuery: tweaked rules for swapping comparison operands
- [FIX] Logging: Whitespace normalized
- [FIX] XQuery: transitive module imports
VERSION 11.4 (October 2, …
=> ci(deps): bump BaseX from 11.3 to 11.6

src/reporter/test-report.css
Moving the a:active style below the a:hover style in the CSS file enables the a:active style to take effect.
How to reproduce the problem:
1. Run `tutorial/escape-for-regex.xspec` to generate the HTML report
2. Scroll down to the bottom of the report, so that step 3 won't cause any further scrolling
3. Click the link on the failure label, "Strings should be escaped and status attributes should be added" (or click and hold down the mouse button, to see the effect longer)
As you do step 3, you should see the link text change its text color and background color. The bug is that without this code change, the colors stay the same because the a:active style has no effect.
Reference: Look for LVHA in this document: https://developer.mozilla.org/en-US/docs/Web/CSS/:active
=> fix(report): make active link coloring take effect

editors/oxygen/add-on/description/latest.xhtml, oxygen-addon.xml, xspec.xpr
This v3.2.0 add-on is not the v3.2 release but instead has a portion of the changes we expect to be in XSpec v3.2. I wanted to make #2045 and #2055 more easily available to users who want to try out these changes.
I tested this change in Oxygen 27.0 build 2024112212 using https://github.com/galtm/xspec/raw/oxygen-addon-3-2-0/oxygen-addon.xml . I checked the subbullets under "Test the add-on 3.2.num with latest Oxygen" in #2017 and noticed no problems.
=> build(oxygen): add-on v3.2.0

src/reporter/test-report-base.css, src/reporter/test-report-colors-blackwhite.css, src/reporter/test-report-colors-classic.css, src/reporter/test-report-colors-whiteblack.css
Fixes #2050.
In addition to relying on the analysis by @birdya22 (thanks!) and some of my own, I sanity-checked two representative reports:
- Viewed the test result report for `test/end-to-end/cases/serialize.xspec` and the coverage report for `test/end-to-end/cases-coverage/xsl-with-param-01.xspec` in a browser. Scanned the page and hovered and clicked on a few links. Looks normal.
- Modified the `test-report-base.css` file by adding a style (see below) that displays some text for each of the elements, classes, and IDs that were removed -- and also displays that text for h1. I see the text in the browser next to the h1, but that is the only instance on the page. ("Find in page" doesn't find that text, but printing to PDF and doing "find in page" there successfully finds the 1 expected …
=> refactor(report): remove obsolete CSS styles

test/ci/env/global.env
From https://github.com/BaseXdb/basex/blob/main/CHANGELOG
VERSION 11.7 (January 31, 2025) ----------------------------------------
- [ADD] XQuery: Ordered maps, preserving the insertion order
- [ADD] New Pipeline operator "->"
- [ADD] XQuery 3.1 function (finally) fn:load-xquery-module
- [ADD] New functions: fn:siblings, fn:type-of, fn:elements-to-maps
- [ADD] New parse functions: fn:parse-csv, fn:parse-html
- [ADD] HTML parsing: Support for both TagSoup and Validate.nu
- [MOD] Better readable serialization of doubles, maps and arrays
- [MOD] Store functions: only read if contents have changed
- [MOD] RESTXQERRORS option: if disabled, write error to logs
- [FIX] RESTXQ: Correct handling of query and form parameters
=> ci(deps): bump BaseX from 11.6 to 11.7

src/reporter/test-report-colors-blackwhite.css, src/reporter/test-report-colors-whiteblack.css
Fixes #2063.
I decided not to touch the classic CSS file.
This change will make it easier to add color themes that apply coloring in the same manner as the black/white themes but merely pick different color values for the named styles. The diff between the blackwhite and whiteblack CSS files is now quite small, just comments and the definitions of the named styles.
=> refactor(report): use CSS variables

test/ant/worker/generate.xsl, test/end-to-end/cases-coverage/external_issue-2071-call-function.xsl, test/end-to-end/cases-coverage/external_issue-2071-call-function.xspec
This pull request has a new end-to-end coverage test, developed by @birdya22 and provided in a ZIP-file linked from
https://github.com/xspec/xspec/issues/2071#issuecomment-2669271632
I have configured the test not to run at the moment, because of the problem documented in #2071. After that issue is completed, the changes in 9d49aa0e5d5ee1d69ecb8184e98ae9b3d5ca0f6e should be reverted to make this test operational.
=> test(xslt): end-to-end coverage test for issue 2071

src/reporter/test-report-base.css
Fixes #2077 by making the border `0px` instead of `1px`. I considered removing that style, but I thought this approach would be safer. I'm not sure how to reproduce the original problem to which the comment alludes or why the workaround worked.
With this change, I viewed a sample test result report and a sample code coverage report in Brave version 1.75.181 (uses Chromium 133.0.6943.141), Firefox version 135.0.1, and Edge version 133.0.3065.92. I made the browser narrow and wide, and I didn't see anything that looks like a line not being filled.
With the `'whiteblack'` theme, I no longer see the boxes, so #2077 is fixed. Here's a sample screen capture.
=> fix(report): avoid visible borders on headings

test/ci/env/global.env
From https://github.com/BaseXdb/basex/blob/main/CHANGELOG
VERSION 11.8 (March 20, 2025) ------------------------------------------
- [MOD] Lightning fast construction of ordered maps of all types
- [MOD] fn:distinct-values, fn:duplicate-values: faster comparisons
- [MOD] Faster map comparison (ordered and unordered)
- [ADD] New function util:values-except
- [ADD] XQuery 4.0 functionality (functions, %method annotation)
- [MOD] XQuery fold functions: more early exits
- [MOD] XQuery, fn:parse-xml: options added
- [MOD] prof:variables: Better capture of in-scope variables
- [FIX] Stricter permission checks when calling built-in functions
=> ci(deps): bump BaseX from 11.7 to 11.8

pom.xml
As per our [workflow](https://github.com/xspec/xspec/wiki/Release-Workflow), this pull request increases the version of the XSpec release and adds the snapshot suffix.
As usual, this should be the first pull request to be merged into `master` in order to start the development of XSpec v3.3.
=> build(maven): bump pom.xml to 3.3-SNAPSHOT

README.md, src/common/common-utils.xqm, src/common/common-utils.xsl, src/common/report-sequence.xqm, src/common/wrap.xsl, src/compiler/base/resolve-import/gather/distinct-nodes-stable.xsl, src/compiler/base/resolve-import/gather/gather-descriptions.xsl, src/compiler/base/util/compiler-misc-utils.xsl, src/compiler/xslt/declare-variable/declare-variable.xsl, test/xslt-package/arith/package/complex-arithmetic.xsl, test/xslt-package/arith/package/complex-arithmetic_private.xsl, test/xslt-package/filter/package/filter.xsl, third-party-licenses/W3C-document-license-2023.txt, third-party-licenses/W3C-software-license-2023.txt
The XSpec repo has some test files and other code that is copied or derived from W3C specification documents. This pull request attempts to carry out the requirements of the W3C licenses, as a good-faith effort by a layperson without a legal background. I followed the XSLT 3 spec to its GitHub source's license file, https://github.com/w3c/qtspecs/blob/master/LICENSE.md, which points to https://www.w3.org/copyright/document-license-2023/ which in turn points to https://www.w3.org/copyright/software-license-2023/ in a paragraph that mentions code examples.
The license notice in the two .xsl files here will also be needed in new test files for #2082.
=> docs: w3c licenses and citations

src/compiler/xslt/compile/compile-scenario.xsl, test/error-compiling-scenario/call-both-function-and-template.xspec, test/error-compiling-scenario/call-neither-function-nor-template.xspec, test/error-compiling-scenario/context-both-href-and-content.xspec, test/win-bats/collection.xml, test/xspec.bats
If `x:call` is ready to run the SUT but does not have either a `function` or `template` attribute on that element or through inheritance, then there is nothing to call. This commit adds a user-facing error message for that situation.
Without this change, the situation leads to a user-unfriendly error from the compiler:
```
src\compiler\xslt\compile\compile-scenario.xsl:198:34: Fatal Error!
Conditional expression: None of the conditions is satisfied, so an empty sequence is returned,
but this is not allowed as the value of variable $invocation-type
```
=> fix: reject x:call that doesn't say what to call

docs/xslt-code-coverage-by-element.md, src/reporter/coverage-compute-status.xsl, test/end-to-end/cases-coverage/expected/stylesheet/xsl-evaluate-01-coverage.html, test/end-to-end/cases-coverage/expected/stylesheet/xsl-with-param-01-coverage.html, test/end-to-end/cases-coverage/xsl-evaluate-01.xsl, test/end-to-end/cases-coverage/xsl-with-param-01.xsl
This pull request contains the XSLT change, test comment updates, and documentation update by @birdya22 from the ZIP-file linked from #2113. The XSLT change makes the coverage status of `xsl:evaluate` follow from the trace data instead of using the status 'unknown'.
I reviewed the files, which all look good to me. Thanks, @birdya22 !
Fixes #2113.
=> fix(report): xsl:evaluate coverage is known

test/ci/env/global.env
Release notes:
https://github.com/xmlresolver/xmlresolver/releases/tag/5.3.3
=> ci(deps): bump XMLResolver.org XML Resolver from 5.3.0 to 5.3.3

pom.xml, test/ci/env/saxon-12.env
* Skip Saxon 12.6 because it does not support Java 8.
* Retain 12.4 for code coverage testing with Ant, until the discussion in #2112 is complete. If the conclusion there is to use 12.7 for code coverage testing, that will be a separate pull request involving the `test/ci/env/codecoverage.env` file. (#1991 created the split between testing of code coverage and everything else.)
Cc: @birdya22 as an FYI
=> ci(deps): bump Saxon from 12.5 to 12.7 (except coverage)

test/end-to-end/cases/expected/query/serialize-result.html, test/end-to-end/cases/expected/query/serialize-result.xml, test/end-to-end/cases/expected/stylesheet/serialize-result.html, test/end-to-end/cases/expected/stylesheet/serialize-result.xml, test/end-to-end/cases/serialize.xspec
I noticed a typo in a word that's used as an element name in a test file. There is no effect on the functionality of the test, but I prefer to have the word "ordinary" spelled correctly. This PR fixes the test file and the generated expected result files.
=> test: typo: change oridinary to ordinary

test/ci/env/global.env
From https://github.com/BaseXdb/basex/blob/main/CHANGELOG
VERSION 12.0 (June 26, 2025) -------------------------------------------
🔧 Core Upgrades
- Java 17: better performance, long-term support
- Jetty 12: better compatibility, future-proofing
✨ XQuery features, 4.0
- Order-Preserving Maps: more intuitive & predictable data structures
- Map performance: significantly leaner & faster, close to native Java
- Arrays & sequences: Wrapping as arrays in constant time & vice versa
- Pipeline Operator: clean, expressive queries with the -> operator
- Typed constructs: structured data with item and record constructors
- Stack Traces, finally block: better debugging, robust error-handling
- While Clauses: better control flow in functional logic
- Standardized CSV, JSON, and HTML Parsing, support …
=> ci(deps): bump BaseX from 11.9 to 12.0

azure-pipelines.yml, test/ci/azure-pipelines_windows.yml, test/ci/set-env.cmd, test/ci/set-env.sh
Part of #2108; see https://github.com/xspec/xspec/issues/2108#issuecomment-3233020765.
=> ci: bump Java from 8 to 11 on Azure Pipelines

pom.xml
#2165 shouldn't have changed the version number in `pom.xml` because 3.3.1 is only a release candidate. This PR switches it back to `3.3-SNAPSHOT`.
Will we have any updates to make between 3.3.1 and the final release of v3.3.x?
- If so, this pull request should be merged **first**. That way, we'll get a proper snapshot and we won't have errors from Maven attempting to recreate the v3.3.1 artifacts.
- If not, this PR won't be needed and can be closed without merging.
=> fix(maven): use 3.3-snapshot between pre-release and release

pom.xml
As per our [workflow](https://github.com/xspec/xspec/wiki/Release-Workflow), this pull request increases the version of the XSpec release and adds the snapshot suffix.
As usual, this should be the first pull request to be merged into `master` in order to start the development of XSpec v3.4.
=> build(maven): bump pom.xml to 3.4-SNAPSHOT
