xspec/xspec

bin/xspec.sh
test/xspec.bats

Add support for Saxon-B (see https://github.com/expath/xspec/pull/82)

merge feature/saxon-b (expath#79)

---

.travis.yml
src/compiler/generate-xspec-tests.xsl
test/run-xspec-tests.sh
test/unit-expect-xsl.xspec
test/xspec-xslt3.xsl
test/xspec-xslt3.xspec

- add XSLT 3.0 support
- add unit test for XSLT 3.0 support
- fail test suite if compilation error
- fix relative path

add XSLT 3.0 support #9

---

.travis.yml
saxon/README.md

- remove Saxon binaries
- amend travis configuration to download Saxon jar file from Maven repo

retrieve saxon from maven repo

---

.travis.yml
test/run-xspec-tests.sh
test/unit-expect-xsl.xspec

runner script for XSpec test suite does not detect compiling issues

---

README.md
appveyor.yml
bin/xspec.bat
test/run-xspec-tests.cmd
test/xspec-bat.cmd

If you think it ok to give AppVeyor a go, please take this set of changes and it should work like [this](https://ci.appveyor.com/project/AirQuick/xspec/build/8-appveyor_master).
* `README.md`: Added a badge. May need to adjust URLs.
* `appveyor.yml`: AppVeyor config file based on [.travis.yml](https://github.com/xspec/xspec/blob/670fcfef2f549ca90afc96a967546d723b5a6a0a/.travis.yml)
* `bin/xspec.bat`: Updated to be compatible with `test/run-xspec-tests.cmd`
* `test/run-xspec-tests.cmd`: Mimics [run-xspec-tests.sh](https://github.com/xspec/xspec/blob/4449512cd1495a0bbb1862baeb2da9741270204a/test/run-xspec-tests.sh)
* `test/xspec-bat.cmd`: Mimics [xspec.bats](https://github.com/xspec/xspec/blob/706b4e6bafd338cbe45540d9757c90e82ac4848c/test/xspec.bats)

Run tests on AppVeyor

---

bin/xspec.sh
tutorial/escape-for-regex.xspec

This fixes #56 by removing obsolete references to google code repositories.

remove old references to google repos #56

---

test/xspec-bat.cmd

(This change is purely an internal enhancement.)
For some specific tests, `xspec-bat.cmd` (mimicking `xspec.bats`) performs ad hoc cleanup tasks.
This change consolidates the cleanup tasks into `:teardown`.
Also any cleanup failure is now treated as a test failure.

Consolidate cleanup tasks in xspec-bat.cmd

---

.travis.yml
appveyor.yml

... to reflect the recent product updates:
* http://www.saxonica.com/download/download_page.xml
* https://www.oxygenxml.com/xml_editor/whats_new.html#19Component_Updates

Update Saxon versions for tests

---

src/schemas/xspec.rnc

Fix for: https://github.com/xspec/xspec/issues/113
Add more annotations to defined attributes.

Added more annotations for attributes

---

bin/xspec.bat
test/xspec-bat.cmd

This change fixes #84.
In order to fix it, surrounding quotes (`"`) have been added to variable lines inside script block (`()`).

Fix issue 84

---

.travis.yml
appveyor.yml

Increment the XML Calabash version to reflect its latest release
https://github.com/ndw/xmlcalabash1/releases

Run tests with XML Calabash 1.1.16-97

---

test/xspec-xslt3.xspec

Fixes #219 
This pull request just updates the labels to reflect what the scenario actually tests.

Fix labels in test/xspec-xslt3.xspec

---

test/xspec-26.xspec

This pull request just fixes URL in a comment in `test/xspec-26.xspec`.

Fix URL in xspec-26.xspec 

---

src/ant/make-path.js

This pull request just adds a comment to `src/ant/make-path.js` to clarify why JavaScript is needed.

Add comment to make-path.js

---

pom.xml

This pull request addresses the discussion in [here](https://github.com/xspec/xspec/pull/402#issuecomment-430520323) with @cmarchand and increases the version of the `pom.xml` file in order to prepare for the next XSpec release (v1.2.0) and allow developers to publish Maven artifacts before an official release is made. 
@cmarchand: could you please review this pull request?

Increase version to prepare for next release

---

pom.xml

This pull request increments the release version in the `pom.xml` file. This is the last pull request to be merged before releasing XSpec v1.3.0.

 Increment version for v1.3.0 release

---

pom.xml

This PR increases the version of XSpec to 1.4.0 following our [release workflow](https://github.com/xspec/xspec/wiki/Release-Workflow#updating-pomxml). 
This is the last pull request to be merged into `master` before the release of XSpec v1.4.0.

release: increment xspec version for pom file

---

src/harnesses/basex/basex-server-xquery-harness.xproc
src/harnesses/basex/basex-standalone-xquery-harness.xproc
src/harnesses/exist/exist-xquery-harness.xproc
src/harnesses/harness-lib.xpl
src/harnesses/marklogic/ml-xquery-harness.xproc
src/harnesses/saxon/saxon-xquery-harness.xproc
src/harnesses/saxon/saxon-xslt-harness.xproc
src/harnesses/zorba/zorba-xquery-harness.xproc

This pull request just updates the repository URL written in the files in `src/harnesses/`.
URL is aligned with the ones in `src/compiler/`.

Update repository URL in src/harnesses/

---

test/win-bats/collection.xml

Closes #580. This pull request implements the test improvements described there.

Improve BaseX server test for Windows

---

test/ci/install-deps.cmd
test/ci/install-deps.sh

This pull request just updates the messages echoed when the installation is skipped.

ci: update installation skip message

---

test/ci/install-deps.sh

This pull request just aligns the details of `test/ci/install-deps.sh` with `test/ci/install-deps.cmd`.

ci: align install-deps.sh with .cmd

---

.travis.yml
appveyor.yml
azure-pipelines.yml
test/ci/azure-pipelines_windows.yml

This pull request just updates the version of XML Calabash used for testing.

ci: test with XML Calabash 1.1.29

---

test/end-to-end/cases/expected/query/xspec-serialize-junit.xml
test/end-to-end/cases/expected/query/xspec-serialize-result.html
test/end-to-end/cases/expected/query/xspec-serialize-result.xml
test/end-to-end/cases/expected/stylesheet/xspec-serialize-junit.xml
test/end-to-end/cases/expected/stylesheet/xspec-serialize-result.html
test/end-to-end/cases/expected/stylesheet/xspec-serialize-result.xml
test/end-to-end/cases/xspec-serialize.xspec

This pull request just adds some tests to check how attributes and processing instructions are colored in the test result reports.

Test for serialization color of attribute and processing insturction

---

build.xml
src/ant/locate-schematron-uri.xsl
src/common/xspec-utils.xsl
src/schematron/generate-step3-wrapper.xsl
src/schematron/sch-file-path.xsl
test/xspec-utils_stylesheet.xspec

Schematron file URI is resolved in multiple places. This pull request just consolidates that operation into a single function.

Locate Schematron file URI using a single function

---

.travis.yml
appveyor.yml
azure-pipelines.yml
test/ci/azure-pipelines_windows.yml

This pull request just updates the version of XML Calabash used for testing.

ci: test with XML Calabash 1.1.30

---

test/xspec-utils/parse-preserve-space.xspec

I came across this typo by chance and am fixing it.

Fix typo in code comment

---

pom.xml

Following our [workflow](https://github.com/xspec/xspec/wiki/Release-Workflow#updating-pomxml), this pull request increases the version of the XSpec release and adds the snapshot suffix. 
As usual, this should be the first pull request to be merged into `master` in order to start the development of XSpec v1.6.0.

release: increment pom.xml

---

test/end-to-end/cases/expected/query/xspec-report_schema-aware-result.html
test/end-to-end/cases/expected/query/xspec-report_schema-aware-result.xml
test/end-to-end/cases/expected/stylesheet/xspec-report_schema-aware-result.html
test/end-to-end/cases/expected/stylesheet/xspec-report_schema-aware-result.xml

This pull request just applies #770 to the expect results of the schema-aware test.

test: update expected result of schema-aware end-to-end test

---

test/tunnel-param.xsl
test/tunnel-param.xspec

`x:param/@tunnel` is not tested. This pull request just adds simple tests for it.

test(xslt): x:param/attribute(tunnel)

---

test/schematron-01.xspec
test/xspec-eqname_stylesheet.xspec
test/xspec-no-prefix_stylesheet.xspec

This pull request just syncs `xspec-no-prefix_*.xspec` with their source files.

test: sync xspec-no-prefix_*.xspec with source files

---

azure-pipelines.yml

This pull request is a workaround for Azure Pipelines not being triggered: https://developercommunity.visualstudio.com/content/problem/947762/github-pull-request-not-triggering-azure-pipelines.html

ci: specify all pr branches in azure-pipelines.yml

---

test/win-bats/collection.xml
test/xspec.bats

This pull request just adds two CLI tests: Unknown option and extra arg

test: test CLI with unknown option and extra arg

---

.github/workflows/test.yml
test/ci/run-core-tests.cmd
test/ci/set-env.cmd
test/ci/set-env.sh

This pull request integrates the CI tests into GitHub Actions. This effectively is a super set of our current Azure Pipelines, AppVeyor and Travis CI; 30 different environments run in 20 parallel nodes.
This pr modifies none of the existing files. So I'm merging this as soon as GHA ran successfully. Verification will be done in another upcoming pr.

ci: run test in GitHub Actions

---

test/ci/build_install-deps.xml
test/ci/env/README.md
test/ci/env/global.env
test/ci/env/saxon-10.env
test/ci/env/saxon-9-7.env
test/ci/extract-zip.cmd
test/ci/install-deps.cmd
test/ci/install-deps.sh
test/ci/set-env.cmd
test/ci/set-env.sh

This pull request replaces some shell scripts in `test/ci/` with an Ant build file for reducing platform dependency.

ci: install deps using Ant

---

test/win-bats/collection.xml
test/xspec.bats

This pull request just randomizes temporary paths in Bats tests.

test: randomize temp path in Bats tests

---

README.md

This pull request updates the status badges in `README.md` to reflect recent changes:
* Update Travis CI URL
* Add GitHub Actions workflows

docs: update status badges

---

test/ant/worker/build-worker_util.xml
test/ant/worker/generate.xsl
test/end-to-end/cases/custom-coverage-report.xspec
test/end-to-end/cases/expected/stylesheet/custom-coverage-report-coverage.html
test/end-to-end/cases/expected/stylesheet/custom-coverage-report-junit.xml
test/end-to-end/cases/expected/stylesheet/custom-coverage-report-result.html
test/end-to-end/cases/expected/stylesheet/custom-coverage-report-result.xml
test/win-bats/collection.xml
test/xspec.bats

This pull request enables the end-to-end test to use the specified coverage reporter.
This will make it easier to test #878.

test: test custom coverage reporter in end-to-end test

---

.github/semantic.yml

Configuration file for https://probot.github.io/apps/semantic-pull-requests/ based on the current https://github.com/xspec/xspec/blob/master/CONTRIBUTING.md

docs: configure Semantic Pull Requests

---

src/common/xspec-utils.xquery
src/common/xspec-utils.xsl

Just cleans up some expressions in `src/common/xspec-utils.*`. No logic change.

refactor: details in xspec-utils.*

---

src/compiler/generate-query-helper.xsl
src/compiler/generate-tests-helper.xsl

Just cleans up some expressions in `src/compiler/generate-*-helper.xsl`. No logic change.

refactor: details in src/compiler/generate-*-helper.xsl

---

src/compiler/generate-query-utils.xql
src/compiler/generate-tests-utils.xsl

refactor(xquery): extract deep-equal utils

---

test/ci/print-env.cmd
test/ci/print-env.sh
test/ci/switch-java.cmd

Hardcode Java 11 path until actions/virtual-environments#885 gets fixed and propagated.

ci: workaround for Azure Pipelines Java 11

---

src/compiler/generate-query-utils.xql

This pull request just simplifies `test:report-atomic-value()` using `typeswitch`.
The function already has tests in `test/generate-x-utils.xspec`.

refactor(xquery): typeswitch in test:report-atomic-value()

---

test/xspec-tvt.xspec
test/xspec-tvt_schematron.xspec

This pull request just prepends a prefix to functions in the TVT tests, to make sure that namespace prefixes are available in TVT.

test: test TVT with namespace prefix

---

test/ant/worker/generate.xsl

Following #1030, this pull request enables the test on Saxon 9.9.1.8.

test: assume Saxon bug 4621 will be fixed on Saxon 9.9.1.8

---

src/compiler/generate-common-tests.xsl
src/compiler/generate-query-helper.xsl
src/compiler/generate-tests-helper.xsl
src/compiler/generate-xspec-tests.xsl
src/reporter/format-utils.xsl

Remove verbose `/xsl:template/xsl:param[node() => empty()]/@select[. eq '()']`.

refactor: remove verbose select="()"

---

src/common/xspec-utils.xsl
src/compiler/generate-xspec-tests.xsl
test/win-bats/collection.xml
test/xspec-utils_stylesheet.xspec
test/xspec.bats
tutorial/under-the-hood/Compilation.md

Just remove prefixes from runtime `system-property()` call.

refactor(xslt): runtime system-property() using URIQualifiedName

---

editors/oxygen/add-on/description/latest.xhtml
oxygen-addon.xml
xspec.xpr

Following #1077, this pull request publishes the latest `master` via Oxygen add-on channel.
I tested this change on Oxygen 22.1 build 2020061102 using `https://github.com/AirQuick/xspec/raw/oxy-addon_2-0-2/oxygen-addon.xml`

build(oxygen): add-on v2.0.2

---

test/ci/build_install-deps.xml

Install test dependencies in parallel.

ci: install test deps in parallel

---

test/schxslt/base-uri.xsl
test/schxslt/compile-for-svrl.xsl
test/schxslt/expand.xsl
test/schxslt/include.xsl

Just update the SchXslt version used for testing.

test(schematron): test with SchXslt v1.4.7

---

test/schxslt/base-uri.xsl

Just update the SchXslt version used for testing.

test(schematron): test with SchXslt v1.5

---

test/external_nested-context.xspec
test/external_nested-function-call.xsl
test/external_nested-function-call.xspec
test/external_nested-template-call.xspec
test/nested-context.xsl
test/nested-context.xspec
test/nested-function-call.xqm
test/nested-function-call.xsl
test/nested-function-call.xspec
test/nested-template-call.xsl
test/nested-template-call.xspec

"[Nesting Scenarios](https://github.com/xspec/xspec/wiki/Nesting-Scenarios)" does not have explicit tests. This pull request adds them.
- Add a new section, "Nesting Context", in [Wiki](https://github.com/xspec/xspec/wiki/Nesting-Scenarios) and make it refer to `test/nested-context.xspec`.

test: nesting scenarios

---

test/win-bats/collection.xml
test/xspec.bats
tutorial/under-the-hood/Compilation.md
tutorial/under-the-hood/compilation-variables-scope.xspec

Add some tests to verify that "variables are evaluated once" in this statement is true:
https://github.com/xspec/xspec/blob/73b2b4c781292c9b047d23c5f3e8485855cf766b/tutorial/under-the-hood/Compilation.md#L744-L748

test: verify that x:variable is evaluated only once

---

test/ant/worker/generate.xsl
test/end-to-end/cases/report_schema-aware.xspec
test/external_xmlns.xspec
test/report-sequence_stylesheet_schema-aware.xspec
test/xmlns.xspec

#906 left some remnants. This pull request removes them.

test: remove unused components (following up pr 906)

---

test/report-sequence_xsd-1-0.xspec

Test `src/common/report-sequence.x(sl|qm)` with XSD 1.0.
(Namespace declarations in `x:description` are for XQuery.)

test(report): test report-sequence.x* with XSD 1.0

---

test/param-disallowed/description-param/static-param/query.xspec
test/param-disallowed/description-param/static-param/schematron.xspec
test/param-disallowed/description-param/static-param/stylesheet.xspec
test/win-bats/collection.xml
test/xspec.bats

Small refactoring of tests in preparation for #991.

test: refactor tests for forbidden x:param

---

test/issue-1020_stylesheet.xspec

Just update a comment in a test to reflect #1077.

test: update a TVT comment in issue-1020_stylesheet.xspec

---

test/avt.xspec
test/avt_schematron.xspec
test/avt_stylesheet.xspec
test/end-to-end/cases/expected/stylesheet/external_issue-450-451_stylesheet-result.html
test/end-to-end/cases/expected/stylesheet/external_issue-450-451_stylesheet-result.xml
test/end-to-end/cases/expected/stylesheet/issue-450-451_stylesheet-result.xml
test/end-to-end/cases/external_issue-450-451_stylesheet.xspec
test/end-to-end/cases/issue-450-451_stylesheet.xspec
test/node-selection_stylesheet.xspec
test/prefix-conflict_stylesheet.xspec
test/tvt.xspec
test/tvt_schematron.xspec
test/tvt_stylesheet.xspec
test/undeclare-ns_stylesheet.xspec
test/user-content-utils.xspec
test/ws-only-text.xspec
test/ws-only-text_stylesheet.xspec
test/xml-base_stylesheet.xspec

Minor refactoring of tests in preparation for #991.

test: refactor tests to prepare for issue 991

---

editors/oxygen/add-on/description/latest.xhtml
oxygen-addon.xml
xspec.xpr

I tested this change on Oxygen 23.0 build 2020121712 using `https://github.com/AirQuick/xspec/raw/oxy-addon_2-1-1/oxygen-addon.xml`.

build(oxygen): add-on v2.1.1

---

test/ci/install-deps.cmd
test/ci/install-deps.sh
test/ci/install-jing.sh

Add [`--retry-connrefused`](https://curl.se/docs/manpage.html#--retry-connrefused) to `curl` options for more stability.

ci: add --retry-connrefused curl option

---

test/ci/install-deps.cmd
test/ci/install-deps.sh
test/ci/install-jing.sh

as a workaround for curl/curl#4461

ci: add --connect-timeout curl option

---

test/ci/env/global.env

> VERSION 9.5 (February 25, 2021) ----------------------------------------
> 
>  RESTXQ
>  - the client IP address behind a proxy is added to the logs
>  - stack traces in the error message can now be suppressed
>  - the default error code has been changed from 400 to 500
>  - error messages are more user-friendly now (#1708)
>  - content negotiation was improved (#1991)
>  - inline arguments of called function (#1982)
> 
>  XQUERY FUNCTIONS
>  - Utility: new functions for sequences, arrays and maps
>  - Higher-Order Functions: hof:drop-while
>  - Jobs: More options for job intervals
> 
>  XQUERY PERFORMANCE
>  - revised scoring propagation (all items will take less memory)
>  - default function inlining limit reduced from 100 to 50
> …

ci(deps): bump BaseX from 9.4.6 to 9.5

---

test/issue-1029.xsl
test/issue-1029.xspec

Add some `x:expect` to `test/issue-1029.xspec` for ensuring that `test/issue-1029.xsl` is written properly.

test(xslt): verify stylesheet components in testing issue 1029

---

README.md

Just update 301 Moved Permanently links in `README.md`.

docs: update links in README.md

---

editors/oxygen/add-on/description/latest.xhtml
oxygen-addon.xml
xspec.xpr

I tested this change on Oxygen 23.1 build 2021030206 using `https://github.com/AirQuick/xspec/raw/oxy-addon_2-1-2/oxygen-addon.xml`.

build(oxygen): add-on v2.1.2

---

test/ci/build_install-deps.xml

Just consolidate common `get` tasks in `test/ci/build_install-deps.xml` into a `macrodef`.

ci: macrodef get task in build_install-deps.xml

---

test/ci/env/global.env

> VERSION 9.6 (August 19, 2021) ------------------------------------------
> 
>  XQUERY: MODULES, FEATURES
>  - Archive Module, archive:write: stream large archives to file
>  - SQL Module: support for more SQL types
>  - Full-Text Module, ft:thesaurus: perform Thesaurus queries
>  - Fulltext, fuzzy search: specify Levenshtein limit
>  - UNROLLLIMIT option: controll limit for unrolling loops
> 
>  XQUERY: JAVA BINDINGS
>  - Java objects of unknown type are wrapped into function items
>  - results of constructor calls are returned as function items
>  - the standard package java.lang. has become optional
>  - array arguments can be specified with the middle dot notation
>  - conversion can be controlled with the WRAPJAVA option
>  - …

ci(deps): bump BaseX from 9.5.2 to 9.6

---

.github/workflows/lint.yml
.github/workflows/pr-lint.yml
.github/workflows/test.yml
azure-pipelines.yml
package-lock.json
package.json
test/bats-helper.bash
test/ci/npm-ci.sh
test/ci/run-commitlint.sh
test/ci/run-prettier.sh
test/ci/set-env.sh
test/ci/uninstall-bats-macos.sh
test/rnc.bats
test/run-bats.sh
test/win-bats/collection.xml
test/win-bats/stub.cmd
test/xspec.bats

- Install Bats using npm on both Linux and macOS
- Remove a workaround for a Bats bug fixed by v1.5.0
- Use recent Bats new features

test: test with Bats v1.5.0

---

tutorial/under-the-hood/Compilation.md

#1329 forgot to update `tutorial/under-the-hood/Compilation.md`. This pull request delivers it.

docs(xslt): update under-the-hood/Compilation.md to reflect PR 1329

---

test/ci/env/global.env

From https://github.com/BaseXdb/basex/blob/9/CHANGELOG
> VERSION 9.7.3 (June 30, 2022) ------------------------------------------
> 
>  - DBA: Improved support for database backups
>  - Performance tweaks and bug fixes
>  - BaseX 10 preview: Store Module (before: Caching Module)
>  - BaseX 10 preview: Backup of general data (users, jobs, stores)
> 
> VERSION 9.7.2 (May 14, 2022) -------------------------------------------
> 
>  - English Stemmer: dictionary for irregular forms added
>  - Preview implementations of BaseX 10 features
>  - Performance tweaks, minor fixes
> 
> VERSION 9.7.1 (April 26, 2022) -----------------------------------------
> 
>  - RESTXQ: improved caching for unmodified modules
>  - GUI: improved support for middle mouse button
>  - GUI, editor: list opened files …

ci(deps): bump BaseX from 9.6.4 to 9.7.3

---

.github/workflows/lint.yml
package-lock.json
test/ci/npm-ci.sh

This pull request imitates #1693 on the schxslt branch

ci: adapt to npm v9 on schxslt branch

---

test/ci/env/global.env

https://github.com/BaseXdb/basex/blob/main/CHANGELOG
> VERSION 10.6 (May 4, 2023) ---------------------------------------------
> 
>  - XQuery: Much more memory-efficient representation of XML fragments
>  - XQuery: Faster access to substrings and single characters
>  - XQuery: Faster iterations with the simple map operator 
>  - XQuery 4: more preview features available
>  - CSV/JSON conversions: Less memory consumption
>  - CSV parsing: option for skipping empty fields
>  - GUI, editor: better code completion
>  - Less reflection: Direct acccess to TagSoup, iXml, JLine
>  - Minor bug fixes
> 
> VERSION 10.5 (March 23, 2023) ------------------------------------------
> 
>  - new XQuery 4 features
>  - numerous performance tweaks
>  - minor bug fixes
> 
> VERSION 10.4 (December 1, 2022) …

ci(deps): bump BaseX from 10.1 to 10.6

---

test/ci/env/global.env

https://github.com/BaseXdb/basex/blob/main/CHANGELOG
> VERSION 10.7 (August 4, 2023) ------------------------------------------
> 
>  - GUI, Editor: Full support for Unicode characters
>  - GUI, Editor: Faster font rendering (font dialog: anti-aliasing)
>  - XQuery 4: New features, functions, operators
>  - BaseX 11 preview features (see the documentation)
>  - bug fix: web:forward, write concluding log entry
>  - bug fix: job:eval, re-initialize scheduled jobs
>  - various other bug fixes

ci(deps): bump BaseX from 10.6 to 10.7

---

editors/oxygen/add-on/description/latest.xhtml
oxygen-addon.xml
pom.xml
xspec.xpr

This pull request is for the checklist item in #1657 that says, "Create a pull request incrementing the version (to `2.3` without `-SNAPSHOT`) of `pom.xml` and the Oxygen add-on and merge it into `master`".
It increments the version numbers to make the official stable release of v2.3. (technically v2.3.2, based on https://github.com/xspec/xspec/issues/940).
I tested the Oxygen add-on in Oxygen 25.1 using https://github.com/galtm/xspec/raw/rel_2-3-2/oxygen-addon.xml.

build: release v2.3.2

---

test/ci/env/saxon-10.env
test/ci/env/saxon-11.env
test/ci/env/saxon-12.env

Update the XML Calabash versions used for testing.

ci(deps): bump XML Calabash from 1.5.6 to 1.5.7

---

test/ci/codespell-dic.txt
test/ci/run-codespell.cmd
test/ci/run-codespell.sh

Following #1801, this PR adds a custom `codespell` dictionary.

ci: codespell XLST

---

README.md
pom.xml

Updated documentation to reflect @galtm is an admin of this repository.

docs: add galtm as a maintainer

---

test/catalog/01/imported-xspec-uri.xspec
test/x-context.xspec

This PR has a minor simplification in a test, and a comment update. The two changes are related only in that I noticed the opportunities for improvement while working on #1771.

refactor: simplify "for" expression in test

---

editors/oxygen/add-on/description/latest.xhtml
oxygen-addon.xml
pom.xml
xspec.xpr

This pull request is for the checklist item in #1890 that says, "Create a pull request incrementing the version (to 3.0 without -SNAPSHOT) in pom.xml and the Oxygen add-on, and merge it into master".
It increments the version numbers to make the official stable release of v3.0. (technically v3.0.3, based on https://github.com/xspec/xspec/issues/940).
I tested the Oxygen add-on in Oxygen 26.1 using `https://github.com/galtm/xspec/raw/rel_3-0-3/oxygen-addon.xml`.

build: release v3.0.3

---

docs/xslt-code-coverage-by-element.md

Fixes #1958. Thanks to @birdya22 for the corrections.

docs: update coverage information about xsl:with-param

---

docs/xslt-code-coverage-by-element.md

docs: update coverage rule for xsl:context-item

---

test/ci/env/global.env

https://github.com/BaseXdb/basex/blob/main/CHANGELOG
>VERSION 11.0 (June 6, 2024) --------------------------------------------
>
> STORAGE
> - Key/value Store: Better compactification when storing values
> - CSV/JSON/XML parsing: reduced memory consumption
>
> XQUERY
> - First release with new 4.0 features
> - Numerous new built-in functions (standard, maps, arrays, math)
> - Updates: Multiple targets in rename/replace/insert expressions
> - New custom functions: archive:refresh, validate:xsd-init, xslt:init
> - Full support for Invisible XML.
>
> GENERAL
> - GUI: Full Unicode character support
> - Web Server: Upgrade to Jetty 11
> - Command-Line: New options -C, -Q, -W
> - Options: WRITESTORE, writes store to disk at shutdown time

ci(deps): bump BaseX from 10.7 to 11.0

---

test/end-to-end/cases/focus-vs-pending-attribute.xspec
test/end-to-end/cases/focus-vs-pending-element.xspec
test/end-to-end/cases/shared-like.xspec
test/focus-ignored-by-like.xspec
test/pending-ignored-by-like.xspec
test/pending-scenario-features-inherited-by-focus.xspec
test/pending-shared-variable-inherited-by-focus.xspec

This pull request adds tests corresponding to the "Potential new test cases" section of https://github.com/xspec/xspec/issues/575#issuecomment-1837518117

test: more tests for pending/focus feature

---

.github/workflows/maven-deploy.yml

This pull request reverts 9e5a1df32d7978bcc6b7e362c9fa6c337c9d32e2, which was an experiment as part of #2009.
Cc: @cmarchand

build(deps): revert verify/deploy change

---

editors/oxygen/add-on/description/latest.xhtml
oxygen-addon.xml
pom.xml
xspec.xpr

This pull request is for the checklist item in #1912 that says, "Create a pull request replacing `-SNAPSHOT` with the number, _num_, in `pom.xml` and the Oxygen add-on. Merge it into master".
It increments the version numbers to make the official stable release of v3.1. (technically v3.1.2, based on #940).
I tested the Oxygen add-on in Oxygen 26.1 using https://github.com/galtm/xspec/raw/v3.1.2/oxygen-addon.xml.

build: release v3.1.2

---

editors/oxygen/add-on/description/latest.xhtml
oxygen-addon.xml
xspec.xpr

This PR is like #2032 except that
- It seeks to merge to the `master` branch
- It has only the Oxygen commit (cherry-picked from build(oxygen): add-on v3.1.3), not the pom.xml change

build(oxygen): add-on v3.1.3 for master branch

---

docs/xslt-code-coverage-by-element.md
test/end-to-end/cases-coverage/expected/stylesheet/xsl-fork-01-coverage.html
test/end-to-end/cases-coverage/expected/stylesheet/xsl-fork-01-coverage.xml
test/end-to-end/cases-coverage/xsl-fork-01.xsl
test/end-to-end/cases-coverage/xsl-fork-01.xspec

This pull request contains the test case and documentation update by @birdya22 from the ZIP-file linked from #2098. I reviewed the files, which all look good to me. Thanks, @birdya22 !
Fixes #2098.

test(report): coverage test case for xsl:fork

---

pom.xml

Solves issue #2143.
Same content as 3.2.2, just to check maven migration

build: release 3.2.3

---

src/xproc3/xquery-harness.xproc
src/xproc3/xslt-harness.xproc
test/win-bats/collection.xml
test/xspec.bats

refactor: move/rename XProc 3 harnesses

---

lib/README.md
lib/XQS/compile.xqm
lib/XQS/dry-run.xqm
lib/XQS/evaluate.xqm
lib/XQS/include-expand.xqm
lib/XQS/svrl.xqm
lib/XQS/utils.xqm

Replace the built-in XQS v1.0.3 with v1.1.0.

feat(schematron): bump built-in XQS to v1.1.0

---

lib/XQS/evaluate.xqm
lib/XQS/svrl.xqm

Replace the built-in XQS v1.1.0 with v1.1.2.

feat(schematron): bump built-in XQS to v1.1.2
